# ------------------------------------------------------------------
# GENERATED FILE - DO NOT EDIT.
#
# Generated by scripts/contracts-generate-ai.sh from the JSON Schema in
# apps/api/internal/events/schema, which is itself generated from the Go
# event structs in apps/api/internal/events (`make contracts-generate`).
# ------------------------------------------------------------------

from jobfinder_ai.contracts.enrich_work import EnrichWork
from jobfinder_ai.contracts.envelope import Envelope
from jobfinder_ai.contracts.failure import Failure
from jobfinder_ai.contracts.generate_work import GenerateWork
from jobfinder_ai.contracts.ghost_work import GhostWork
from jobfinder_ai.contracts.ingest_work import IngestWork
from jobfinder_ai.contracts.match_work import MatchWork
from jobfinder_ai.contracts.result import Result
from jobfinder_ai.contracts.salary_work import SalaryWork
from jobfinder_ai.contracts.usage import Usage

__all__ = [
    "EnrichWork",
    "Envelope",
    "Failure",
    "GenerateWork",
    "GhostWork",
    "IngestWork",
    "MatchWork",
    "Result",
    "SalaryWork",
    "Usage",
]
