# ------------------------------------------------------------------
# GENERATED FILE - DO NOT EDIT.
#
# Generated by scripts/contracts-generate-ai.sh from the JSON Schema in
# apps/api/internal/events/schema, which is itself generated from the Go
# event structs in apps/api/internal/events (`make contracts-generate`).
# ------------------------------------------------------------------
# generated by datamodel-codegen:
#   filename:  failure.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Failure(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: str
    retryable: bool
    message: str
    failed_step: str | None = None
