# ------------------------------------------------------------------
# GENERATED FILE - DO NOT EDIT.
#
# Generated by scripts/contracts-generate-ai.sh from the JSON Schema in
# apps/api/internal/events/schema, which is itself generated from the Go
# event structs in apps/api/internal/events (`make contracts-generate`).
# ------------------------------------------------------------------
# generated by datamodel-codegen:
#   filename:  ghost_work.schema.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict


class GhostWork(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    jobId: str
    activityId: str | None = None
    snapshot: dict[str, Any]
    snapshot_hash: str
