# ------------------------------------------------------------------
# GENERATED FILE - DO NOT EDIT.
#
# Generated by scripts/contracts-generate-ai.sh from the JSON Schema in
# apps/api/internal/events/schema, which is itself generated from the Go
# event structs in apps/api/internal/events (`make contracts-generate`).
# ------------------------------------------------------------------
# generated by datamodel-codegen:
#   filename:  usage.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Usage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_tokens: int | None = None
    output_tokens: int | None = None
    cost_usd: float | None = None
