// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activityrun.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteActivityRunsBefore = `-- name: DeleteActivityRunsBefore :exec
DELETE FROM "ActivityRun" WHERE "createdAt" < $1
`

func (q *Queries) DeleteActivityRunsBefore(ctx context.Context, createdat pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteActivityRunsBefore, createdat)
	return err
}

const finishActivityRunCancelled = `-- name: FinishActivityRunCancelled :exec
UPDATE "ActivityRun" SET "state" = 'cancelled', "error" = $2, "finishedAt" = now() WHERE "id" = $1
`

type FinishActivityRunCancelledParams struct {
	ID    pgtype.UUID `json:"id"`
	Error *string     `json:"error"`
}

func (q *Queries) FinishActivityRunCancelled(ctx context.Context, arg FinishActivityRunCancelledParams) error {
	_, err := q.db.Exec(ctx, finishActivityRunCancelled, arg.ID, arg.Error)
	return err
}

const finishActivityRunError = `-- name: FinishActivityRunError :exec
UPDATE "ActivityRun" SET "state" = 'failed', "error" = $2, "finishedAt" = now() WHERE "id" = $1
`

type FinishActivityRunErrorParams struct {
	ID    pgtype.UUID `json:"id"`
	Error *string     `json:"error"`
}

func (q *Queries) FinishActivityRunError(ctx context.Context, arg FinishActivityRunErrorParams) error {
	_, err := q.db.Exec(ctx, finishActivityRunError, arg.ID, arg.Error)
	return err
}

const finishActivityRunOk = `-- name: FinishActivityRunOk :exec
UPDATE "ActivityRun" SET "state" = 'succeeded', "refId" = $2, "meta" = COALESCE($3, "meta"), "finishedAt" = now() WHERE "id" = $1
`

type FinishActivityRunOkParams struct {
	ID    pgtype.UUID `json:"id"`
	RefId *string     `json:"refId"`
	Meta  []byte      `json:"meta"`
}

func (q *Queries) FinishActivityRunOk(ctx context.Context, arg FinishActivityRunOkParams) error {
	_, err := q.db.Exec(ctx, finishActivityRunOk, arg.ID, arg.RefId, arg.Meta)
	return err
}

const insertActivityRun = `-- name: InsertActivityRun :one
INSERT INTO "ActivityRun" ("op", "label", "jobId", "sourceKey", "queueTaskId", "meta")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, op, state, label, step, "jobId", "sourceKey", "queueTaskId", "refId", error, meta, "createdAt", "startedAt", "finishedAt"
`

type InsertActivityRunParams struct {
	Op          string      `json:"op"`
	Label       string      `json:"label"`
	JobId       pgtype.UUID `json:"jobId"`
	SourceKey   *string     `json:"sourceKey"`
	QueueTaskId *string     `json:"queueTaskId"`
	Meta        []byte      `json:"meta"`
}

func (q *Queries) InsertActivityRun(ctx context.Context, arg InsertActivityRunParams) (ActivityRun, error) {
	row := q.db.QueryRow(ctx, insertActivityRun,
		arg.Op,
		arg.Label,
		arg.JobId,
		arg.SourceKey,
		arg.QueueTaskId,
		arg.Meta,
	)
	var i ActivityRun
	err := row.Scan(
		&i.ID,
		&i.Op,
		&i.State,
		&i.Label,
		&i.Step,
		&i.JobId,
		&i.SourceKey,
		&i.QueueTaskId,
		&i.RefId,
		&i.Error,
		&i.Meta,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listActiveActivityRuns = `-- name: ListActiveActivityRuns :many
SELECT id, op, state, label, step, "jobId", "sourceKey", "queueTaskId", "refId", error, meta, "createdAt", "startedAt", "finishedAt" FROM "ActivityRun" WHERE "state" IN ('queued', 'running') ORDER BY "createdAt" DESC
`

func (q *Queries) ListActiveActivityRuns(ctx context.Context) ([]ActivityRun, error) {
	rows, err := q.db.Query(ctx, listActiveActivityRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityRun
	for rows.Next() {
		var i ActivityRun
		if err := rows.Scan(
			&i.ID,
			&i.Op,
			&i.State,
			&i.Label,
			&i.Step,
			&i.JobId,
			&i.SourceKey,
			&i.QueueTaskId,
			&i.RefId,
			&i.Error,
			&i.Meta,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedActivityRuns = `-- name: ListFailedActivityRuns :many
SELECT id, op, state, label, step, "jobId", "sourceKey", "queueTaskId", "refId", error, meta, "createdAt", "startedAt", "finishedAt" FROM "ActivityRun"
WHERE "state" IN ('failed', 'cancelled') AND ($1::text IS NULL OR "op" = $1)
ORDER BY "createdAt" DESC
`

// Includes "cancelled" runs (e.g. skipped because of an upstream rate limit)
// alongside "failed" ones — both are retryable the same way.
func (q *Queries) ListFailedActivityRuns(ctx context.Context, op *string) ([]ActivityRun, error) {
	rows, err := q.db.Query(ctx, listFailedActivityRuns, op)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityRun
	for rows.Next() {
		var i ActivityRun
		if err := rows.Scan(
			&i.ID,
			&i.Op,
			&i.State,
			&i.Label,
			&i.Step,
			&i.JobId,
			&i.SourceKey,
			&i.QueueTaskId,
			&i.RefId,
			&i.Error,
			&i.Meta,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivityRuns = `-- name: ListRecentActivityRuns :many
SELECT id, op, state, label, step, "jobId", "sourceKey", "queueTaskId", "refId", error, meta, "createdAt", "startedAt", "finishedAt" FROM "ActivityRun" ORDER BY "createdAt" DESC LIMIT $1
`

func (q *Queries) ListRecentActivityRuns(ctx context.Context, limit int32) ([]ActivityRun, error) {
	rows, err := q.db.Query(ctx, listRecentActivityRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityRun
	for rows.Next() {
		var i ActivityRun
		if err := rows.Scan(
			&i.ID,
			&i.Op,
			&i.State,
			&i.Label,
			&i.Step,
			&i.JobId,
			&i.SourceKey,
			&i.QueueTaskId,
			&i.RefId,
			&i.Error,
			&i.Meta,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActivityStep = `-- name: SetActivityStep :exec
UPDATE "ActivityRun" SET "step" = $2, "meta" = COALESCE($3, "meta") WHERE "id" = $1
`

type SetActivityStepParams struct {
	ID   pgtype.UUID `json:"id"`
	Step *string     `json:"step"`
	Meta []byte      `json:"meta"`
}

func (q *Queries) SetActivityStep(ctx context.Context, arg SetActivityStepParams) error {
	_, err := q.db.Exec(ctx, setActivityStep, arg.ID, arg.Step, arg.Meta)
	return err
}

const startActivityRun = `-- name: StartActivityRun :exec
UPDATE "ActivityRun" SET "state" = 'running', "startedAt" = now() WHERE "id" = $1
`

func (q *Queries) StartActivityRun(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, startActivityRun, id)
	return err
}
