// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activityrun.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkInsertActivities = `-- name: BulkInsertActivities :many
INSERT INTO "ActivityRun" ("op", "label", "jobId", "sourceKey")
SELECT o, l, j, NULLIF(sk, '')
FROM (
  SELECT unnest($1::text[]) AS o,
         unnest($2::text[]) AS l,
         unnest($3::uuid[]) AS j,
         unnest($4::text[]) AS sk
) AS x
RETURNING "id", "jobId", "op"
`

type BulkInsertActivitiesParams struct {
	Ops        []string      `json:"ops"`
	Labels     []string      `json:"labels"`
	JobIds     []pgtype.UUID `json:"job_ids"`
	SourceKeys []string      `json:"source_keys"`
}

type BulkInsertActivitiesRow struct {
	ID    pgtype.UUID `json:"id"`
	JobId pgtype.UUID `json:"jobId"`
	Op    string      `json:"op"`
}

// Batch form of the per-task activity.New insert. Without this the N+1 simply
// moves from the persist loop to the enqueue loop and SC-002 is not met.
// Returns "jobId" and "op" alongside "id" so the caller correlates by
// (job, op) rather than by row order, which is not guaranteed.
// The column set follows the actual "ActivityRun" schema (00004/00030), not
// the kind/status names in the contract: the table's columns are "op" and
// "state", "state" defaults to 'queued' and "meta" defaults to '{}'.
// The arrays are zipped by parallel unnest() calls in a subquery select list
// rather than the multi-argument unnest(a, b, ...) table form, which sqlc's
// analyzer cannot resolve; PostgreSQL evaluates them in lockstep either way.
func (q *Queries) BulkInsertActivities(ctx context.Context, arg BulkInsertActivitiesParams) ([]BulkInsertActivitiesRow, error) {
	rows, err := q.db.Query(ctx, bulkInsertActivities,
		arg.Ops,
		arg.Labels,
		arg.JobIds,
		arg.SourceKeys,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BulkInsertActivitiesRow
	for rows.Next() {
		var i BulkInsertActivitiesRow
		if err := rows.Scan(&i.ID, &i.JobId, &i.Op); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteActivityRunsBefore = `-- name: DeleteActivityRunsBefore :exec
DELETE FROM "ActivityRun" WHERE "createdAt" < $1
`

func (q *Queries) DeleteActivityRunsBefore(ctx context.Context, createdat pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteActivityRunsBefore, createdat)
	return err
}

const finishActivityRunCancelled = `-- name: FinishActivityRunCancelled :exec
UPDATE "ActivityRun" SET "state" = 'cancelled', "error" = $2, "finishedAt" = now() WHERE "id" = $1
`

type FinishActivityRunCancelledParams struct {
	ID    pgtype.UUID `json:"id"`
	Error *string     `json:"error"`
}

func (q *Queries) FinishActivityRunCancelled(ctx context.Context, arg FinishActivityRunCancelledParams) error {
	_, err := q.db.Exec(ctx, finishActivityRunCancelled, arg.ID, arg.Error)
	return err
}

const finishActivityRunError = `-- name: FinishActivityRunError :exec
UPDATE "ActivityRun" SET "state" = 'failed', "error" = $2, "finishedAt" = now() WHERE "id" = $1
`

type FinishActivityRunErrorParams struct {
	ID    pgtype.UUID `json:"id"`
	Error *string     `json:"error"`
}

func (q *Queries) FinishActivityRunError(ctx context.Context, arg FinishActivityRunErrorParams) error {
	_, err := q.db.Exec(ctx, finishActivityRunError, arg.ID, arg.Error)
	return err
}

const finishActivityRunInterrupted = `-- name: FinishActivityRunInterrupted :exec
UPDATE "ActivityRun" SET "state" = 'interrupted', "error" = $2, "finishedAt" = now() WHERE "id" = $1 AND "state" = 'queued'
`

type FinishActivityRunInterruptedParams struct {
	ID    pgtype.UUID `json:"id"`
	Error *string     `json:"error"`
}

// Per-row finalizer for a stale queued run past ACTIVITY_QUEUED_GRACE, one
// row at a time.
func (q *Queries) FinishActivityRunInterrupted(ctx context.Context, arg FinishActivityRunInterruptedParams) error {
	_, err := q.db.Exec(ctx, finishActivityRunInterrupted, arg.ID, arg.Error)
	return err
}

const finishActivityRunOk = `-- name: FinishActivityRunOk :exec
UPDATE "ActivityRun" SET "state" = 'succeeded', "refId" = $2, "meta" = COALESCE($3, "meta"), "finishedAt" = now() WHERE "id" = $1
`

type FinishActivityRunOkParams struct {
	ID    pgtype.UUID `json:"id"`
	RefId *string     `json:"refId"`
	Meta  []byte      `json:"meta"`
}

func (q *Queries) FinishActivityRunOk(ctx context.Context, arg FinishActivityRunOkParams) error {
	_, err := q.db.Exec(ctx, finishActivityRunOk, arg.ID, arg.RefId, arg.Meta)
	return err
}

const finishActivityRunTimedOut = `-- name: FinishActivityRunTimedOut :exec
UPDATE "ActivityRun" SET "state" = 'timed_out', "error" = $2, "finishedAt" = now() WHERE "id" = $1 AND "state" = 'running'
`

type FinishActivityRunTimedOutParams struct {
	ID    pgtype.UUID `json:"id"`
	Error *string     `json:"error"`
}

func (q *Queries) FinishActivityRunTimedOut(ctx context.Context, arg FinishActivityRunTimedOutParams) error {
	_, err := q.db.Exec(ctx, finishActivityRunTimedOut, arg.ID, arg.Error)
	return err
}

const getActivityRun = `-- name: GetActivityRun :one
SELECT id, op, state, label, step, "jobId", "sourceKey", "queueTaskId", "refId", error, meta, "createdAt", "startedAt", "finishedAt", "heartbeatAt", "timeoutMs" FROM "ActivityRun" WHERE "id" = $1
`

func (q *Queries) GetActivityRun(ctx context.Context, id pgtype.UUID) (ActivityRun, error) {
	row := q.db.QueryRow(ctx, getActivityRun, id)
	var i ActivityRun
	err := row.Scan(
		&i.ID,
		&i.Op,
		&i.State,
		&i.Label,
		&i.Step,
		&i.JobId,
		&i.SourceKey,
		&i.QueueTaskId,
		&i.RefId,
		&i.Error,
		&i.Meta,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HeartbeatAt,
		&i.TimeoutMs,
	)
	return i, err
}

const insertActivityRun = `-- name: InsertActivityRun :one
INSERT INTO "ActivityRun" ("op", "label", "jobId", "sourceKey", "queueTaskId", "meta")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, op, state, label, step, "jobId", "sourceKey", "queueTaskId", "refId", error, meta, "createdAt", "startedAt", "finishedAt", "heartbeatAt", "timeoutMs"
`

type InsertActivityRunParams struct {
	Op          string      `json:"op"`
	Label       string      `json:"label"`
	JobId       pgtype.UUID `json:"jobId"`
	SourceKey   *string     `json:"sourceKey"`
	QueueTaskId *string     `json:"queueTaskId"`
	Meta        []byte      `json:"meta"`
}

func (q *Queries) InsertActivityRun(ctx context.Context, arg InsertActivityRunParams) (ActivityRun, error) {
	row := q.db.QueryRow(ctx, insertActivityRun,
		arg.Op,
		arg.Label,
		arg.JobId,
		arg.SourceKey,
		arg.QueueTaskId,
		arg.Meta,
	)
	var i ActivityRun
	err := row.Scan(
		&i.ID,
		&i.Op,
		&i.State,
		&i.Label,
		&i.Step,
		&i.JobId,
		&i.SourceKey,
		&i.QueueTaskId,
		&i.RefId,
		&i.Error,
		&i.Meta,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HeartbeatAt,
		&i.TimeoutMs,
	)
	return i, err
}

const listActiveActivityRuns = `-- name: ListActiveActivityRuns :many
SELECT id, op, state, label, step, "jobId", "sourceKey", "queueTaskId", "refId", error, meta, "createdAt", "startedAt", "finishedAt", "heartbeatAt", "timeoutMs" FROM "ActivityRun" WHERE "state" IN ('queued', 'running') ORDER BY "createdAt" DESC
`

func (q *Queries) ListActiveActivityRuns(ctx context.Context) ([]ActivityRun, error) {
	rows, err := q.db.Query(ctx, listActiveActivityRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityRun
	for rows.Next() {
		var i ActivityRun
		if err := rows.Scan(
			&i.ID,
			&i.Op,
			&i.State,
			&i.Label,
			&i.Step,
			&i.JobId,
			&i.SourceKey,
			&i.QueueTaskId,
			&i.RefId,
			&i.Error,
			&i.Meta,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.HeartbeatAt,
			&i.TimeoutMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedActivityRuns = `-- name: ListFailedActivityRuns :many
SELECT id, op, state, label, step, "jobId", "sourceKey", "queueTaskId", "refId", error, meta, "createdAt", "startedAt", "finishedAt", "heartbeatAt", "timeoutMs" FROM "ActivityRun"
WHERE "state" IN ('failed', 'cancelled', 'timed_out', 'interrupted') AND ($1::text IS NULL OR "op" = $1)
ORDER BY "createdAt" DESC
`

// Includes "cancelled" (e.g. skipped because of an upstream rate limit),
// "timed_out" (exceeded its task-type deadline), and "interrupted" (worker
// vanished) alongside "failed" — all four are retryable the same way.
func (q *Queries) ListFailedActivityRuns(ctx context.Context, op *string) ([]ActivityRun, error) {
	rows, err := q.db.Query(ctx, listFailedActivityRuns, op)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityRun
	for rows.Next() {
		var i ActivityRun
		if err := rows.Scan(
			&i.ID,
			&i.Op,
			&i.State,
			&i.Label,
			&i.Step,
			&i.JobId,
			&i.SourceKey,
			&i.QueueTaskId,
			&i.RefId,
			&i.Error,
			&i.Meta,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.HeartbeatAt,
			&i.TimeoutMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivityRuns = `-- name: ListRecentActivityRuns :many
SELECT id, op, state, label, step, "jobId", "sourceKey", "queueTaskId", "refId", error, meta, "createdAt", "startedAt", "finishedAt", "heartbeatAt", "timeoutMs" FROM "ActivityRun" ORDER BY "createdAt" DESC LIMIT $1
`

func (q *Queries) ListRecentActivityRuns(ctx context.Context, limit int32) ([]ActivityRun, error) {
	rows, err := q.db.Query(ctx, listRecentActivityRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityRun
	for rows.Next() {
		var i ActivityRun
		if err := rows.Scan(
			&i.ID,
			&i.Op,
			&i.State,
			&i.Label,
			&i.Step,
			&i.JobId,
			&i.SourceKey,
			&i.QueueTaskId,
			&i.RefId,
			&i.Error,
			&i.Meta,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.HeartbeatAt,
			&i.TimeoutMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleQueuedActivityRuns = `-- name: ListStaleQueuedActivityRuns :many
SELECT id, op, state, label, step, "jobId", "sourceKey", "queueTaskId", "refId", error, meta, "createdAt", "startedAt", "finishedAt", "heartbeatAt", "timeoutMs" FROM "ActivityRun" WHERE "state" = 'queued' AND "createdAt" < $1
`

// Rows past the queued grace window (ACTIVITY_QUEUED_GRACE). RabbitMQ has
// no per-message "does this still exist" query the way asynq's Inspector
// did, so these rows are DB-authoritative: past the grace window means
// interrupted, unconditionally.
func (q *Queries) ListStaleQueuedActivityRuns(ctx context.Context, cutoff pgtype.Timestamp) ([]ActivityRun, error) {
	rows, err := q.db.Query(ctx, listStaleQueuedActivityRuns, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityRun
	for rows.Next() {
		var i ActivityRun
		if err := rows.Scan(
			&i.ID,
			&i.Op,
			&i.State,
			&i.Label,
			&i.Step,
			&i.JobId,
			&i.SourceKey,
			&i.QueueTaskId,
			&i.RefId,
			&i.Error,
			&i.Meta,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.HeartbeatAt,
			&i.TimeoutMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActivityRunTimeout = `-- name: SetActivityRunTimeout :exec
UPDATE "ActivityRun" SET "timeoutMs" = $2 WHERE "id" = $1
`

type SetActivityRunTimeoutParams struct {
	ID        pgtype.UUID `json:"id"`
	TimeoutMs *int32      `json:"timeoutMs"`
}

// Records the deadline (from the task-type policy) the run was admitted
// under, so the sweeper and UI can report which limit applied. Set by the
// queue middleware, independent of the handler's own StartActivityRun call.
func (q *Queries) SetActivityRunTimeout(ctx context.Context, arg SetActivityRunTimeoutParams) error {
	_, err := q.db.Exec(ctx, setActivityRunTimeout, arg.ID, arg.TimeoutMs)
	return err
}

const setActivityStep = `-- name: SetActivityStep :exec
UPDATE "ActivityRun" SET "step" = $2, "meta" = COALESCE($3, "meta"), "heartbeatAt" = now() WHERE "id" = $1
`

type SetActivityStepParams struct {
	ID   pgtype.UUID `json:"id"`
	Step *string     `json:"step"`
	Meta []byte      `json:"meta"`
}

func (q *Queries) SetActivityStep(ctx context.Context, arg SetActivityStepParams) error {
	_, err := q.db.Exec(ctx, setActivityStep, arg.ID, arg.Step, arg.Meta)
	return err
}

const startActivityRun = `-- name: StartActivityRun :exec
UPDATE "ActivityRun" SET "state" = 'running', "startedAt" = now(), "heartbeatAt" = now() WHERE "id" = $1
`

func (q *Queries) StartActivityRun(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, startActivityRun, id)
	return err
}

const sweepStaleRunningActivityRuns = `-- name: SweepStaleRunningActivityRuns :many
UPDATE "ActivityRun"
SET "state" = 'interrupted', "error" = $1, "finishedAt" = now()
WHERE "state" = 'running' AND ("heartbeatAt" IS NULL OR "heartbeatAt" < $2)
RETURNING id, op, state, label, step, "jobId", "sourceKey", "queueTaskId", "refId", error, meta, "createdAt", "startedAt", "finishedAt", "heartbeatAt", "timeoutMs"
`

type SweepStaleRunningActivityRunsParams struct {
	Reason *string          `json:"reason"`
	Cutoff pgtype.Timestamp `json:"cutoff"`
}

// Stale: heartbeatAt older than sqlc.arg('cutoff'), or null (the existing-ghost
// case — pre-migration rows and any queued->running transition that predates
// this feature). Only ever moves 'running' rows, never a terminal one, so a
// run that finished between sweep read and write is never re-opened.
func (q *Queries) SweepStaleRunningActivityRuns(ctx context.Context, arg SweepStaleRunningActivityRunsParams) ([]ActivityRun, error) {
	rows, err := q.db.Query(ctx, sweepStaleRunningActivityRuns, arg.Reason, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityRun
	for rows.Next() {
		var i ActivityRun
		if err := rows.Scan(
			&i.ID,
			&i.Op,
			&i.State,
			&i.Label,
			&i.Step,
			&i.JobId,
			&i.SourceKey,
			&i.QueueTaskId,
			&i.RefId,
			&i.Error,
			&i.Meta,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.HeartbeatAt,
			&i.TimeoutMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchActivityRunHeartbeat = `-- name: TouchActivityRunHeartbeat :exec
UPDATE "ActivityRun" SET "heartbeatAt" = now() WHERE "id" = $1 AND "state" = 'running'
`

func (q *Queries) TouchActivityRunHeartbeat(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchActivityRunHeartbeat, id)
	return err
}
