// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aifeaturesetting.sql

package sqlcgen

import (
	"context"
)

const getAiFeatureSetting = `-- name: GetAiFeatureSetting :one
SELECT "featureKey", enabled, threshold, "updatedAt" FROM "AiFeatureSetting" WHERE "featureKey" = $1
`

func (q *Queries) GetAiFeatureSetting(ctx context.Context, featurekey string) (AiFeatureSetting, error) {
	row := q.db.QueryRow(ctx, getAiFeatureSetting, featurekey)
	var i AiFeatureSetting
	err := row.Scan(
		&i.FeatureKey,
		&i.Enabled,
		&i.Threshold,
		&i.UpdatedAt,
	)
	return i, err
}

const listAiFeatureSettings = `-- name: ListAiFeatureSettings :many
SELECT "featureKey", enabled, threshold, "updatedAt" FROM "AiFeatureSetting" ORDER BY "featureKey"
`

func (q *Queries) ListAiFeatureSettings(ctx context.Context) ([]AiFeatureSetting, error) {
	rows, err := q.db.Query(ctx, listAiFeatureSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiFeatureSetting
	for rows.Next() {
		var i AiFeatureSetting
		if err := rows.Scan(
			&i.FeatureKey,
			&i.Enabled,
			&i.Threshold,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAiFeatureSetting = `-- name: UpdateAiFeatureSetting :one
UPDATE "AiFeatureSetting"
SET "enabled" = $2, "threshold" = $3, "updatedAt" = now()
WHERE "featureKey" = $1
RETURNING "featureKey", enabled, threshold, "updatedAt"
`

type UpdateAiFeatureSettingParams struct {
	FeatureKey string `json:"featureKey"`
	Enabled    bool   `json:"enabled"`
	Threshold  int32  `json:"threshold"`
}

func (q *Queries) UpdateAiFeatureSetting(ctx context.Context, arg UpdateAiFeatureSettingParams) (AiFeatureSetting, error) {
	row := q.db.QueryRow(ctx, updateAiFeatureSetting, arg.FeatureKey, arg.Enabled, arg.Threshold)
	var i AiFeatureSetting
	err := row.Scan(
		&i.FeatureKey,
		&i.Enabled,
		&i.Threshold,
		&i.UpdatedAt,
	)
	return i, err
}
