// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applicationoutcome.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApplicationOutcomes = `-- name: CountApplicationOutcomes :one
SELECT count(*) FROM "ApplicationOutcome" WHERE "applicationId" = $1
`

func (q *Queries) CountApplicationOutcomes(ctx context.Context, applicationid pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationOutcomes, applicationid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertApplicationOutcome = `-- name: InsertApplicationOutcome :one
INSERT INTO "ApplicationOutcome" ("applicationId", "eventType", "occurredAt", "note")
VALUES ($1, $2, $3, $4)
ON CONFLICT ("applicationId", "eventType")
	WHERE "eventType" IN ('applied', 'offer', 'rejected')
	DO NOTHING
RETURNING id, "applicationId", "eventType", "occurredAt", "recordedAt", note, "createdAt"
`

type InsertApplicationOutcomeParams struct {
	ApplicationId pgtype.UUID      `json:"applicationId"`
	EventType     string           `json:"eventType"`
	OccurredAt    pgtype.Timestamp `json:"occurredAt"`
	Note          *string          `json:"note"`
}

// Append one outcome event. Idempotent for the terminal-once types
// ('applied', 'offer', 'rejected') via the partial unique index — a redundant
// transition inserts nothing and returns no row (pgx.ErrNoRows), which callers
// treat as "already recorded". 'viewed'/'screen' are outside the index
// predicate and always insert.
func (q *Queries) InsertApplicationOutcome(ctx context.Context, arg InsertApplicationOutcomeParams) (ApplicationOutcome, error) {
	row := q.db.QueryRow(ctx, insertApplicationOutcome,
		arg.ApplicationId,
		arg.EventType,
		arg.OccurredAt,
		arg.Note,
	)
	var i ApplicationOutcome
	err := row.Scan(
		&i.ID,
		&i.ApplicationId,
		&i.EventType,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listApplicationOutcomes = `-- name: ListApplicationOutcomes :many
SELECT id, "applicationId", "eventType", "occurredAt", "recordedAt", note, "createdAt" FROM "ApplicationOutcome"
WHERE "applicationId" = $1
ORDER BY "occurredAt" ASC, "recordedAt" ASC
`

// Timeline read: oldest first by real-world event time, "recordedAt" breaking
// ties so two events back-dated to the same instant still return in write order.
func (q *Queries) ListApplicationOutcomes(ctx context.Context, applicationid pgtype.UUID) ([]ApplicationOutcome, error) {
	rows, err := q.db.Query(ctx, listApplicationOutcomes, applicationid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationOutcome
	for rows.Next() {
		var i ApplicationOutcome
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationId,
			&i.EventType,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
