// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, "jobId", status, notes, "appliedAt", events, "updatedAt", "createdAt" FROM "Application" WHERE "id" = $1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id pgtype.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.JobId,
		&i.Status,
		&i.Notes,
		&i.AppliedAt,
		&i.Events,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApplicationByJobID = `-- name: GetApplicationByJobID :one
SELECT id, "jobId", status, notes, "appliedAt", events, "updatedAt", "createdAt" FROM "Application" WHERE "jobId" = $1
`

func (q *Queries) GetApplicationByJobID(ctx context.Context, jobid pgtype.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByJobID, jobid)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.JobId,
		&i.Status,
		&i.Notes,
		&i.AppliedAt,
		&i.Events,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT
  a.id, a."jobId", a.status, a.notes, a."appliedAt", a.events, a."updatedAt", a."createdAt",
  j."id" AS job_id_full, j."dedupeKey" AS job_dedupe_key, j."sourceKey" AS job_source_key,
  j."title" AS job_title, j."company" AS job_company, j."location" AS job_location,
  j."remote" AS job_remote, j."salaryRaw" AS job_salary_raw, j."url" AS job_url,
  j."description" AS job_description, j."postedAt" AS job_posted_at, j."ingestedAt" AS job_ingested_at,
  j."status" AS job_status,
  mr."id" AS mr_id, mr."similarity" AS mr_similarity, mr."score" AS mr_score,
  mr."matchedSkills" AS mr_matched_skills, mr."missingSkills" AS mr_missing_skills,
  mr."summary" AS mr_summary, mr."redFlags" AS mr_red_flags, mr."model" AS mr_model,
  mr."createdAt" AS mr_created_at
FROM "Application" a
JOIN "Job" j ON j."id" = a."jobId"
LEFT JOIN "MatchResult" mr ON mr."jobId" = j."id"
WHERE ($1::text IS NULL OR a."status" = $1)
ORDER BY a."updatedAt" DESC
`

type ListApplicationsRow struct {
	ID              pgtype.UUID      `json:"id"`
	JobId           pgtype.UUID      `json:"jobId"`
	Status          string           `json:"status"`
	Notes           *string          `json:"notes"`
	AppliedAt       pgtype.Timestamp `json:"appliedAt"`
	Events          []byte           `json:"events"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	JobIDFull       pgtype.UUID      `json:"job_id_full"`
	JobDedupeKey    string           `json:"job_dedupe_key"`
	JobSourceKey    string           `json:"job_source_key"`
	JobTitle        string           `json:"job_title"`
	JobCompany      string           `json:"job_company"`
	JobLocation     *string          `json:"job_location"`
	JobRemote       bool             `json:"job_remote"`
	JobSalaryRaw    *string          `json:"job_salary_raw"`
	JobUrl          string           `json:"job_url"`
	JobDescription  string           `json:"job_description"`
	JobPostedAt     pgtype.Timestamp `json:"job_posted_at"`
	JobIngestedAt   pgtype.Timestamp `json:"job_ingested_at"`
	JobStatus       string           `json:"job_status"`
	MrID            pgtype.UUID      `json:"mr_id"`
	MrSimilarity    *float64         `json:"mr_similarity"`
	MrScore         *int32           `json:"mr_score"`
	MrMatchedSkills []byte           `json:"mr_matched_skills"`
	MrMissingSkills []byte           `json:"mr_missing_skills"`
	MrSummary       *string          `json:"mr_summary"`
	MrRedFlags      []byte           `json:"mr_red_flags"`
	MrModel         *string          `json:"mr_model"`
	MrCreatedAt     pgtype.Timestamp `json:"mr_created_at"`
}

func (q *Queries) ListApplications(ctx context.Context, status *string) ([]ListApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listApplications, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsRow
	for rows.Next() {
		var i ListApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobId,
			&i.Status,
			&i.Notes,
			&i.AppliedAt,
			&i.Events,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.JobIDFull,
			&i.JobDedupeKey,
			&i.JobSourceKey,
			&i.JobTitle,
			&i.JobCompany,
			&i.JobLocation,
			&i.JobRemote,
			&i.JobSalaryRaw,
			&i.JobUrl,
			&i.JobDescription,
			&i.JobPostedAt,
			&i.JobIngestedAt,
			&i.JobStatus,
			&i.MrID,
			&i.MrSimilarity,
			&i.MrScore,
			&i.MrMatchedSkills,
			&i.MrMissingSkills,
			&i.MrSummary,
			&i.MrRedFlags,
			&i.MrModel,
			&i.MrCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsHighFit = `-- name: StatsHighFit :one
SELECT count(*) FROM "MatchResult" WHERE "score" >= 70
`

func (q *Queries) StatsHighFit(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, statsHighFit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const statsJobsLast24h = `-- name: StatsJobsLast24h :one
SELECT count(*) FROM "Job" WHERE "ingestedAt" >= $1
`

func (q *Queries) StatsJobsLast24h(ctx context.Context, ingestedat pgtype.Timestamp) (int64, error) {
	row := q.db.QueryRow(ctx, statsJobsLast24h, ingestedat)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const statsJobsTotal = `-- name: StatsJobsTotal :one
SELECT count(*) FROM "Job" WHERE "status" != 'hidden'
`

func (q *Queries) StatsJobsTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, statsJobsTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const statsPipeline = `-- name: StatsPipeline :many
SELECT "status", count(*) AS count FROM "Application" GROUP BY "status" ORDER BY "status" ASC
`

type StatsPipelineRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) StatsPipeline(ctx context.Context) ([]StatsPipelineRow, error) {
	rows, err := q.db.Query(ctx, statsPipeline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsPipelineRow
	for rows.Next() {
		var i StatsPipelineRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE "Application" SET
  "status" = COALESCE($1, "status"),
  "notes" = CASE WHEN $2::bool THEN $3 ELSE "notes" END,
  "events" = COALESCE($4, "events"),
  "appliedAt" = COALESCE($5, "appliedAt"),
  "updatedAt" = now()
WHERE "id" = $6
RETURNING id, "jobId", status, notes, "appliedAt", events, "updatedAt", "createdAt"
`

type UpdateApplicationParams struct {
	Status    *string          `json:"status"`
	NotesSet  *bool            `json:"notes_set"`
	Notes     *string          `json:"notes"`
	Events    []byte           `json:"events"`
	AppliedAt pgtype.Timestamp `json:"applied_at"`
	ID        pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.Status,
		arg.NotesSet,
		arg.Notes,
		arg.Events,
		arg.AppliedAt,
		arg.ID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.JobId,
		&i.Status,
		&i.Notes,
		&i.AppliedAt,
		&i.Events,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertApplicationStatus = `-- name: UpsertApplicationStatus :exec
INSERT INTO "Application" ("jobId", "status", "events")
VALUES ($1, $2, $3)
ON CONFLICT ("jobId") DO UPDATE SET "status" = EXCLUDED."status", "events" = EXCLUDED."events"
`

type UpsertApplicationStatusParams struct {
	JobId  pgtype.UUID `json:"jobId"`
	Status string      `json:"status"`
	Events []byte      `json:"events"`
}

func (q *Queries) UpsertApplicationStatus(ctx context.Context, arg UpsertApplicationStatusParams) error {
	_, err := q.db.Exec(ctx, upsertApplicationStatus, arg.JobId, arg.Status, arg.Events)
	return err
}
