// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: autogensetting.sql

package sqlcgen

import (
	"context"
)

const getAutoGenerateSetting = `-- name: GetAutoGenerateSetting :one
SELECT id, enabled, threshold, "updatedAt" FROM "AutoGenerateSetting" WHERE "id" = 'default'
`

func (q *Queries) GetAutoGenerateSetting(ctx context.Context) (AutoGenerateSetting, error) {
	row := q.db.QueryRow(ctx, getAutoGenerateSetting)
	var i AutoGenerateSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Threshold,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAutoGenerateSetting = `-- name: UpdateAutoGenerateSetting :one
UPDATE "AutoGenerateSetting"
SET "enabled" = $1, "threshold" = $2, "updatedAt" = now()
WHERE "id" = 'default'
RETURNING id, enabled, threshold, "updatedAt"
`

type UpdateAutoGenerateSettingParams struct {
	Enabled   bool  `json:"enabled"`
	Threshold int32 `json:"threshold"`
}

func (q *Queries) UpdateAutoGenerateSetting(ctx context.Context, arg UpdateAutoGenerateSettingParams) (AutoGenerateSetting, error) {
	row := q.db.QueryRow(ctx, updateAutoGenerateSetting, arg.Enabled, arg.Threshold)
	var i AutoGenerateSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Threshold,
		&i.UpdatedAt,
	)
	return i, err
}
