// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompanyByNormalizedName = `-- name: GetCompanyByNormalizedName :one
SELECT id, name, "normalizedName", website, "firstSeenAt", "lastRefreshedAt" FROM "Company" WHERE "normalizedName" = $1
`

func (q *Queries) GetCompanyByNormalizedName(ctx context.Context, normalizedname string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByNormalizedName, normalizedname)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Website,
		&i.FirstSeenAt,
		&i.LastRefreshedAt,
	)
	return i, err
}

const updateCompanyLastRefreshed = `-- name: UpdateCompanyLastRefreshed :exec
UPDATE "Company" SET "lastRefreshedAt" = now() WHERE id = $1
`

func (q *Queries) UpdateCompanyLastRefreshed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateCompanyLastRefreshed, id)
	return err
}

const upsertCompany = `-- name: UpsertCompany :one
INSERT INTO "Company" (name, "normalizedName", website, "firstSeenAt", "lastRefreshedAt")
VALUES ($1, $2, $3, now(), $4)
ON CONFLICT ("normalizedName") DO UPDATE SET
  name = EXCLUDED.name,
  website = COALESCE(EXCLUDED.website, "Company".website),
  "lastRefreshedAt" = COALESCE(EXCLUDED."lastRefreshedAt", "Company"."lastRefreshedAt")
RETURNING id, name, "normalizedName", website, "firstSeenAt", "lastRefreshedAt"
`

type UpsertCompanyParams struct {
	Name            string           `json:"name"`
	NormalizedName  string           `json:"normalizedName"`
	Website         *string          `json:"website"`
	LastRefreshedAt pgtype.Timestamp `json:"lastRefreshedAt"`
}

func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, upsertCompany,
		arg.Name,
		arg.NormalizedName,
		arg.Website,
		arg.LastRefreshedAt,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Website,
		&i.FirstSeenAt,
		&i.LastRefreshedAt,
	)
	return i, err
}
