// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companysignal.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCompanySignals = `-- name: DeleteCompanySignals :execrows
DELETE FROM "CompanySignal" WHERE "companyId" = $1
`

func (q *Queries) DeleteCompanySignals(ctx context.Context, companyid pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompanySignals, companyid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompanySignalByKind = `-- name: GetCompanySignalByKind :one
SELECT id, "companyId", kind, value, source, "fetchedAt", raw FROM "CompanySignal" WHERE "companyId" = $1 AND kind = $2
`

type GetCompanySignalByKindParams struct {
	CompanyId pgtype.UUID `json:"companyId"`
	Kind      string      `json:"kind"`
}

func (q *Queries) GetCompanySignalByKind(ctx context.Context, arg GetCompanySignalByKindParams) (CompanySignal, error) {
	row := q.db.QueryRow(ctx, getCompanySignalByKind, arg.CompanyId, arg.Kind)
	var i CompanySignal
	err := row.Scan(
		&i.ID,
		&i.CompanyId,
		&i.Kind,
		&i.Value,
		&i.Source,
		&i.FetchedAt,
		&i.Raw,
	)
	return i, err
}

const getCompanySignals = `-- name: GetCompanySignals :many
SELECT id, "companyId", kind, value, source, "fetchedAt", raw FROM "CompanySignal" WHERE "companyId" = $1 ORDER BY kind
`

func (q *Queries) GetCompanySignals(ctx context.Context, companyid pgtype.UUID) ([]CompanySignal, error) {
	rows, err := q.db.Query(ctx, getCompanySignals, companyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanySignal
	for rows.Next() {
		var i CompanySignal
		if err := rows.Scan(
			&i.ID,
			&i.CompanyId,
			&i.Kind,
			&i.Value,
			&i.Source,
			&i.FetchedAt,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompanySignal = `-- name: UpsertCompanySignal :one
INSERT INTO "CompanySignal" ("companyId", kind, value, source, "fetchedAt", raw)
VALUES ($1, $2, $3, $4, now(), $5)
ON CONFLICT ("companyId", kind) DO UPDATE SET
  value = EXCLUDED.value,
  source = EXCLUDED.source,
  "fetchedAt" = now(),
  raw = EXCLUDED.raw
RETURNING id, "companyId", kind, value, source, "fetchedAt", raw
`

type UpsertCompanySignalParams struct {
	CompanyId pgtype.UUID `json:"companyId"`
	Kind      string      `json:"kind"`
	Value     []byte      `json:"value"`
	Source    *string     `json:"source"`
	Raw       []byte      `json:"raw"`
}

func (q *Queries) UpsertCompanySignal(ctx context.Context, arg UpsertCompanySignalParams) (CompanySignal, error) {
	row := q.db.QueryRow(ctx, upsertCompanySignal,
		arg.CompanyId,
		arg.Kind,
		arg.Value,
		arg.Source,
		arg.Raw,
	)
	var i CompanySignal
	err := row.Scan(
		&i.ID,
		&i.CompanyId,
		&i.Kind,
		&i.Value,
		&i.Source,
		&i.FetchedAt,
		&i.Raw,
	)
	return i, err
}
