// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllConnections = `-- name: DeleteAllConnections :execrows
DELETE FROM "ContactConnection"
`

func (q *Queries) DeleteAllConnections(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllConnections)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAllContacts = `-- name: DeleteAllContacts :execrows
DELETE FROM "Contact"
`

func (q *Queries) DeleteAllContacts(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllContacts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findContactsAtCompany = `-- name: FindContactsAtCompany :many
SELECT id, name, email, company, role, "linkedinUrl", "githubUsername", source, "createdAt" FROM "Contact" WHERE "company" ILIKE '%' || $1 || '%' ORDER BY "name"
`

func (q *Queries) FindContactsAtCompany(ctx context.Context, dollar_1 *string) ([]Contact, error) {
	rows, err := q.db.Query(ctx, findContactsAtCompany, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Company,
			&i.Role,
			&i.LinkedinUrl,
			&i.GithubUsername,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findContactsByGithubUsername = `-- name: FindContactsByGithubUsername :many
SELECT id, name, email, company, role, "linkedinUrl", "githubUsername", source, "createdAt" FROM "Contact" WHERE "githubUsername" = $1
`

func (q *Queries) FindContactsByGithubUsername(ctx context.Context, githubusername *string) ([]Contact, error) {
	rows, err := q.db.Query(ctx, findContactsByGithubUsername, githubusername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Company,
			&i.Role,
			&i.LinkedinUrl,
			&i.GithubUsername,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConnectionsFrom = `-- name: GetConnectionsFrom :many
SELECT id, "fromContactId", "toContactId", "relationshipType", strength, "createdAt" FROM "ContactConnection" WHERE "fromContactId" = $1
`

func (q *Queries) GetConnectionsFrom(ctx context.Context, fromcontactid pgtype.UUID) ([]ContactConnection, error) {
	rows, err := q.db.Query(ctx, getConnectionsFrom, fromcontactid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactConnection
	for rows.Next() {
		var i ContactConnection
		if err := rows.Scan(
			&i.ID,
			&i.FromContactId,
			&i.ToContactId,
			&i.RelationshipType,
			&i.Strength,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConnectionsTo = `-- name: GetConnectionsTo :many
SELECT id, "fromContactId", "toContactId", "relationshipType", strength, "createdAt" FROM "ContactConnection" WHERE "toContactId" = $1
`

func (q *Queries) GetConnectionsTo(ctx context.Context, tocontactid pgtype.UUID) ([]ContactConnection, error) {
	rows, err := q.db.Query(ctx, getConnectionsTo, tocontactid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactConnection
	for rows.Next() {
		var i ContactConnection
		if err := rows.Scan(
			&i.ID,
			&i.FromContactId,
			&i.ToContactId,
			&i.RelationshipType,
			&i.Strength,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactByID = `-- name: GetContactByID :one
SELECT id, name, email, company, role, "linkedinUrl", "githubUsername", source, "createdAt" FROM "Contact" WHERE "id" = $1
`

func (q *Queries) GetContactByID(ctx context.Context, id pgtype.UUID) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByID, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Company,
		&i.Role,
		&i.LinkedinUrl,
		&i.GithubUsername,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const insertContact = `-- name: InsertContact :one
INSERT INTO "Contact" ("name", "email", "company", "role", "linkedinUrl", "githubUsername", "source")
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, email, company, role, "linkedinUrl", "githubUsername", source, "createdAt"
`

type InsertContactParams struct {
	Name           string  `json:"name"`
	Email          *string `json:"email"`
	Company        *string `json:"company"`
	Role           *string `json:"role"`
	LinkedinUrl    *string `json:"linkedinUrl"`
	GithubUsername *string `json:"githubUsername"`
	Source         string  `json:"source"`
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, insertContact,
		arg.Name,
		arg.Email,
		arg.Company,
		arg.Role,
		arg.LinkedinUrl,
		arg.GithubUsername,
		arg.Source,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Company,
		&i.Role,
		&i.LinkedinUrl,
		&i.GithubUsername,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const insertContactConnection = `-- name: InsertContactConnection :one
INSERT INTO "ContactConnection" ("fromContactId", "toContactId", "relationshipType", "strength")
VALUES ($1, $2, $3, $4)
ON CONFLICT ("fromContactId", "toContactId") DO UPDATE
SET "relationshipType" = EXCLUDED."relationshipType",
    "strength" = EXCLUDED."strength"
RETURNING id, "fromContactId", "toContactId", "relationshipType", strength, "createdAt"
`

type InsertContactConnectionParams struct {
	FromContactId    pgtype.UUID `json:"fromContactId"`
	ToContactId      pgtype.UUID `json:"toContactId"`
	RelationshipType string      `json:"relationshipType"`
	Strength         float32     `json:"strength"`
}

func (q *Queries) InsertContactConnection(ctx context.Context, arg InsertContactConnectionParams) (ContactConnection, error) {
	row := q.db.QueryRow(ctx, insertContactConnection,
		arg.FromContactId,
		arg.ToContactId,
		arg.RelationshipType,
		arg.Strength,
	)
	var i ContactConnection
	err := row.Scan(
		&i.ID,
		&i.FromContactId,
		&i.ToContactId,
		&i.RelationshipType,
		&i.Strength,
		&i.CreatedAt,
	)
	return i, err
}

const listConnections = `-- name: ListConnections :many
SELECT id, "fromContactId", "toContactId", "relationshipType", strength, "createdAt" FROM "ContactConnection" ORDER BY "createdAt" DESC
`

func (q *Queries) ListConnections(ctx context.Context) ([]ContactConnection, error) {
	rows, err := q.db.Query(ctx, listConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactConnection
	for rows.Next() {
		var i ContactConnection
		if err := rows.Scan(
			&i.ID,
			&i.FromContactId,
			&i.ToContactId,
			&i.RelationshipType,
			&i.Strength,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT id, name, email, company, role, "linkedinUrl", "githubUsername", source, "createdAt" FROM "Contact" ORDER BY "createdAt" DESC
`

func (q *Queries) ListContacts(ctx context.Context) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Company,
			&i.Role,
			&i.LinkedinUrl,
			&i.GithubUsername,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByCompany = `-- name: ListContactsByCompany :many
SELECT id, name, email, company, role, "linkedinUrl", "githubUsername", source, "createdAt" FROM "Contact" WHERE "company" = $1 ORDER BY "name"
`

func (q *Queries) ListContactsByCompany(ctx context.Context, company *string) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContactsByCompany, company)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Company,
			&i.Role,
			&i.LinkedinUrl,
			&i.GithubUsername,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
