// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForCreateProposals implements pgx.CopyFromSource.
type iteratorForCreateProposals struct {
	rows                 []CreateProposalsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateProposals) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateProposals) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].DraftID,
		r.rows[0].FieldType,
		r.rows[0].FieldKey,
		r.rows[0].BeforeValue,
		r.rows[0].AfterValue,
		r.rows[0].Traceability,
		r.rows[0].Status,
		r.rows[0].DroppedReason,
	}, nil
}

func (r iteratorForCreateProposals) Err() error {
	return nil
}

func (q *Queries) CreateProposals(ctx context.Context, arg []CreateProposalsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"edit_proposals"}, []string{"draft_id", "field_type", "field_key", "before_value", "after_value", "traceability", "status", "dropped_reason"}, &iteratorForCreateProposals{rows: arg})
}
