// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, "jobId", type, version, content, "pdfPath", model, "createdAt", company, title, vacancy FROM "GeneratedDocument" WHERE "id" = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id pgtype.UUID) (GeneratedDocument, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i GeneratedDocument
	err := row.Scan(
		&i.ID,
		&i.JobId,
		&i.Type,
		&i.Version,
		&i.Content,
		&i.PdfPath,
		&i.Model,
		&i.CreatedAt,
		&i.Company,
		&i.Title,
		&i.Vacancy,
	)
	return i, err
}

const insertGeneratedDocument = `-- name: InsertGeneratedDocument :one
INSERT INTO "GeneratedDocument" ("jobId", "type", "version", "content", "pdfPath", "model", "company", "title", "vacancy")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, "jobId", type, version, content, "pdfPath", model, "createdAt", company, title, vacancy
`

type InsertGeneratedDocumentParams struct {
	JobId   pgtype.UUID `json:"jobId"`
	Type    string      `json:"type"`
	Version int32       `json:"version"`
	Content []byte      `json:"content"`
	PdfPath *string     `json:"pdfPath"`
	Model   string      `json:"model"`
	Company *string     `json:"company"`
	Title   *string     `json:"title"`
	Vacancy *string     `json:"vacancy"`
}

func (q *Queries) InsertGeneratedDocument(ctx context.Context, arg InsertGeneratedDocumentParams) (GeneratedDocument, error) {
	row := q.db.QueryRow(ctx, insertGeneratedDocument,
		arg.JobId,
		arg.Type,
		arg.Version,
		arg.Content,
		arg.PdfPath,
		arg.Model,
		arg.Company,
		arg.Title,
		arg.Vacancy,
	)
	var i GeneratedDocument
	err := row.Scan(
		&i.ID,
		&i.JobId,
		&i.Type,
		&i.Version,
		&i.Content,
		&i.PdfPath,
		&i.Model,
		&i.CreatedAt,
		&i.Company,
		&i.Title,
		&i.Vacancy,
	)
	return i, err
}

const listAdHocDocuments = `-- name: ListAdHocDocuments :many
SELECT id, "jobId", type, version, content, "pdfPath", model, "createdAt", company, title, vacancy FROM "GeneratedDocument"
WHERE "jobId" IS NULL
ORDER BY "createdAt" DESC
`

func (q *Queries) ListAdHocDocuments(ctx context.Context) ([]GeneratedDocument, error) {
	rows, err := q.db.Query(ctx, listAdHocDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneratedDocument
	for rows.Next() {
		var i GeneratedDocument
		if err := rows.Scan(
			&i.ID,
			&i.JobId,
			&i.Type,
			&i.Version,
			&i.Content,
			&i.PdfPath,
			&i.Model,
			&i.CreatedAt,
			&i.Company,
			&i.Title,
			&i.Vacancy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsForJob = `-- name: ListDocumentsForJob :many
SELECT id, "jobId", type, version, content, "pdfPath", model, "createdAt", company, title, vacancy FROM "GeneratedDocument"
WHERE "jobId" = $1
ORDER BY "type" ASC, "version" DESC
`

func (q *Queries) ListDocumentsForJob(ctx context.Context, jobid pgtype.UUID) ([]GeneratedDocument, error) {
	rows, err := q.db.Query(ctx, listDocumentsForJob, jobid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneratedDocument
	for rows.Next() {
		var i GeneratedDocument
		if err := rows.Scan(
			&i.ID,
			&i.JobId,
			&i.Type,
			&i.Version,
			&i.Content,
			&i.PdfPath,
			&i.Model,
			&i.CreatedAt,
			&i.Company,
			&i.Title,
			&i.Vacancy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxDocumentVersion = `-- name: MaxDocumentVersion :one
SELECT COALESCE(MAX("version"), 0)::int AS max_version
FROM "GeneratedDocument"
WHERE "jobId" = $1 AND "type" = $2
`

type MaxDocumentVersionParams struct {
	JobId pgtype.UUID `json:"jobId"`
	Type  string      `json:"type"`
}

func (q *Queries) MaxDocumentVersion(ctx context.Context, arg MaxDocumentVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, maxDocumentVersion, arg.JobId, arg.Type)
	var max_version int32
	err := row.Scan(&max_version)
	return max_version, err
}

const updateDocumentContent = `-- name: UpdateDocumentContent :one
UPDATE "GeneratedDocument" SET "content" = $2, "pdfPath" = $3
WHERE "id" = $1
RETURNING id, "jobId", type, version, content, "pdfPath", model, "createdAt", company, title, vacancy
`

type UpdateDocumentContentParams struct {
	ID      pgtype.UUID `json:"id"`
	Content []byte      `json:"content"`
	PdfPath *string     `json:"pdfPath"`
}

func (q *Queries) UpdateDocumentContent(ctx context.Context, arg UpdateDocumentContentParams) (GeneratedDocument, error) {
	row := q.db.QueryRow(ctx, updateDocumentContent, arg.ID, arg.Content, arg.PdfPath)
	var i GeneratedDocument
	err := row.Scan(
		&i.ID,
		&i.JobId,
		&i.Type,
		&i.Version,
		&i.Content,
		&i.PdfPath,
		&i.Model,
		&i.CreatedAt,
		&i.Company,
		&i.Title,
		&i.Vacancy,
	)
	return i, err
}
