// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employerboard.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decideBoardCandidate = `-- name: DecideBoardCandidate :exec
UPDATE "BoardCandidate" SET "state" = $2, "decidedAt" = now() WHERE "id" = $1
`

type DecideBoardCandidateParams struct {
	ID    pgtype.UUID `json:"id"`
	State string      `json:"state"`
}

func (q *Queries) DecideBoardCandidate(ctx context.Context, arg DecideBoardCandidateParams) error {
	_, err := q.db.Exec(ctx, decideBoardCandidate, arg.ID, arg.State)
	return err
}

const deleteEmployerBoard = `-- name: DeleteEmployerBoard :exec
DELETE FROM "EmployerBoard" WHERE "id" = $1
`

func (q *Queries) DeleteEmployerBoard(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmployerBoard, id)
	return err
}

const getBoardCandidate = `-- name: GetBoardCandidate :one
SELECT id, vendor, "employerIdentifier", "inferredFromJobId", state, "createdAt", "decidedAt" FROM "BoardCandidate" WHERE "vendor" = $1 AND "employerIdentifier" = $2
`

type GetBoardCandidateParams struct {
	Vendor             string `json:"vendor"`
	EmployerIdentifier string `json:"employerIdentifier"`
}

func (q *Queries) GetBoardCandidate(ctx context.Context, arg GetBoardCandidateParams) (BoardCandidate, error) {
	row := q.db.QueryRow(ctx, getBoardCandidate, arg.Vendor, arg.EmployerIdentifier)
	var i BoardCandidate
	err := row.Scan(
		&i.ID,
		&i.Vendor,
		&i.EmployerIdentifier,
		&i.InferredFromJobId,
		&i.State,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getBoardCandidateByID = `-- name: GetBoardCandidateByID :one
SELECT id, vendor, "employerIdentifier", "inferredFromJobId", state, "createdAt", "decidedAt" FROM "BoardCandidate" WHERE "id" = $1
`

func (q *Queries) GetBoardCandidateByID(ctx context.Context, id pgtype.UUID) (BoardCandidate, error) {
	row := q.db.QueryRow(ctx, getBoardCandidateByID, id)
	var i BoardCandidate
	err := row.Scan(
		&i.ID,
		&i.Vendor,
		&i.EmployerIdentifier,
		&i.InferredFromJobId,
		&i.State,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getEmployerBoard = `-- name: GetEmployerBoard :one
SELECT id, vendor, "employerIdentifier", "displayName", "addedVia", enabled, "lastSuccessAt", "lastPostingCount", "consecutiveEmptyRuns", "createdAt" FROM "EmployerBoard" WHERE "vendor" = $1 AND "employerIdentifier" = $2
`

type GetEmployerBoardParams struct {
	Vendor             string `json:"vendor"`
	EmployerIdentifier string `json:"employerIdentifier"`
}

func (q *Queries) GetEmployerBoard(ctx context.Context, arg GetEmployerBoardParams) (EmployerBoard, error) {
	row := q.db.QueryRow(ctx, getEmployerBoard, arg.Vendor, arg.EmployerIdentifier)
	var i EmployerBoard
	err := row.Scan(
		&i.ID,
		&i.Vendor,
		&i.EmployerIdentifier,
		&i.DisplayName,
		&i.AddedVia,
		&i.Enabled,
		&i.LastSuccessAt,
		&i.LastPostingCount,
		&i.ConsecutiveEmptyRuns,
		&i.CreatedAt,
	)
	return i, err
}

const insertBoardCandidate = `-- name: InsertBoardCandidate :one
INSERT INTO "BoardCandidate" ("vendor", "employerIdentifier", "inferredFromJobId")
VALUES ($1, $2, $3)
ON CONFLICT ("vendor", "employerIdentifier") DO NOTHING
RETURNING id, vendor, "employerIdentifier", "inferredFromJobId", state, "createdAt", "decidedAt"
`

type InsertBoardCandidateParams struct {
	Vendor             string      `json:"vendor"`
	EmployerIdentifier string      `json:"employerIdentifier"`
	InferredFromJobId  pgtype.UUID `json:"inferredFromJobId"`
}

func (q *Queries) InsertBoardCandidate(ctx context.Context, arg InsertBoardCandidateParams) (BoardCandidate, error) {
	row := q.db.QueryRow(ctx, insertBoardCandidate, arg.Vendor, arg.EmployerIdentifier, arg.InferredFromJobId)
	var i BoardCandidate
	err := row.Scan(
		&i.ID,
		&i.Vendor,
		&i.EmployerIdentifier,
		&i.InferredFromJobId,
		&i.State,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const insertEmployerBoard = `-- name: InsertEmployerBoard :one
INSERT INTO "EmployerBoard" ("vendor", "employerIdentifier", "displayName", "addedVia")
VALUES ($1, $2, $3, $4)
ON CONFLICT ("vendor", "employerIdentifier") DO UPDATE SET "enabled" = true
RETURNING id, vendor, "employerIdentifier", "displayName", "addedVia", enabled, "lastSuccessAt", "lastPostingCount", "consecutiveEmptyRuns", "createdAt"
`

type InsertEmployerBoardParams struct {
	Vendor             string `json:"vendor"`
	EmployerIdentifier string `json:"employerIdentifier"`
	DisplayName        string `json:"displayName"`
	AddedVia           string `json:"addedVia"`
}

func (q *Queries) InsertEmployerBoard(ctx context.Context, arg InsertEmployerBoardParams) (EmployerBoard, error) {
	row := q.db.QueryRow(ctx, insertEmployerBoard,
		arg.Vendor,
		arg.EmployerIdentifier,
		arg.DisplayName,
		arg.AddedVia,
	)
	var i EmployerBoard
	err := row.Scan(
		&i.ID,
		&i.Vendor,
		&i.EmployerIdentifier,
		&i.DisplayName,
		&i.AddedVia,
		&i.Enabled,
		&i.LastSuccessAt,
		&i.LastPostingCount,
		&i.ConsecutiveEmptyRuns,
		&i.CreatedAt,
	)
	return i, err
}

const listApplyURLsForDiscovery = `-- name: ListApplyURLsForDiscovery :many
SELECT DISTINCT "url" FROM "Job" ORDER BY "ingestedAt" DESC LIMIT $1
`

// Every distinct job URL, newest first, scanned by candidate discovery for
// supported-vendor links (research.md §3). Bounded so discovery over a large
// Job table stays cheap; re-running periodically still catches older links
// eventually via the LIMIT window sliding as new jobs are ingested above it.
func (q *Queries) ListApplyURLsForDiscovery(ctx context.Context, limit int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listApplyURLsForDiscovery, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardCandidates = `-- name: ListBoardCandidates :many
SELECT id, vendor, "employerIdentifier", "inferredFromJobId", state, "createdAt", "decidedAt" FROM "BoardCandidate" WHERE "state" = 'proposed' ORDER BY "createdAt" DESC
`

func (q *Queries) ListBoardCandidates(ctx context.Context) ([]BoardCandidate, error) {
	rows, err := q.db.Query(ctx, listBoardCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardCandidate
	for rows.Next() {
		var i BoardCandidate
		if err := rows.Scan(
			&i.ID,
			&i.Vendor,
			&i.EmployerIdentifier,
			&i.InferredFromJobId,
			&i.State,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployerBoards = `-- name: ListEmployerBoards :many
SELECT id, vendor, "employerIdentifier", "displayName", "addedVia", enabled, "lastSuccessAt", "lastPostingCount", "consecutiveEmptyRuns", "createdAt" FROM "EmployerBoard" ORDER BY "vendor", "displayName"
`

func (q *Queries) ListEmployerBoards(ctx context.Context) ([]EmployerBoard, error) {
	rows, err := q.db.Query(ctx, listEmployerBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmployerBoard
	for rows.Next() {
		var i EmployerBoard
		if err := rows.Scan(
			&i.ID,
			&i.Vendor,
			&i.EmployerIdentifier,
			&i.DisplayName,
			&i.AddedVia,
			&i.Enabled,
			&i.LastSuccessAt,
			&i.LastPostingCount,
			&i.ConsecutiveEmptyRuns,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployerBoardsByVendor = `-- name: ListEmployerBoardsByVendor :many
SELECT id, vendor, "employerIdentifier", "displayName", "addedVia", enabled, "lastSuccessAt", "lastPostingCount", "consecutiveEmptyRuns", "createdAt" FROM "EmployerBoard" WHERE "vendor" = $1 AND "enabled" = true ORDER BY "displayName"
`

func (q *Queries) ListEmployerBoardsByVendor(ctx context.Context, vendor string) ([]EmployerBoard, error) {
	rows, err := q.db.Query(ctx, listEmployerBoardsByVendor, vendor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmployerBoard
	for rows.Next() {
		var i EmployerBoard
		if err := rows.Scan(
			&i.ID,
			&i.Vendor,
			&i.EmployerIdentifier,
			&i.DisplayName,
			&i.AddedVia,
			&i.Enabled,
			&i.LastSuccessAt,
			&i.LastPostingCount,
			&i.ConsecutiveEmptyRuns,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordEmployerBoardRunOutcome = `-- name: RecordEmployerBoardRunOutcome :exec
UPDATE "EmployerBoard" SET
  "lastSuccessAt" = now(),
  "lastPostingCount" = $2,
  "consecutiveEmptyRuns" = CASE WHEN $2::int > 0 THEN 0 ELSE "consecutiveEmptyRuns" + 1 END
WHERE "id" = $1
`

type RecordEmployerBoardRunOutcomeParams struct {
	ID               pgtype.UUID `json:"id"`
	LastPostingCount int32       `json:"lastPostingCount"`
}

// postingCount > 0 resets the stale counter; 0 increments it (FR-014).
func (q *Queries) RecordEmployerBoardRunOutcome(ctx context.Context, arg RecordEmployerBoardRunOutcomeParams) error {
	_, err := q.db.Exec(ctx, recordEmployerBoardRunOutcome, arg.ID, arg.LastPostingCount)
	return err
}
