// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extauth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeBootstrapCode = `-- name: ConsumeBootstrapCode :one
UPDATE "ExtBootstrapCode"
SET "usedAt" = now()
WHERE "codeHash" = $1 AND "usedAt" IS NULL AND "expiresAt" > now()
RETURNING id, "codeHash", "createdAt", "expiresAt", "usedAt"
`

func (q *Queries) ConsumeBootstrapCode(ctx context.Context, codehash string) (ExtBootstrapCode, error) {
	row := q.db.QueryRow(ctx, consumeBootstrapCode, codehash)
	var i ExtBootstrapCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteExpiredBootstrapCodes = `-- name: DeleteExpiredBootstrapCodes :execrows
DELETE FROM "ExtBootstrapCode" WHERE "expiresAt" < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredBootstrapCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredBootstrapCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveRefreshToken = `-- name: GetActiveRefreshToken :one
SELECT id, "tokenHash", "createdAt", "expiresAt", "revokedAt", "rotatedToId" FROM "ExtRefreshToken"
WHERE "tokenHash" = $1 AND "revokedAt" IS NULL AND "expiresAt" > now()
`

func (q *Queries) GetActiveRefreshToken(ctx context.Context, tokenhash string) (ExtRefreshToken, error) {
	row := q.db.QueryRow(ctx, getActiveRefreshToken, tokenhash)
	var i ExtRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RotatedToId,
	)
	return i, err
}

const insertBootstrapCode = `-- name: InsertBootstrapCode :one
INSERT INTO "ExtBootstrapCode" ("codeHash", "expiresAt")
VALUES ($1, $2)
RETURNING id, "codeHash", "createdAt", "expiresAt", "usedAt"
`

type InsertBootstrapCodeParams struct {
	CodeHash  string           `json:"codeHash"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) InsertBootstrapCode(ctx context.Context, arg InsertBootstrapCodeParams) (ExtBootstrapCode, error) {
	row := q.db.QueryRow(ctx, insertBootstrapCode, arg.CodeHash, arg.ExpiresAt)
	var i ExtBootstrapCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO "ExtRefreshToken" ("tokenHash", "expiresAt")
VALUES ($1, $2)
RETURNING id, "tokenHash", "createdAt", "expiresAt", "revokedAt", "rotatedToId"
`

type InsertRefreshTokenParams struct {
	TokenHash string           `json:"tokenHash"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (ExtRefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken, arg.TokenHash, arg.ExpiresAt)
	var i ExtRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RotatedToId,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE "ExtRefreshToken"
SET "revokedAt" = now(), "rotatedToId" = $2
WHERE "id" = $1
`

type RevokeRefreshTokenParams struct {
	ID          pgtype.UUID `json:"id"`
	RotatedToId pgtype.UUID `json:"rotatedToId"`
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.ID, arg.RotatedToId)
	return err
}
