// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: freshmatchnotification.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentNotificationsByProfile = `-- name: CountRecentNotificationsByProfile :one
SELECT COUNT(*) FROM "FreshMatchNotification"
WHERE "profileId" = $1 AND "createdAt" > now() - make_interval(hours => $2::int)
`

type CountRecentNotificationsByProfileParams struct {
	ProfileId pgtype.UUID `json:"profileId"`
	Column2   int32       `json:"column_2"`
}

func (q *Queries) CountRecentNotificationsByProfile(ctx context.Context, arg CountRecentNotificationsByProfileParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentNotificationsByProfile, arg.ProfileId, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertFreshMatchNotification = `-- name: InsertFreshMatchNotification :one
INSERT INTO "FreshMatchNotification" (
    "jobId", "matchResultId", "profileId", "fresh"
) VALUES (
    $1, $2, $3, $4
) RETURNING id, "jobId", "matchResultId", "profileId", fresh, seen, "createdAt"
`

type InsertFreshMatchNotificationParams struct {
	JobId         pgtype.UUID `json:"jobId"`
	MatchResultId pgtype.UUID `json:"matchResultId"`
	ProfileId     pgtype.UUID `json:"profileId"`
	Fresh         bool        `json:"fresh"`
}

func (q *Queries) InsertFreshMatchNotification(ctx context.Context, arg InsertFreshMatchNotificationParams) (FreshMatchNotification, error) {
	row := q.db.QueryRow(ctx, insertFreshMatchNotification,
		arg.JobId,
		arg.MatchResultId,
		arg.ProfileId,
		arg.Fresh,
	)
	var i FreshMatchNotification
	err := row.Scan(
		&i.ID,
		&i.JobId,
		&i.MatchResultId,
		&i.ProfileId,
		&i.Fresh,
		&i.Seen,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentNotificationsByProfile = `-- name: ListRecentNotificationsByProfile :many
SELECT id, "jobId", "matchResultId", "profileId", fresh, seen, "createdAt" FROM "FreshMatchNotification"
WHERE "profileId" = $1
ORDER BY "createdAt" DESC
LIMIT $2
`

type ListRecentNotificationsByProfileParams struct {
	ProfileId pgtype.UUID `json:"profileId"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListRecentNotificationsByProfile(ctx context.Context, arg ListRecentNotificationsByProfileParams) ([]FreshMatchNotification, error) {
	rows, err := q.db.Query(ctx, listRecentNotificationsByProfile, arg.ProfileId, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FreshMatchNotification
	for rows.Next() {
		var i FreshMatchNotification
		if err := rows.Scan(
			&i.ID,
			&i.JobId,
			&i.MatchResultId,
			&i.ProfileId,
			&i.Fresh,
			&i.Seen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
