// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generationrun.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItems = `-- name: CreateItems :many
INSERT INTO generation_items (section_id, origin, source_index, source_text, edited_text, rank, position, selected)
SELECT $1::uuid, o, NULLIF(si, -1), st, NULLIF(et, ''), r, p, sel
FROM (
    SELECT
        unnest($2::text[]) AS o,
        unnest($3::int[]) AS si,
        unnest($4::text[]) AS st,
        unnest($5::text[]) AS et,
        unnest($6::int[]) AS r,
        unnest($7::int[]) AS p,
        unnest($8::bool[]) AS sel
) AS x
RETURNING id, section_id, origin, source_index, source_text, edited_text, rank, position, selected, unavailable, created_at, updated_at, dropped_entries
`

type CreateItemsParams struct {
	SectionID     pgtype.UUID `json:"section_id"`
	Origins       []string    `json:"origins"`
	SourceIndexes []int32     `json:"source_indexes"`
	SourceTexts   []string    `json:"source_texts"`
	EditedTexts   []string    `json:"edited_texts"`
	Ranks         []int32     `json:"ranks"`
	Positions     []int32     `json:"positions"`
	SelectedFlags []bool      `json:"selected_flags"`
}

// Batch insert for one section's items. Same zipped-unnest pattern as
// CreateSections. source_index is passed as -1 for origin='ai' rows (which
// have no source index) and normalized to NULL here; edited_text is passed
// as "" for rows with no edit and normalized to NULL here.
func (q *Queries) CreateItems(ctx context.Context, arg CreateItemsParams) ([]GenerationItem, error) {
	rows, err := q.db.Query(ctx, createItems,
		arg.SectionID,
		arg.Origins,
		arg.SourceIndexes,
		arg.SourceTexts,
		arg.EditedTexts,
		arg.Ranks,
		arg.Positions,
		arg.SelectedFlags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationItem
	for rows.Next() {
		var i GenerationItem
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Origin,
			&i.SourceIndex,
			&i.SourceText,
			&i.EditedText,
			&i.Rank,
			&i.Position,
			&i.Selected,
			&i.Unavailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DroppedEntries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRun = `-- name: CreateRun :one
INSERT INTO generation_runs (
    profile_id, job_id, vacancy_company, vacancy_title, vacancy_text,
    master_snapshot, master_content_hash, shape_config, grounding_level, summary_option_id
) VALUES (
    $1, $7, $8, $9, $2,
    $3, $4, $5, $6, $10
)
RETURNING id, profile_id, job_id, vacancy_company, vacancy_title, vacancy_text, master_snapshot, master_content_hash, shape_config, grounding_level, summary_option_id, analysis, state, activity_id, export_document_id, export_status, export_report, created_at, updated_at
`

type CreateRunParams struct {
	ProfileID         pgtype.UUID `json:"profile_id"`
	VacancyText       string      `json:"vacancy_text"`
	MasterSnapshot    []byte      `json:"master_snapshot"`
	MasterContentHash string      `json:"master_content_hash"`
	ShapeConfig       []byte      `json:"shape_config"`
	GroundingLevel    string      `json:"grounding_level"`
	JobID             pgtype.UUID `json:"job_id"`
	VacancyCompany    *string     `json:"vacancy_company"`
	VacancyTitle      *string     `json:"vacancy_title"`
	SummaryOptionID   *string     `json:"summary_option_id"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (GenerationRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ProfileID,
		arg.VacancyText,
		arg.MasterSnapshot,
		arg.MasterContentHash,
		arg.ShapeConfig,
		arg.GroundingLevel,
		arg.JobID,
		arg.VacancyCompany,
		arg.VacancyTitle,
		arg.SummaryOptionID,
	)
	var i GenerationRun
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.JobID,
		&i.VacancyCompany,
		&i.VacancyTitle,
		&i.VacancyText,
		&i.MasterSnapshot,
		&i.MasterContentHash,
		&i.ShapeConfig,
		&i.GroundingLevel,
		&i.SummaryOptionID,
		&i.Analysis,
		&i.State,
		&i.ActivityID,
		&i.ExportDocumentID,
		&i.ExportStatus,
		&i.ExportReport,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSections = `-- name: CreateSections :many
INSERT INTO generation_sections (run_id, kind, entry_key, entry_label, position, target_count)
SELECT $1::uuid, k, NULLIF(ek, ''), NULLIF(el, ''), p, tc
FROM (
    SELECT
        unnest($2::text[]) AS k,
        unnest($3::text[]) AS ek,
        unnest($4::text[]) AS el,
        unnest($5::int[]) AS p,
        unnest($6::int[]) AS tc
) AS x
RETURNING id, run_id, kind, entry_key, entry_label, position, target_count, state, error, fallback_used
`

type CreateSectionsParams struct {
	RunID        pgtype.UUID `json:"run_id"`
	Kinds        []string    `json:"kinds"`
	EntryKeys    []string    `json:"entry_keys"`
	EntryLabels  []string    `json:"entry_labels"`
	Positions    []int32     `json:"positions"`
	TargetCounts []int32     `json:"target_counts"`
}

// Batch insert for one run's sections (one summary, one per master
// experience entry, one skills). Arrays are position-aligned and zipped via
// parallel unnest() calls in a subquery select list rather than the
// multi-argument unnest(a, b, ...) table form, which sqlc's analyzer cannot
// resolve (same pattern as job.sql's BulkInsertJobs and tailoring.sql's
// CreateProposals); PostgreSQL evaluates them in lockstep either way.
// entry_key/entry_label are passed as "" for summary/skills sections and
// normalized to NULL here.
func (q *Queries) CreateSections(ctx context.Context, arg CreateSectionsParams) ([]GenerationSection, error) {
	rows, err := q.db.Query(ctx, createSections,
		arg.RunID,
		arg.Kinds,
		arg.EntryKeys,
		arg.EntryLabels,
		arg.Positions,
		arg.TargetCounts,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationSection
	for rows.Next() {
		var i GenerationSection
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.EntryKey,
			&i.EntryLabel,
			&i.Position,
			&i.TargetCount,
			&i.State,
			&i.Error,
			&i.FallbackUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRun = `-- name: DeleteRun :exec
DELETE FROM generation_runs WHERE id = $1
`

func (q *Queries) DeleteRun(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRun, id)
	return err
}

const deleteSectionItems = `-- name: DeleteSectionItems :exec
DELETE FROM generation_items WHERE section_id = $1
`

// Used by a section rerun (FR-021): the section's items are deleted and
// recreated, with the caller re-applying matched selections/edits/positions
// from the deleted rows before this call (data-model.md §4).
func (q *Queries) DeleteSectionItems(ctx context.Context, sectionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSectionItems, sectionID)
	return err
}

const getItemForUpdate = `-- name: GetItemForUpdate :one
SELECT id, section_id, origin, source_index, source_text, edited_text, rank, position, selected, unavailable, created_at, updated_at, dropped_entries FROM generation_items WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetItemForUpdate(ctx context.Context, id pgtype.UUID) (GenerationItem, error) {
	row := q.db.QueryRow(ctx, getItemForUpdate, id)
	var i GenerationItem
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Origin,
		&i.SourceIndex,
		&i.SourceText,
		&i.EditedText,
		&i.Rank,
		&i.Position,
		&i.Selected,
		&i.Unavailable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DroppedEntries,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, profile_id, job_id, vacancy_company, vacancy_title, vacancy_text, master_snapshot, master_content_hash, shape_config, grounding_level, summary_option_id, analysis, state, activity_id, export_document_id, export_status, export_report, created_at, updated_at FROM generation_runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (GenerationRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i GenerationRun
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.JobID,
		&i.VacancyCompany,
		&i.VacancyTitle,
		&i.VacancyText,
		&i.MasterSnapshot,
		&i.MasterContentHash,
		&i.ShapeConfig,
		&i.GroundingLevel,
		&i.SummaryOptionID,
		&i.Analysis,
		&i.State,
		&i.ActivityID,
		&i.ExportDocumentID,
		&i.ExportStatus,
		&i.ExportReport,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunForUpdate = `-- name: GetRunForUpdate :one
SELECT id, profile_id, job_id, vacancy_company, vacancy_title, vacancy_text, master_snapshot, master_content_hash, shape_config, grounding_level, summary_option_id, analysis, state, activity_id, export_document_id, export_status, export_report, created_at, updated_at FROM generation_runs WHERE id = $1 FOR UPDATE
`

// Row lock for every mutation on this run (item toggle/edit/reorder, rerun,
// export): these read the current state and write it back, so concurrent
// requests against the same run must serialize (rest-api.md's "every write
// takes a row-level SELECT ... FOR UPDATE on the run first").
func (q *Queries) GetRunForUpdate(ctx context.Context, id pgtype.UUID) (GenerationRun, error) {
	row := q.db.QueryRow(ctx, getRunForUpdate, id)
	var i GenerationRun
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.JobID,
		&i.VacancyCompany,
		&i.VacancyTitle,
		&i.VacancyText,
		&i.MasterSnapshot,
		&i.MasterContentHash,
		&i.ShapeConfig,
		&i.GroundingLevel,
		&i.SummaryOptionID,
		&i.Analysis,
		&i.State,
		&i.ActivityID,
		&i.ExportDocumentID,
		&i.ExportStatus,
		&i.ExportReport,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemsByRun = `-- name: ListItemsByRun :many
SELECT gi.id, gi.section_id, gi.origin, gi.source_index, gi.source_text, gi.edited_text, gi.rank, gi.position, gi.selected, gi.unavailable, gi.created_at, gi.updated_at, gi.dropped_entries FROM generation_items gi
JOIN generation_sections gs ON gs.id = gi.section_id
WHERE gs.run_id = $1
ORDER BY gs.position, gi.position
`

// Joins to the run through the section so the handler can build the whole
// workspace (GET /v1/generations/{runId}) with one query per table. Ordered
// by section position then item position, matching the "items are returned
// in position order" response rule (rest-api.md).
func (q *Queries) ListItemsByRun(ctx context.Context, runID pgtype.UUID) ([]GenerationItem, error) {
	rows, err := q.db.Query(ctx, listItemsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationItem
	for rows.Next() {
		var i GenerationItem
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Origin,
			&i.SourceIndex,
			&i.SourceText,
			&i.EditedText,
			&i.Rank,
			&i.Position,
			&i.Selected,
			&i.Unavailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DroppedEntries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByProfile = `-- name: ListRunsByProfile :many
SELECT id, profile_id, job_id, vacancy_company, vacancy_title, vacancy_text, master_snapshot, master_content_hash, shape_config, grounding_level, summary_option_id, analysis, state, activity_id, export_document_id, export_status, export_report, created_at, updated_at FROM generation_runs
WHERE profile_id = $1
  AND ($3::uuid IS NULL OR job_id = $3)
ORDER BY created_at DESC
LIMIT $2
`

type ListRunsByProfileParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	Limit     int32       `json:"limit"`
	JobID     pgtype.UUID `json:"job_id"`
}

// jobId is optional: NULL matches every run for the profile, matching the
// `GET /v1/generations?jobId=&limit=` contract (rest-api.md).
func (q *Queries) ListRunsByProfile(ctx context.Context, arg ListRunsByProfileParams) ([]GenerationRun, error) {
	rows, err := q.db.Query(ctx, listRunsByProfile, arg.ProfileID, arg.Limit, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationRun
	for rows.Next() {
		var i GenerationRun
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.JobID,
			&i.VacancyCompany,
			&i.VacancyTitle,
			&i.VacancyText,
			&i.MasterSnapshot,
			&i.MasterContentHash,
			&i.ShapeConfig,
			&i.GroundingLevel,
			&i.SummaryOptionID,
			&i.Analysis,
			&i.State,
			&i.ActivityID,
			&i.ExportDocumentID,
			&i.ExportStatus,
			&i.ExportReport,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByRun = `-- name: ListSectionsByRun :many
SELECT id, run_id, kind, entry_key, entry_label, position, target_count, state, error, fallback_used FROM generation_sections WHERE run_id = $1 ORDER BY position
`

func (q *Queries) ListSectionsByRun(ctx context.Context, runID pgtype.UUID) ([]GenerationSection, error) {
	rows, err := q.db.Query(ctx, listSectionsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationSection
	for rows.Next() {
		var i GenerationSection
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.EntryKey,
			&i.EntryLabel,
			&i.Position,
			&i.TargetCount,
			&i.State,
			&i.Error,
			&i.FallbackUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markItemsUnavailable = `-- name: MarkItemsUnavailable :exec
UPDATE generation_items SET unavailable = true, updated_at = now()
WHERE id = ANY($1::uuid[])
`

// FR-022: called when the master changed and these items' source_index no
// longer resolves against the current profile. Never deletes the row — an
// unavailable item is still shown, per data-model.md §4.
func (q *Queries) MarkItemsUnavailable(ctx context.Context, itemIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markItemsUnavailable, itemIds)
	return err
}

const reorderSectionItems = `-- name: ReorderSectionItems :exec
UPDATE generation_items AS gi SET
    position = x.p,
    updated_at = now()
FROM (
    SELECT
        unnest($2::uuid[]) AS id,
        unnest($3::int[]) AS p
) AS x
WHERE gi.id = x.id AND gi.section_id = $1::uuid
`

type ReorderSectionItemsParams struct {
	SectionID pgtype.UUID   `json:"section_id"`
	ItemIds   []pgtype.UUID `json:"item_ids"`
	Positions []int32       `json:"positions"`
}

// Whole-section reorder in one call (PATCH .../sections/{sectionId}/order).
// item_ids and positions are position-aligned arrays.
func (q *Queries) ReorderSectionItems(ctx context.Context, arg ReorderSectionItemsParams) error {
	_, err := q.db.Exec(ctx, reorderSectionItems, arg.SectionID, arg.ItemIds, arg.Positions)
	return err
}

const setRunAnalysis = `-- name: SetRunAnalysis :exec
UPDATE generation_runs SET analysis = $2, updated_at = now() WHERE id = $1
`

type SetRunAnalysisParams struct {
	ID       pgtype.UUID `json:"id"`
	Analysis []byte      `json:"analysis"`
}

// Persists the VacancyAnalysis once at run start so a per-section rerun
// (FR-021) does not re-analyse (data-model.md §1).
func (q *Queries) SetRunAnalysis(ctx context.Context, arg SetRunAnalysisParams) error {
	_, err := q.db.Exec(ctx, setRunAnalysis, arg.ID, arg.Analysis)
	return err
}

const setRunExport = `-- name: SetRunExport :exec
UPDATE generation_runs SET
    export_document_id = $3,
    export_status = $2,
    export_report = $4,
    updated_at = now()
WHERE id = $1
`

type SetRunExportParams struct {
	ID               pgtype.UUID `json:"id"`
	ExportStatus     *string     `json:"export_status"`
	ExportDocumentID pgtype.UUID `json:"export_document_id"`
	ExportReport     []byte      `json:"export_report"`
}

// Covers every export state transition: rendering (both NULL), exported
// (document_id set, report NULL) and blocked (document_id NULL, report set).
func (q *Queries) SetRunExport(ctx context.Context, arg SetRunExportParams) error {
	_, err := q.db.Exec(ctx, setRunExport,
		arg.ID,
		arg.ExportStatus,
		arg.ExportDocumentID,
		arg.ExportReport,
	)
	return err
}

const setRunState = `-- name: SetRunState :exec
UPDATE generation_runs SET state = $2, updated_at = now() WHERE id = $1
`

type SetRunStateParams struct {
	ID    pgtype.UUID `json:"id"`
	State string      `json:"state"`
}

func (q *Queries) SetRunState(ctx context.Context, arg SetRunStateParams) error {
	_, err := q.db.Exec(ctx, setRunState, arg.ID, arg.State)
	return err
}

const setSectionState = `-- name: SetSectionState :exec
UPDATE generation_sections SET
    state = $2,
    error = $4,
    fallback_used = $3
WHERE id = $1
`

type SetSectionStateParams struct {
	ID           pgtype.UUID `json:"id"`
	State        string      `json:"state"`
	FallbackUsed bool        `json:"fallback_used"`
	Error        *string     `json:"error"`
}

func (q *Queries) SetSectionState(ctx context.Context, arg SetSectionStateParams) error {
	_, err := q.db.Exec(ctx, setSectionState,
		arg.ID,
		arg.State,
		arg.FallbackUsed,
		arg.Error,
	)
	return err
}

const updateItemDroppedEntries = `-- name: UpdateItemDroppedEntries :exec
UPDATE generation_items SET
    dropped_entries = $2::text[],
    updated_at = now()
WHERE id = $1
`

type UpdateItemDroppedEntriesParams struct {
	ID             pgtype.UUID `json:"id"`
	DroppedEntries []string    `json:"dropped_entries"`
}

// The per-skill half of PATCH .../items/{itemId}: the entries of a skill
// group's `details` the user switched off, replaced wholesale so the write is
// idempotent and order-free. Only ever called for a profile-origin item in a
// skills section, checked by the handler.
func (q *Queries) UpdateItemDroppedEntries(ctx context.Context, arg UpdateItemDroppedEntriesParams) error {
	_, err := q.db.Exec(ctx, updateItemDroppedEntries, arg.ID, arg.DroppedEntries)
	return err
}

const updateItemSelection = `-- name: UpdateItemSelection :exec
UPDATE generation_items SET
    selected = COALESCE($2, selected),
    position = COALESCE($3, position),
    updated_at = now()
WHERE id = $1
`

type UpdateItemSelectionParams struct {
	ID       pgtype.UUID `json:"id"`
	Selected *bool       `json:"selected"`
	Position *int32      `json:"position"`
}

// Covers the toggle and reorder halves of PATCH .../items/{itemId}. Both
// fields are optional in the request ("any subset"), so each is left
// unchanged when its narg is NULL.
func (q *Queries) UpdateItemSelection(ctx context.Context, arg UpdateItemSelectionParams) error {
	_, err := q.db.Exec(ctx, updateItemSelection, arg.ID, arg.Selected, arg.Position)
	return err
}

const updateItemText = `-- name: UpdateItemText :exec
UPDATE generation_items SET edited_text = $2, updated_at = now() WHERE id = $1
`

type UpdateItemTextParams struct {
	ID         pgtype.UUID `json:"id"`
	EditedText *string     `json:"edited_text"`
}

// FR-009/FR-015 at the query boundary: this is only ever called for an
// origin='ai' item, enforced by the CHECK constraint and re-checked by the
// handler before calling it (403 for a profile-origin item).
func (q *Queries) UpdateItemText(ctx context.Context, arg UpdateItemTextParams) error {
	_, err := q.db.Exec(ctx, updateItemText, arg.ID, arg.EditedText)
	return err
}
