// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hostretrievalstate.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearHostCookies = `-- name: ClearHostCookies :exec
UPDATE host_retrieval_state SET cookies = NULL, updated_at = now() WHERE host = $1
`

func (q *Queries) ClearHostCookies(ctx context.Context, host string) error {
	_, err := q.db.Exec(ctx, clearHostCookies, host)
	return err
}

const clearHostRung = `-- name: ClearHostRung :exec
UPDATE host_retrieval_state SET current_rung = 'direct', rung_last_verified_at = NULL, updated_at = now() WHERE host = $1
`

func (q *Queries) ClearHostRung(ctx context.Context, host string) error {
	_, err := q.db.Exec(ctx, clearHostRung, host)
	return err
}

const getHostRetrievalState = `-- name: GetHostRetrievalState :one
SELECT id, host, identity_version, current_rung, rung_last_verified_at, cookies, consecutive_blocks, cooling_off_until, last_block_at, last_block_reason, crawl_delay_seconds, created_at, updated_at FROM host_retrieval_state WHERE host = $1
`

func (q *Queries) GetHostRetrievalState(ctx context.Context, host string) (HostRetrievalState, error) {
	row := q.db.QueryRow(ctx, getHostRetrievalState, host)
	var i HostRetrievalState
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.IdentityVersion,
		&i.CurrentRung,
		&i.RungLastVerifiedAt,
		&i.Cookies,
		&i.ConsecutiveBlocks,
		&i.CoolingOffUntil,
		&i.LastBlockAt,
		&i.LastBlockReason,
		&i.CrawlDelaySeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordHostBlock = `-- name: RecordHostBlock :exec
UPDATE host_retrieval_state SET
    consecutive_blocks = consecutive_blocks + 1,
    last_block_at = now(),
    last_block_reason = $2,
    updated_at = now()
WHERE host = $1
`

type RecordHostBlockParams struct {
	Host            string  `json:"host"`
	LastBlockReason *string `json:"last_block_reason"`
}

func (q *Queries) RecordHostBlock(ctx context.Context, arg RecordHostBlockParams) error {
	_, err := q.db.Exec(ctx, recordHostBlock, arg.Host, arg.LastBlockReason)
	return err
}

const recordHostSuccess = `-- name: RecordHostSuccess :exec
UPDATE host_retrieval_state SET
    current_rung = $2,
    consecutive_blocks = 0,
    rung_last_verified_at = now(),
    updated_at = now()
WHERE host = $1
`

type RecordHostSuccessParams struct {
	Host        string `json:"host"`
	CurrentRung string `json:"current_rung"`
}

func (q *Queries) RecordHostSuccess(ctx context.Context, arg RecordHostSuccessParams) error {
	_, err := q.db.Exec(ctx, recordHostSuccess, arg.Host, arg.CurrentRung)
	return err
}

const setHostCrawlDelay = `-- name: SetHostCrawlDelay :exec
UPDATE host_retrieval_state SET crawl_delay_seconds = $2, updated_at = now() WHERE host = $1
`

type SetHostCrawlDelayParams struct {
	Host              string `json:"host"`
	CrawlDelaySeconds *int32 `json:"crawl_delay_seconds"`
}

func (q *Queries) SetHostCrawlDelay(ctx context.Context, arg SetHostCrawlDelayParams) error {
	_, err := q.db.Exec(ctx, setHostCrawlDelay, arg.Host, arg.CrawlDelaySeconds)
	return err
}

const updateHostCookies = `-- name: UpdateHostCookies :exec
UPDATE host_retrieval_state SET cookies = $2, updated_at = now() WHERE host = $1
`

type UpdateHostCookiesParams struct {
	Host    string `json:"host"`
	Cookies []byte `json:"cookies"`
}

func (q *Queries) UpdateHostCookies(ctx context.Context, arg UpdateHostCookiesParams) error {
	_, err := q.db.Exec(ctx, updateHostCookies, arg.Host, arg.Cookies)
	return err
}

const upsertHostRetrievalState = `-- name: UpsertHostRetrievalState :exec
INSERT INTO host_retrieval_state (
    host, identity_version, current_rung, rung_last_verified_at,
    cookies, consecutive_blocks, cooling_off_until,
    last_block_at, last_block_reason, crawl_delay_seconds
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
) ON CONFLICT (host) DO UPDATE SET
    identity_version = EXCLUDED.identity_version,
    current_rung = EXCLUDED.current_rung,
    rung_last_verified_at = EXCLUDED.rung_last_verified_at,
    cookies = EXCLUDED.cookies,
    consecutive_blocks = EXCLUDED.consecutive_blocks,
    cooling_off_until = EXCLUDED.cooling_off_until,
    last_block_at = EXCLUDED.last_block_at,
    last_block_reason = EXCLUDED.last_block_reason,
    crawl_delay_seconds = EXCLUDED.crawl_delay_seconds,
    updated_at = now()
`

type UpsertHostRetrievalStateParams struct {
	Host               string             `json:"host"`
	IdentityVersion    string             `json:"identity_version"`
	CurrentRung        string             `json:"current_rung"`
	RungLastVerifiedAt pgtype.Timestamptz `json:"rung_last_verified_at"`
	Cookies            []byte             `json:"cookies"`
	ConsecutiveBlocks  int32              `json:"consecutive_blocks"`
	CoolingOffUntil    pgtype.Timestamptz `json:"cooling_off_until"`
	LastBlockAt        pgtype.Timestamptz `json:"last_block_at"`
	LastBlockReason    *string            `json:"last_block_reason"`
	CrawlDelaySeconds  *int32             `json:"crawl_delay_seconds"`
}

func (q *Queries) UpsertHostRetrievalState(ctx context.Context, arg UpsertHostRetrievalStateParams) error {
	_, err := q.db.Exec(ctx, upsertHostRetrievalState,
		arg.Host,
		arg.IdentityVersion,
		arg.CurrentRung,
		arg.RungLastVerifiedAt,
		arg.Cookies,
		arg.ConsecutiveBlocks,
		arg.CoolingOffUntil,
		arg.LastBlockAt,
		arg.LastBlockReason,
		arg.CrawlDelaySeconds,
	)
	return err
}
