// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotencyledger.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIdempotencyLedgerEntry = `-- name: GetIdempotencyLedgerEntry :one
SELECT idempotency_key, work_type, run_id, accepted_at FROM idempotency_ledger WHERE idempotency_key = $1
`

func (q *Queries) GetIdempotencyLedgerEntry(ctx context.Context, idempotencyKey string) (IdempotencyLedger, error) {
	row := q.db.QueryRow(ctx, getIdempotencyLedgerEntry, idempotencyKey)
	var i IdempotencyLedger
	err := row.Scan(
		&i.IdempotencyKey,
		&i.WorkType,
		&i.RunID,
		&i.AcceptedAt,
	)
	return i, err
}

const insertIdempotencyLedgerEntry = `-- name: InsertIdempotencyLedgerEntry :one
INSERT INTO idempotency_ledger (idempotency_key, work_type, run_id)
VALUES ($1, $2, $3)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING idempotency_key, work_type, run_id, accepted_at
`

type InsertIdempotencyLedgerEntryParams struct {
	IdempotencyKey string      `json:"idempotency_key"`
	WorkType       string      `json:"work_type"`
	RunID          pgtype.UUID `json:"run_id"`
}

// The dedupe write (data-model.md § 7): a redelivery of the same
// idempotency_key hits the primary key and inserts nothing, which is how the
// caller (events.Admit) tells a fresh accept from a duplicate/superseded one.
func (q *Queries) InsertIdempotencyLedgerEntry(ctx context.Context, arg InsertIdempotencyLedgerEntryParams) (IdempotencyLedger, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyLedgerEntry, arg.IdempotencyKey, arg.WorkType, arg.RunID)
	var i IdempotencyLedger
	err := row.Scan(
		&i.IdempotencyKey,
		&i.WorkType,
		&i.RunID,
		&i.AcceptedAt,
	)
	return i, err
}

const pruneIdempotencyLedger = `-- name: PruneIdempotencyLedger :execrows
DELETE FROM idempotency_ledger WHERE accepted_at < $1
`

// Retention: rows older than the longest retry budget plus a margin
// (data-model.md § 7). Cutoff is computed by the caller.
func (q *Queries) PruneIdempotencyLedger(ctx context.Context, acceptedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, pruneIdempotencyLedger, acceptedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
