// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const deleteAllJobs = `-- name: DeleteAllJobs :execrows
DELETE FROM "Job"
`

// Wipes every job. FK "ON DELETE cascade" clears the dependent
// Application / GeneratedDocument / MatchResult / Activity rows too.
func (q *Queries) DeleteAllJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJobByDedupeKey = `-- name: GetJobByDedupeKey :one
SELECT "id" FROM "Job" WHERE "dedupeKey" = $1
`

func (q *Queries) GetJobByDedupeKey(ctx context.Context, dedupekey string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getJobByDedupeKey, dedupekey)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status, "detailScrapedAt" FROM "Job" WHERE "id" = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.SourceKey,
		&i.ExternalId,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.SalaryRaw,
		&i.Url,
		&i.Description,
		&i.Raw,
		&i.PostedAt,
		&i.IngestedAt,
		&i.Embedding,
		&i.Status,
		&i.DetailScrapedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO "Job" (
  "dedupeKey", "sourceKey", "externalId", "title", "company", "location",
  "remote", "salaryRaw", "url", "description", "raw", "postedAt"
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status, "detailScrapedAt"
`

type InsertJobParams struct {
	DedupeKey   string           `json:"dedupeKey"`
	SourceKey   string           `json:"sourceKey"`
	ExternalId  *string          `json:"externalId"`
	Title       string           `json:"title"`
	Company     string           `json:"company"`
	Location    *string          `json:"location"`
	Remote      bool             `json:"remote"`
	SalaryRaw   *string          `json:"salaryRaw"`
	Url         string           `json:"url"`
	Description string           `json:"description"`
	Raw         []byte           `json:"raw"`
	PostedAt    pgtype.Timestamp `json:"postedAt"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.DedupeKey,
		arg.SourceKey,
		arg.ExternalId,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Remote,
		arg.SalaryRaw,
		arg.Url,
		arg.Description,
		arg.Raw,
		arg.PostedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.SourceKey,
		&i.ExternalId,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.SalaryRaw,
		&i.Url,
		&i.Description,
		&i.Raw,
		&i.PostedAt,
		&i.IngestedAt,
		&i.Embedding,
		&i.Status,
		&i.DetailScrapedAt,
	)
	return i, err
}

const listJobsNeedingDetail = `-- name: ListJobsNeedingDetail :many
SELECT id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status, "detailScrapedAt" FROM "Job"
WHERE "sourceKey" = $1 AND "detailScrapedAt" IS NULL
ORDER BY "ingestedAt" ASC
LIMIT $2
`

type ListJobsNeedingDetailParams struct {
	SourceKey string `json:"sourceKey"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListJobsNeedingDetail(ctx context.Context, arg ListJobsNeedingDetailParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsNeedingDetail, arg.SourceKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.DedupeKey,
			&i.SourceKey,
			&i.ExternalId,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.SalaryRaw,
			&i.Url,
			&i.Description,
			&i.Raw,
			&i.PostedAt,
			&i.IngestedAt,
			&i.Embedding,
			&i.Status,
			&i.DetailScrapedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobDetail = `-- name: UpdateJobDetail :one
UPDATE "Job" SET
  "description" = COALESCE(NULLIF($1, ''), "description"),
  "salaryRaw" = COALESCE($2, "salaryRaw"),
  "location" = COALESCE($3, "location"),
  "remote" = "remote" OR $4::bool,
  "raw" = $5,
  "postedAt" = COALESCE($6, "postedAt"),
  "detailScrapedAt" = now()
WHERE "id" = $7
RETURNING id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status, "detailScrapedAt"
`

type UpdateJobDetailParams struct {
	Description interface{}      `json:"description"`
	SalaryRaw   *string          `json:"salaryRaw"`
	Location    *string          `json:"location"`
	Remote      bool             `json:"remote"`
	Raw         []byte           `json:"raw"`
	PostedAt    pgtype.Timestamp `json:"postedAt"`
	ID          pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateJobDetail(ctx context.Context, arg UpdateJobDetailParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobDetail,
		arg.Description,
		arg.SalaryRaw,
		arg.Location,
		arg.Remote,
		arg.Raw,
		arg.PostedAt,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.SourceKey,
		&i.ExternalId,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.SalaryRaw,
		&i.Url,
		&i.Description,
		&i.Raw,
		&i.PostedAt,
		&i.IngestedAt,
		&i.Embedding,
		&i.Status,
		&i.DetailScrapedAt,
	)
	return i, err
}

const updateJobEmbedding = `-- name: UpdateJobEmbedding :exec
UPDATE "Job" SET "embedding" = $2 WHERE "id" = $1
`

type UpdateJobEmbeddingParams struct {
	ID        pgtype.UUID      `json:"id"`
	Embedding *pgvector.Vector `json:"embedding"`
}

func (q *Queries) UpdateJobEmbedding(ctx context.Context, arg UpdateJobEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateJobEmbedding, arg.ID, arg.Embedding)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE "Job" SET "status" = $2 WHERE "id" = $1
RETURNING id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status, "detailScrapedAt"
`

type UpdateJobStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.SourceKey,
		&i.ExternalId,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.SalaryRaw,
		&i.Url,
		&i.Description,
		&i.Raw,
		&i.PostedAt,
		&i.IngestedAt,
		&i.Embedding,
		&i.Status,
		&i.DetailScrapedAt,
	)
	return i, err
}
