// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const deleteAllJobs = `-- name: DeleteAllJobs :execrows
DELETE FROM "Job"
`

// Wipes every job. FK "ON DELETE cascade" clears the dependent
// Application / GeneratedDocument / MatchResult / Activity rows too.
func (q *Queries) DeleteAllJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findJobByCompany = `-- name: FindJobByCompany :one
SELECT id, "sourceKey", "title" FROM "Job"
WHERE LOWER("company") = LOWER($1)
  AND "sourceKey" != $2
ORDER BY "ingestedAt" DESC
LIMIT 1
`

type FindJobByCompanyParams struct {
	Lower     string `json:"lower"`
	SourceKey string `json:"sourceKey"`
}

type FindJobByCompanyRow struct {
	ID        pgtype.UUID `json:"id"`
	SourceKey string      `json:"sourceKey"`
	Title     string      `json:"title"`
}

func (q *Queries) FindJobByCompany(ctx context.Context, arg FindJobByCompanyParams) (FindJobByCompanyRow, error) {
	row := q.db.QueryRow(ctx, findJobByCompany, arg.Lower, arg.SourceKey)
	var i FindJobByCompanyRow
	err := row.Scan(&i.ID, &i.SourceKey, &i.Title)
	return i, err
}

const getJobByDedupeKey = `-- name: GetJobByDedupeKey :one
SELECT "id" FROM "Job" WHERE "dedupeKey" = $1
`

func (q *Queries) GetJobByDedupeKey(ctx context.Context, dedupekey string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getJobByDedupeKey, dedupekey)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status, "detailScrapedAt", "salaryMin", "salaryMax", "salaryCurrency", "salaryConfidence", "salarySource", "seenCount", "subscriptionId", "seenOnSources" FROM "Job" WHERE "id" = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.SourceKey,
		&i.ExternalId,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.SalaryRaw,
		&i.Url,
		&i.Description,
		&i.Raw,
		&i.PostedAt,
		&i.IngestedAt,
		&i.Embedding,
		&i.Status,
		&i.DetailScrapedAt,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryConfidence,
		&i.SalarySource,
		&i.SeenCount,
		&i.SubscriptionId,
		&i.SeenOnSources,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO "Job" (
  "dedupeKey", "sourceKey", "externalId", "title", "company", "location",
  "remote", "salaryRaw", "url", "description", "raw", "postedAt", "subscriptionId",
  "seenOnSources"
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
  ARRAY[$2]
)
RETURNING id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status, "detailScrapedAt", "salaryMin", "salaryMax", "salaryCurrency", "salaryConfidence", "salarySource", "seenCount", "subscriptionId", "seenOnSources"
`

type InsertJobParams struct {
	DedupeKey      string           `json:"dedupeKey"`
	SourceKey      string           `json:"sourceKey"`
	ExternalId     *string          `json:"externalId"`
	Title          string           `json:"title"`
	Company        string           `json:"company"`
	Location       *string          `json:"location"`
	Remote         bool             `json:"remote"`
	SalaryRaw      *string          `json:"salaryRaw"`
	Url            string           `json:"url"`
	Description    string           `json:"description"`
	Raw            []byte           `json:"raw"`
	PostedAt       pgtype.Timestamp `json:"postedAt"`
	SubscriptionId pgtype.UUID      `json:"subscriptionId"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.DedupeKey,
		arg.SourceKey,
		arg.ExternalId,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Remote,
		arg.SalaryRaw,
		arg.Url,
		arg.Description,
		arg.Raw,
		arg.PostedAt,
		arg.SubscriptionId,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.SourceKey,
		&i.ExternalId,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.SalaryRaw,
		&i.Url,
		&i.Description,
		&i.Raw,
		&i.PostedAt,
		&i.IngestedAt,
		&i.Embedding,
		&i.Status,
		&i.DetailScrapedAt,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryConfidence,
		&i.SalarySource,
		&i.SeenCount,
		&i.SubscriptionId,
		&i.SeenOnSources,
	)
	return i, err
}

const listJobsMissingMatch = `-- name: ListJobsMissingMatch :many
SELECT j."id", j."company", j."title" FROM "Job" j
LEFT JOIN "MatchResult" mr ON mr."jobId" = j."id"
WHERE mr."id" IS NULL
  AND j."status" != 'hidden'
  AND j."ingestedAt" < $1::timestamp
  AND j."ingestedAt" > $2::timestamp
ORDER BY j."ingestedAt" DESC
LIMIT $3
`

type ListJobsMissingMatchParams struct {
	OlderThan pgtype.Timestamp `json:"older_than"`
	NewerThan pgtype.Timestamp `json:"newer_than"`
	Limit     int32            `json:"limit"`
}

type ListJobsMissingMatchRow struct {
	ID      pgtype.UUID `json:"id"`
	Company string      `json:"company"`
	Title   string      `json:"title"`
}

// Jobs that were inserted but never produced a MatchResult row. Insert and
// enqueue aren't atomic, so a crash (or a Redis blip) between the two strands
// the job: no score, and therefore invisible in the score-sorted feed, with
// nothing to ever retry it. The scheduler re-enqueues these.
//
// Note a prefiltered-out job is NOT missing a match: matching writes a row
// carrying just the similarity, so the sweep passes over it.
//
// Bounded on both sides. "older_than" leaves in-flight jobs alone (including
// ones still queued behind enrichment); "newer_than" stops a job whose
// matching fails deterministically from being retried on every tick forever.
func (q *Queries) ListJobsMissingMatch(ctx context.Context, arg ListJobsMissingMatchParams) ([]ListJobsMissingMatchRow, error) {
	rows, err := q.db.Query(ctx, listJobsMissingMatch, arg.OlderThan, arg.NewerThan, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsMissingMatchRow
	for rows.Next() {
		var i ListJobsMissingMatchRow
		if err := rows.Scan(&i.ID, &i.Company, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsNeedingDetail = `-- name: ListJobsNeedingDetail :many
SELECT id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status, "detailScrapedAt", "salaryMin", "salaryMax", "salaryCurrency", "salaryConfidence", "salarySource", "seenCount", "subscriptionId", "seenOnSources" FROM "Job"
WHERE "sourceKey" = $1 AND "detailScrapedAt" IS NULL
ORDER BY "ingestedAt" ASC
LIMIT $2
`

type ListJobsNeedingDetailParams struct {
	SourceKey string `json:"sourceKey"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListJobsNeedingDetail(ctx context.Context, arg ListJobsNeedingDetailParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsNeedingDetail, arg.SourceKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.DedupeKey,
			&i.SourceKey,
			&i.ExternalId,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.SalaryRaw,
			&i.Url,
			&i.Description,
			&i.Raw,
			&i.PostedAt,
			&i.IngestedAt,
			&i.Embedding,
			&i.Status,
			&i.DetailScrapedAt,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.SalaryConfidence,
			&i.SalarySource,
			&i.SeenCount,
			&i.SubscriptionId,
			&i.SeenOnSources,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeJobBoard = `-- name: MergeJobBoard :one
UPDATE "Job" SET
  "url" = $2,
  "sourceKey" = $3,
  "seenOnSources" = array_append("seenOnSources", $4)
WHERE "id" = $1
RETURNING id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status, "detailScrapedAt", "salaryMin", "salaryMax", "salaryCurrency", "salaryConfidence", "salarySource", "seenCount", "subscriptionId", "seenOnSources"
`

type MergeJobBoardParams struct {
	ID          pgtype.UUID `json:"id"`
	Url         string      `json:"url"`
	SourceKey   string      `json:"sourceKey"`
	ArrayAppend interface{} `json:"array_append"`
}

func (q *Queries) MergeJobBoard(ctx context.Context, arg MergeJobBoardParams) (Job, error) {
	row := q.db.QueryRow(ctx, mergeJobBoard,
		arg.ID,
		arg.Url,
		arg.SourceKey,
		arg.ArrayAppend,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.SourceKey,
		&i.ExternalId,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.SalaryRaw,
		&i.Url,
		&i.Description,
		&i.Raw,
		&i.PostedAt,
		&i.IngestedAt,
		&i.Embedding,
		&i.Status,
		&i.DetailScrapedAt,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryConfidence,
		&i.SalarySource,
		&i.SeenCount,
		&i.SubscriptionId,
		&i.SeenOnSources,
	)
	return i, err
}

const recordJobRepost = `-- name: RecordJobRepost :one
UPDATE "Job" SET "seenCount" = "seenCount" + 1, "ingestedAt" = now(),
  "subscriptionId" = COALESCE("subscriptionId", $2)
WHERE "dedupeKey" = $1
RETURNING id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status, "detailScrapedAt", "salaryMin", "salaryMax", "salaryCurrency", "salaryConfidence", "salarySource", "seenCount", "subscriptionId", "seenOnSources"
`

type RecordJobRepostParams struct {
	DedupeKey      string      `json:"dedupeKey"`
	SubscriptionId pgtype.UUID `json:"subscriptionId"`
}

// Called by ingestion.persistIfNew when a job with this dedupeKey already
// exists: bumps "seenCount" and refreshes "ingestedAt" so the posting's
// reappearance is durable, feeding the ghost-job repost signal (005).
// Backfills "subscriptionId" when the job wasn't already attributed to one,
// so a job first seen by an unrelated run still surfaces under a subscription
// that later rediscovers it (dashboard "filter by Subscription").
func (q *Queries) RecordJobRepost(ctx context.Context, arg RecordJobRepostParams) (Job, error) {
	row := q.db.QueryRow(ctx, recordJobRepost, arg.DedupeKey, arg.SubscriptionId)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.SourceKey,
		&i.ExternalId,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.SalaryRaw,
		&i.Url,
		&i.Description,
		&i.Raw,
		&i.PostedAt,
		&i.IngestedAt,
		&i.Embedding,
		&i.Status,
		&i.DetailScrapedAt,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryConfidence,
		&i.SalarySource,
		&i.SeenCount,
		&i.SubscriptionId,
		&i.SeenOnSources,
	)
	return i, err
}

const updateJobDetail = `-- name: UpdateJobDetail :one
UPDATE "Job" SET
  "description" = COALESCE(NULLIF($1, ''), "description"),
  "salaryRaw" = COALESCE($2, "salaryRaw"),
  "location" = COALESCE($3, "location"),
  "remote" = "remote" OR $4::bool,
  "raw" = $5,
  "postedAt" = COALESCE($6, "postedAt"),
  "detailScrapedAt" = now()
WHERE "id" = $7
RETURNING id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status, "detailScrapedAt", "salaryMin", "salaryMax", "salaryCurrency", "salaryConfidence", "salarySource", "seenCount", "subscriptionId", "seenOnSources"
`

type UpdateJobDetailParams struct {
	Description interface{}      `json:"description"`
	SalaryRaw   *string          `json:"salaryRaw"`
	Location    *string          `json:"location"`
	Remote      bool             `json:"remote"`
	Raw         []byte           `json:"raw"`
	PostedAt    pgtype.Timestamp `json:"postedAt"`
	ID          pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateJobDetail(ctx context.Context, arg UpdateJobDetailParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobDetail,
		arg.Description,
		arg.SalaryRaw,
		arg.Location,
		arg.Remote,
		arg.Raw,
		arg.PostedAt,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.SourceKey,
		&i.ExternalId,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.SalaryRaw,
		&i.Url,
		&i.Description,
		&i.Raw,
		&i.PostedAt,
		&i.IngestedAt,
		&i.Embedding,
		&i.Status,
		&i.DetailScrapedAt,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryConfidence,
		&i.SalarySource,
		&i.SeenCount,
		&i.SubscriptionId,
		&i.SeenOnSources,
	)
	return i, err
}

const updateJobEmbedding = `-- name: UpdateJobEmbedding :exec
UPDATE "Job" SET "embedding" = $2 WHERE "id" = $1
`

type UpdateJobEmbeddingParams struct {
	ID        pgtype.UUID      `json:"id"`
	Embedding *pgvector.Vector `json:"embedding"`
}

func (q *Queries) UpdateJobEmbedding(ctx context.Context, arg UpdateJobEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateJobEmbedding, arg.ID, arg.Embedding)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE "Job" SET "status" = $2 WHERE "id" = $1
RETURNING id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status, "detailScrapedAt", "salaryMin", "salaryMax", "salaryCurrency", "salaryConfidence", "salarySource", "seenCount", "subscriptionId", "seenOnSources"
`

type UpdateJobStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.SourceKey,
		&i.ExternalId,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.SalaryRaw,
		&i.Url,
		&i.Description,
		&i.Raw,
		&i.PostedAt,
		&i.IngestedAt,
		&i.Embedding,
		&i.Status,
		&i.DetailScrapedAt,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryConfidence,
		&i.SalarySource,
		&i.SeenCount,
		&i.SubscriptionId,
		&i.SeenOnSources,
	)
	return i, err
}
