// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobcontact.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listJobContactsByJob = `-- name: ListJobContactsByJob :many
SELECT id, "jobId", name, title, "linkedInUrl", email, phone, source, confidence, "fetchedAt" FROM "JobContact"
WHERE "jobId" = $1
ORDER BY
  confidence DESC,
  CASE source
    WHEN 'posting' THEN 0
    WHEN 'company-page' THEN 1
    WHEN 'linkedin' THEN 2
    ELSE 3
  END,
  name ASC
`

// Deterministic best-first order for FR-010/SC-010: confidence descending,
// then a fixed source priority (posting beats company-page beats linkedin,
// reflecting how directly each source names the person as owning the req),
// then name as the final tie-break so identical inputs always render the
// same order.
func (q *Queries) ListJobContactsByJob(ctx context.Context, jobid pgtype.UUID) ([]JobContact, error) {
	rows, err := q.db.Query(ctx, listJobContactsByJob, jobid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobContact
	for rows.Next() {
		var i JobContact
		if err := rows.Scan(
			&i.ID,
			&i.JobId,
			&i.Name,
			&i.Title,
			&i.LinkedInUrl,
			&i.Email,
			&i.Phone,
			&i.Source,
			&i.Confidence,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJobContact = `-- name: UpsertJobContact :one
INSERT INTO "JobContact" ("jobId", name, title, "linkedInUrl", email, phone, source, confidence, "fetchedAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT ("jobId", source, name) DO UPDATE SET
  title = EXCLUDED.title,
  "linkedInUrl" = EXCLUDED."linkedInUrl",
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  confidence = EXCLUDED.confidence,
  "fetchedAt" = now()
RETURNING id, "jobId", name, title, "linkedInUrl", email, phone, source, confidence, "fetchedAt"
`

type UpsertJobContactParams struct {
	JobId       pgtype.UUID `json:"jobId"`
	Name        string      `json:"name"`
	Title       *string     `json:"title"`
	LinkedInUrl *string     `json:"linkedInUrl"`
	Email       *string     `json:"email"`
	Phone       *string     `json:"phone"`
	Source      string      `json:"source"`
	Confidence  float64     `json:"confidence"`
}

// Insert-or-update on (jobId, source, name) per FR-013: a re-run of
// resolution for the same job/source/name updates the existing row (fresh
// title/channels/confidence/fetchedAt) instead of duplicating it.
func (q *Queries) UpsertJobContact(ctx context.Context, arg UpsertJobContactParams) (JobContact, error) {
	row := q.db.QueryRow(ctx, upsertJobContact,
		arg.JobId,
		arg.Name,
		arg.Title,
		arg.LinkedInUrl,
		arg.Email,
		arg.Phone,
		arg.Source,
		arg.Confidence,
	)
	var i JobContact
	err := row.Scan(
		&i.ID,
		&i.JobId,
		&i.Name,
		&i.Title,
		&i.LinkedInUrl,
		&i.Email,
		&i.Phone,
		&i.Source,
		&i.Confidence,
		&i.FetchedAt,
	)
	return i, err
}
