// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: joblist.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const countJobs = `-- name: CountJobs :one
SELECT count(*)
FROM "Job" j
LEFT JOIN "MatchResult" mr ON mr."jobId" = j."id"
WHERE ($1::text IS NULL OR j."sourceKey" = $1)
  AND ($2::uuid IS NULL OR j."subscriptionId" = $2)
  AND (
    ($3::text IS NOT NULL AND j."status" = $3)
    OR ($3::text IS NULL AND j."status" != 'hidden')
  )
  AND ($4::bool IS NULL OR j."remote" = $4)
  AND (
    $5::text IS NULL
    OR j."title" ILIKE $5
    OR j."company" ILIKE $5
    OR j."description" ILIKE $5
  )
  AND ($6::int IS NULL OR mr."score" >= $6)
  AND (
    $7::int IS NULL
    OR j."salaryMax" IS NULL
    OR j."salaryCurrency" IS DISTINCT FROM 'USD'
    OR j."salaryMax" >= $7
  )
`

type CountJobsParams struct {
	Source         *string     `json:"source"`
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	Status         *string     `json:"status"`
	Remote         *bool       `json:"remote"`
	Q              *string     `json:"q"`
	MinScore       *int32      `json:"min_score"`
	SalaryFloor    *int32      `json:"salary_floor"`
}

func (q *Queries) CountJobs(ctx context.Context, arg CountJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs,
		arg.Source,
		arg.SubscriptionID,
		arg.Status,
		arg.Remote,
		arg.Q,
		arg.MinScore,
		arg.SalaryFloor,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getJobDocuments = `-- name: GetJobDocuments :many
SELECT id, "jobId", type, version, content, "pdfPath", model, "createdAt", company, title, vacancy FROM "GeneratedDocument" WHERE "jobId" = $1 ORDER BY "createdAt" DESC
`

func (q *Queries) GetJobDocuments(ctx context.Context, jobid pgtype.UUID) ([]GeneratedDocument, error) {
	rows, err := q.db.Query(ctx, getJobDocuments, jobid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneratedDocument
	for rows.Next() {
		var i GeneratedDocument
		if err := rows.Scan(
			&i.ID,
			&i.JobId,
			&i.Type,
			&i.Version,
			&i.Content,
			&i.PdfPath,
			&i.Model,
			&i.CreatedAt,
			&i.Company,
			&i.Title,
			&i.Vacancy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByDate = `-- name: ListJobsByDate :many
SELECT j.id, j."dedupeKey", j."sourceKey", j."externalId", j.title, j.company, j.location, j.remote, j."salaryRaw", j.url, j.description, j.raw, j."postedAt", j."ingestedAt", j.embedding, j.status, j."detailScrapedAt", j."salaryMin", j."salaryMax", j."salaryCurrency", j."salaryConfidence", j."salarySource", j."seenCount", j."subscriptionId", j."seenOnSources", j."embeddingHash", j.experience_level, j.experience_min_years, j.english_level, j.salary_estimate_raw, j.salary_estimate_min, j.salary_estimate_max, j.salary_estimate_currency, j."lastSeenRunId", mr."id" AS mr_id, mr."similarity" AS mr_similarity, mr."score" AS mr_score,
  mr."matchedSkills" AS mr_matched_skills, mr."missingSkills" AS mr_missing_skills,
  mr."summary" AS mr_summary, mr."redFlags" AS mr_red_flags, mr."model" AS mr_model,
  mr."createdAt" AS mr_created_at
FROM "Job" j
LEFT JOIN "MatchResult" mr ON mr."jobId" = j."id"
WHERE ($1::text IS NULL OR j."sourceKey" = $1)
  AND ($2::uuid IS NULL OR j."subscriptionId" = $2)
  AND (
    ($3::text IS NOT NULL AND j."status" = $3)
    OR ($3::text IS NULL AND j."status" != 'hidden')
  )
  AND ($4::bool IS NULL OR j."remote" = $4)
  AND (
    $5::text IS NULL
    OR j."title" ILIKE $5
    OR j."company" ILIKE $5
    OR j."description" ILIKE $5
  )
  AND ($6::int IS NULL OR mr."score" >= $6)
  AND (
    $7::int IS NULL
    OR j."salaryMax" IS NULL
    OR j."salaryCurrency" IS DISTINCT FROM 'USD'
    OR j."salaryMax" >= $7
  )
ORDER BY j."ingestedAt" DESC
OFFSET $8
LIMIT $9
`

type ListJobsByDateParams struct {
	Source         *string     `json:"source"`
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	Status         *string     `json:"status"`
	Remote         *bool       `json:"remote"`
	Q              *string     `json:"q"`
	MinScore       *int32      `json:"min_score"`
	SalaryFloor    *int32      `json:"salary_floor"`
	Offset         int32       `json:"offset"`
	Limit          int32       `json:"limit"`
}

type ListJobsByDateRow struct {
	ID                     pgtype.UUID      `json:"id"`
	DedupeKey              string           `json:"dedupeKey"`
	SourceKey              string           `json:"sourceKey"`
	ExternalId             *string          `json:"externalId"`
	Title                  string           `json:"title"`
	Company                string           `json:"company"`
	Location               *string          `json:"location"`
	Remote                 bool             `json:"remote"`
	SalaryRaw              *string          `json:"salaryRaw"`
	Url                    string           `json:"url"`
	Description            string           `json:"description"`
	Raw                    []byte           `json:"raw"`
	PostedAt               pgtype.Timestamp `json:"postedAt"`
	IngestedAt             pgtype.Timestamp `json:"ingestedAt"`
	Embedding              *pgvector.Vector `json:"embedding"`
	Status                 string           `json:"status"`
	DetailScrapedAt        pgtype.Timestamp `json:"detailScrapedAt"`
	SalaryMin              *int32           `json:"salaryMin"`
	SalaryMax              *int32           `json:"salaryMax"`
	SalaryCurrency         *string          `json:"salaryCurrency"`
	SalaryConfidence       *float64         `json:"salaryConfidence"`
	SalarySource           *string          `json:"salarySource"`
	SeenCount              int32            `json:"seenCount"`
	SubscriptionId         pgtype.UUID      `json:"subscriptionId"`
	SeenOnSources          []string         `json:"seenOnSources"`
	EmbeddingHash          *string          `json:"embeddingHash"`
	ExperienceLevel        *string          `json:"experience_level"`
	ExperienceMinYears     *int32           `json:"experience_min_years"`
	EnglishLevel           *string          `json:"english_level"`
	SalaryEstimateRaw      *string          `json:"salary_estimate_raw"`
	SalaryEstimateMin      *int32           `json:"salary_estimate_min"`
	SalaryEstimateMax      *int32           `json:"salary_estimate_max"`
	SalaryEstimateCurrency *string          `json:"salary_estimate_currency"`
	LastSeenRunId          pgtype.UUID      `json:"lastSeenRunId"`
	MrID                   pgtype.UUID      `json:"mr_id"`
	MrSimilarity           *float64         `json:"mr_similarity"`
	MrScore                *int32           `json:"mr_score"`
	MrMatchedSkills        []byte           `json:"mr_matched_skills"`
	MrMissingSkills        []byte           `json:"mr_missing_skills"`
	MrSummary              *string          `json:"mr_summary"`
	MrRedFlags             []byte           `json:"mr_red_flags"`
	MrModel                *string          `json:"mr_model"`
	MrCreatedAt            pgtype.Timestamp `json:"mr_created_at"`
}

func (q *Queries) ListJobsByDate(ctx context.Context, arg ListJobsByDateParams) ([]ListJobsByDateRow, error) {
	rows, err := q.db.Query(ctx, listJobsByDate,
		arg.Source,
		arg.SubscriptionID,
		arg.Status,
		arg.Remote,
		arg.Q,
		arg.MinScore,
		arg.SalaryFloor,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsByDateRow
	for rows.Next() {
		var i ListJobsByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.DedupeKey,
			&i.SourceKey,
			&i.ExternalId,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.SalaryRaw,
			&i.Url,
			&i.Description,
			&i.Raw,
			&i.PostedAt,
			&i.IngestedAt,
			&i.Embedding,
			&i.Status,
			&i.DetailScrapedAt,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.SalaryConfidence,
			&i.SalarySource,
			&i.SeenCount,
			&i.SubscriptionId,
			&i.SeenOnSources,
			&i.EmbeddingHash,
			&i.ExperienceLevel,
			&i.ExperienceMinYears,
			&i.EnglishLevel,
			&i.SalaryEstimateRaw,
			&i.SalaryEstimateMin,
			&i.SalaryEstimateMax,
			&i.SalaryEstimateCurrency,
			&i.LastSeenRunId,
			&i.MrID,
			&i.MrSimilarity,
			&i.MrScore,
			&i.MrMatchedSkills,
			&i.MrMissingSkills,
			&i.MrSummary,
			&i.MrRedFlags,
			&i.MrModel,
			&i.MrCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByScore = `-- name: ListJobsByScore :many
SELECT j.id, j."dedupeKey", j."sourceKey", j."externalId", j.title, j.company, j.location, j.remote, j."salaryRaw", j.url, j.description, j.raw, j."postedAt", j."ingestedAt", j.embedding, j.status, j."detailScrapedAt", j."salaryMin", j."salaryMax", j."salaryCurrency", j."salaryConfidence", j."salarySource", j."seenCount", j."subscriptionId", j."seenOnSources", j."embeddingHash", j.experience_level, j.experience_min_years, j.english_level, j.salary_estimate_raw, j.salary_estimate_min, j.salary_estimate_max, j.salary_estimate_currency, j."lastSeenRunId", mr."id" AS mr_id, mr."similarity" AS mr_similarity, mr."score" AS mr_score,
  mr."matchedSkills" AS mr_matched_skills, mr."missingSkills" AS mr_missing_skills,
  mr."summary" AS mr_summary, mr."redFlags" AS mr_red_flags, mr."model" AS mr_model,
  mr."createdAt" AS mr_created_at
FROM "Job" j
LEFT JOIN "MatchResult" mr ON mr."jobId" = j."id"
WHERE ($1::text IS NULL OR j."sourceKey" = $1)
  AND ($2::uuid IS NULL OR j."subscriptionId" = $2)
  AND (
    ($3::text IS NOT NULL AND j."status" = $3)
    OR ($3::text IS NULL AND j."status" != 'hidden')
  )
  AND ($4::bool IS NULL OR j."remote" = $4)
  AND (
    $5::text IS NULL
    OR j."title" ILIKE $5
    OR j."company" ILIKE $5
    OR j."description" ILIKE $5
  )
  AND ($6::int IS NULL OR mr."score" >= $6)
  AND (
    $7::int IS NULL
    OR j."salaryMax" IS NULL
    OR j."salaryCurrency" IS DISTINCT FROM 'USD'
    OR j."salaryMax" >= $7
  )
ORDER BY mr."score" DESC NULLS LAST, j."ingestedAt" DESC
OFFSET $8
LIMIT $9
`

type ListJobsByScoreParams struct {
	Source         *string     `json:"source"`
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	Status         *string     `json:"status"`
	Remote         *bool       `json:"remote"`
	Q              *string     `json:"q"`
	MinScore       *int32      `json:"min_score"`
	SalaryFloor    *int32      `json:"salary_floor"`
	Offset         int32       `json:"offset"`
	Limit          int32       `json:"limit"`
}

type ListJobsByScoreRow struct {
	ID                     pgtype.UUID      `json:"id"`
	DedupeKey              string           `json:"dedupeKey"`
	SourceKey              string           `json:"sourceKey"`
	ExternalId             *string          `json:"externalId"`
	Title                  string           `json:"title"`
	Company                string           `json:"company"`
	Location               *string          `json:"location"`
	Remote                 bool             `json:"remote"`
	SalaryRaw              *string          `json:"salaryRaw"`
	Url                    string           `json:"url"`
	Description            string           `json:"description"`
	Raw                    []byte           `json:"raw"`
	PostedAt               pgtype.Timestamp `json:"postedAt"`
	IngestedAt             pgtype.Timestamp `json:"ingestedAt"`
	Embedding              *pgvector.Vector `json:"embedding"`
	Status                 string           `json:"status"`
	DetailScrapedAt        pgtype.Timestamp `json:"detailScrapedAt"`
	SalaryMin              *int32           `json:"salaryMin"`
	SalaryMax              *int32           `json:"salaryMax"`
	SalaryCurrency         *string          `json:"salaryCurrency"`
	SalaryConfidence       *float64         `json:"salaryConfidence"`
	SalarySource           *string          `json:"salarySource"`
	SeenCount              int32            `json:"seenCount"`
	SubscriptionId         pgtype.UUID      `json:"subscriptionId"`
	SeenOnSources          []string         `json:"seenOnSources"`
	EmbeddingHash          *string          `json:"embeddingHash"`
	ExperienceLevel        *string          `json:"experience_level"`
	ExperienceMinYears     *int32           `json:"experience_min_years"`
	EnglishLevel           *string          `json:"english_level"`
	SalaryEstimateRaw      *string          `json:"salary_estimate_raw"`
	SalaryEstimateMin      *int32           `json:"salary_estimate_min"`
	SalaryEstimateMax      *int32           `json:"salary_estimate_max"`
	SalaryEstimateCurrency *string          `json:"salary_estimate_currency"`
	LastSeenRunId          pgtype.UUID      `json:"lastSeenRunId"`
	MrID                   pgtype.UUID      `json:"mr_id"`
	MrSimilarity           *float64         `json:"mr_similarity"`
	MrScore                *int32           `json:"mr_score"`
	MrMatchedSkills        []byte           `json:"mr_matched_skills"`
	MrMissingSkills        []byte           `json:"mr_missing_skills"`
	MrSummary              *string          `json:"mr_summary"`
	MrRedFlags             []byte           `json:"mr_red_flags"`
	MrModel                *string          `json:"mr_model"`
	MrCreatedAt            pgtype.Timestamp `json:"mr_created_at"`
}

func (q *Queries) ListJobsByScore(ctx context.Context, arg ListJobsByScoreParams) ([]ListJobsByScoreRow, error) {
	rows, err := q.db.Query(ctx, listJobsByScore,
		arg.Source,
		arg.SubscriptionID,
		arg.Status,
		arg.Remote,
		arg.Q,
		arg.MinScore,
		arg.SalaryFloor,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsByScoreRow
	for rows.Next() {
		var i ListJobsByScoreRow
		if err := rows.Scan(
			&i.ID,
			&i.DedupeKey,
			&i.SourceKey,
			&i.ExternalId,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.SalaryRaw,
			&i.Url,
			&i.Description,
			&i.Raw,
			&i.PostedAt,
			&i.IngestedAt,
			&i.Embedding,
			&i.Status,
			&i.DetailScrapedAt,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.SalaryConfidence,
			&i.SalarySource,
			&i.SeenCount,
			&i.SubscriptionId,
			&i.SeenOnSources,
			&i.EmbeddingHash,
			&i.ExperienceLevel,
			&i.ExperienceMinYears,
			&i.EnglishLevel,
			&i.SalaryEstimateRaw,
			&i.SalaryEstimateMin,
			&i.SalaryEstimateMax,
			&i.SalaryEstimateCurrency,
			&i.LastSeenRunId,
			&i.MrID,
			&i.MrSimilarity,
			&i.MrScore,
			&i.MrMatchedSkills,
			&i.MrMissingSkills,
			&i.MrSummary,
			&i.MrRedFlags,
			&i.MrModel,
			&i.MrCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
