// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobsignal.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAlwaysHiringByCompany = `-- name: CountAlwaysHiringByCompany :one
SELECT count(*)::int
FROM "Job" j
WHERE lower(j."company") = lower($1)
  AND j."ingestedAt" >= now() - interval '90 days'
  AND j."status" = 'found'
  AND NOT EXISTS (
    SELECT 1 FROM "Application" a
    WHERE a."jobId" = j."id"
      AND a."status" != 'found'
  )
`

// Always-hiring signal (FR-002d / FR-005 / FR-006), 90-day window. Counts
// this company's postings that never progressed past initial discovery: the
// fast-path "status = 'found'" is narrowed by an authoritative check against
// "Application" (rejected counts as progression, not as unprogressed — a
// rejection means a real process happened). Includes the job's own row: a
// lone posting yields 1, which the service/prompt treats as no evidence
// (SC-004), never as a signal skip.
func (q *Queries) CountAlwaysHiringByCompany(ctx context.Context, lower string) (int32, error) {
	row := q.db.QueryRow(ctx, countAlwaysHiringByCompany, lower)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countRepostsByDedupeKey = `-- name: CountRepostsByDedupeKey :one
SELECT "seenCount"::int FROM "Job" WHERE "dedupeKey" = $1
`

// Repost signal (FR-002a / FR-003). Reads the durable "seenCount" column
// (see migration 00016), NOT a recomputed identity or a naive
// `count(*) ... GROUP BY "dedupeKey"` — the latter can only ever return 1
// because "dedupeKey" carries Job_dedupeKey_unique. "seenCount" is bumped by
// ingestion.persistIfNew every time the same dedupeKey is re-ingested, so
// this genuinely reflects "how many times has this posting reappeared".
func (q *Queries) CountRepostsByDedupeKey(ctx context.Context, dedupekey string) (int32, error) {
	row := q.db.QueryRow(ctx, countRepostsByDedupeKey, dedupekey)
	var seenCount int32
	err := row.Scan(&seenCount)
	return seenCount, err
}

const getJobSignal = `-- name: GetJobSignal :one
SELECT id, "jobId", kind, score, signals, model, "createdAt" FROM "JobSignal" WHERE "jobId" = $1 AND "kind" = $2
`

type GetJobSignalParams struct {
	JobId pgtype.UUID `json:"jobId"`
	Kind  string      `json:"kind"`
}

func (q *Queries) GetJobSignal(ctx context.Context, arg GetJobSignalParams) (JobSignal, error) {
	row := q.db.QueryRow(ctx, getJobSignal, arg.JobId, arg.Kind)
	var i JobSignal
	err := row.Scan(
		&i.ID,
		&i.JobId,
		&i.Kind,
		&i.Score,
		&i.Signals,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const listJobSignalsByJobIds = `-- name: ListJobSignalsByJobIds :many
SELECT id, "jobId", kind, score, signals, model, "createdAt" FROM "JobSignal"
WHERE "jobId" = ANY($1::uuid[]) AND "kind" = $2
`

type ListJobSignalsByJobIdsParams struct {
	JobIds []pgtype.UUID `json:"job_ids"`
	Kind   string        `json:"kind"`
}

// Batch fetch for the feed: one query for the whole page, not one per job.
func (q *Queries) ListJobSignalsByJobIds(ctx context.Context, arg ListJobSignalsByJobIdsParams) ([]JobSignal, error) {
	rows, err := q.db.Query(ctx, listJobSignalsByJobIds, arg.JobIds, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobSignal
	for rows.Next() {
		var i JobSignal
		if err := rows.Scan(
			&i.ID,
			&i.JobId,
			&i.Kind,
			&i.Score,
			&i.Signals,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsForCrossBoardCheck = `-- name: ListJobsForCrossBoardCheck :many
SELECT "id", "sourceKey", "description"
FROM "Job"
WHERE "id" != $1
  AND "ingestedAt" >= now() - interval '60 days'
ORDER BY "ingestedAt" DESC
LIMIT 500
`

type ListJobsForCrossBoardCheckRow struct {
	ID          pgtype.UUID `json:"id"`
	SourceKey   string      `json:"sourceKey"`
	Description string      `json:"description"`
}

// Candidate rows for the cross-board-duplicate signal (FR-002c / FR-005).
// Postgres has no fuzzy-text-similarity primitive available here, so this
// query supplies candidates within the 60-day window and
// ghostjob.MeasureSignals does the simhash comparison + counts *distinct*
// "sourceKey" values among near-duplicates app-side. Bounded by LIMIT for
// single-user scale (assumption: thousands of rows, not millions).
func (q *Queries) ListJobsForCrossBoardCheck(ctx context.Context, id pgtype.UUID) ([]ListJobsForCrossBoardCheckRow, error) {
	rows, err := q.db.Query(ctx, listJobsForCrossBoardCheck, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsForCrossBoardCheckRow
	for rows.Next() {
		var i ListJobsForCrossBoardCheckRow
		if err := rows.Scan(&i.ID, &i.SourceKey, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJobSignal = `-- name: UpsertJobSignal :one
INSERT INTO "JobSignal" ("jobId", "kind", "score", "signals", "model")
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ("jobId", "kind") DO UPDATE SET
  "score" = EXCLUDED."score",
  "signals" = EXCLUDED."signals",
  "model" = EXCLUDED."model",
  "createdAt" = now()
RETURNING id, "jobId", kind, score, signals, model, "createdAt"
`

type UpsertJobSignalParams struct {
	JobId   pgtype.UUID `json:"jobId"`
	Kind    string      `json:"kind"`
	Score   int32       `json:"score"`
	Signals []byte      `json:"signals"`
	Model   *string     `json:"model"`
}

// FR-009: at most one result per (job, kind); a re-score replaces the row
// rather than accumulating history.
func (q *Queries) UpsertJobSignal(ctx context.Context, arg UpsertJobSignalParams) (JobSignal, error) {
	row := q.db.QueryRow(ctx, upsertJobSignal,
		arg.JobId,
		arg.Kind,
		arg.Score,
		arg.Signals,
		arg.Model,
	)
	var i JobSignal
	err := row.Scan(
		&i.ID,
		&i.JobId,
		&i.Kind,
		&i.Score,
		&i.Signals,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}
