// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keyworddiff.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteKeywordDiffByJobID = `-- name: DeleteKeywordDiffByJobID :exec
DELETE FROM "KeywordDiff" WHERE "jobId" = $1
`

func (q *Queries) DeleteKeywordDiffByJobID(ctx context.Context, jobid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteKeywordDiffByJobID, jobid)
	return err
}

const getKeywordDiffByJobID = `-- name: GetKeywordDiffByJobID :one
SELECT id, "jobId", matched, "missingRequired", "missingPreferred", "coveragePct", model, "createdAt" FROM "KeywordDiff" WHERE "jobId" = $1
`

func (q *Queries) GetKeywordDiffByJobID(ctx context.Context, jobid pgtype.UUID) (KeywordDiff, error) {
	row := q.db.QueryRow(ctx, getKeywordDiffByJobID, jobid)
	var i KeywordDiff
	err := row.Scan(
		&i.ID,
		&i.JobId,
		&i.Matched,
		&i.MissingRequired,
		&i.MissingPreferred,
		&i.CoveragePct,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const upsertKeywordDiff = `-- name: UpsertKeywordDiff :one
INSERT INTO "KeywordDiff" (
  "jobId", "matched", "missingRequired", "missingPreferred", "coveragePct", "model"
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT ("jobId") DO UPDATE SET
  "matched" = EXCLUDED."matched",
  "missingRequired" = EXCLUDED."missingRequired",
  "missingPreferred" = EXCLUDED."missingPreferred",
  "coveragePct" = EXCLUDED."coveragePct",
  "model" = EXCLUDED."model"
RETURNING id, "jobId", matched, "missingRequired", "missingPreferred", "coveragePct", model, "createdAt"
`

type UpsertKeywordDiffParams struct {
	JobId            pgtype.UUID `json:"jobId"`
	Matched          []byte      `json:"matched"`
	MissingRequired  []byte      `json:"missingRequired"`
	MissingPreferred []byte      `json:"missingPreferred"`
	CoveragePct      *float64    `json:"coveragePct"`
	Model            string      `json:"model"`
}

func (q *Queries) UpsertKeywordDiff(ctx context.Context, arg UpsertKeywordDiffParams) (KeywordDiff, error) {
	row := q.db.QueryRow(ctx, upsertKeywordDiff,
		arg.JobId,
		arg.Matched,
		arg.MissingRequired,
		arg.MissingPreferred,
		arg.CoveragePct,
		arg.Model,
	)
	var i KeywordDiff
	err := row.Scan(
		&i.ID,
		&i.JobId,
		&i.Matched,
		&i.MissingRequired,
		&i.MissingPreferred,
		&i.CoveragePct,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}
