// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llmsetting.sql

package sqlcgen

import (
	"context"
)

const listLlmTaskSettings = `-- name: ListLlmTaskSettings :many
SELECT "taskKey", provider, model, "updatedAt" FROM "LlmTaskSetting" ORDER BY "taskKey"
`

func (q *Queries) ListLlmTaskSettings(ctx context.Context) ([]LlmTaskSetting, error) {
	rows, err := q.db.Query(ctx, listLlmTaskSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmTaskSetting
	for rows.Next() {
		var i LlmTaskSetting
		if err := rows.Scan(
			&i.TaskKey,
			&i.Provider,
			&i.Model,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLlmTaskSetting = `-- name: UpsertLlmTaskSetting :one
INSERT INTO "LlmTaskSetting" (
  "taskKey", "provider", "model"
) VALUES (
  $1, $2, $3
)
ON CONFLICT ("taskKey") DO UPDATE SET
  "provider" = EXCLUDED."provider",
  "model" = EXCLUDED."model",
  "updatedAt" = now()
RETURNING "taskKey", provider, model, "updatedAt"
`

type UpsertLlmTaskSettingParams struct {
	TaskKey  string `json:"taskKey"`
	Provider string `json:"provider"`
	Model    string `json:"model"`
}

func (q *Queries) UpsertLlmTaskSetting(ctx context.Context, arg UpsertLlmTaskSettingParams) (LlmTaskSetting, error) {
	row := q.db.QueryRow(ctx, upsertLlmTaskSetting, arg.TaskKey, arg.Provider, arg.Model)
	var i LlmTaskSetting
	err := row.Scan(
		&i.TaskKey,
		&i.Provider,
		&i.Model,
		&i.UpdatedAt,
	)
	return i, err
}
