// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ActivityRun struct {
	ID          pgtype.UUID      `json:"id"`
	Op          string           `json:"op"`
	State       string           `json:"state"`
	Label       string           `json:"label"`
	Step        *string          `json:"step"`
	JobId       pgtype.UUID      `json:"jobId"`
	SourceKey   *string          `json:"sourceKey"`
	QueueTaskId *string          `json:"queueTaskId"`
	RefId       *string          `json:"refId"`
	Error       *string          `json:"error"`
	Meta        []byte           `json:"meta"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	StartedAt   pgtype.Timestamp `json:"startedAt"`
	FinishedAt  pgtype.Timestamp `json:"finishedAt"`
}

type Application struct {
	ID        pgtype.UUID      `json:"id"`
	JobId     pgtype.UUID      `json:"jobId"`
	Status    string           `json:"status"`
	Notes     *string          `json:"notes"`
	AppliedAt pgtype.Timestamp `json:"appliedAt"`
	Events    []byte           `json:"events"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type GeneratedDocument struct {
	ID        pgtype.UUID      `json:"id"`
	JobId     pgtype.UUID      `json:"jobId"`
	Type      string           `json:"type"`
	Version   int32            `json:"version"`
	Content   []byte           `json:"content"`
	PdfPath   *string          `json:"pdfPath"`
	Model     string           `json:"model"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Company   *string          `json:"company"`
	Title     *string          `json:"title"`
	Vacancy   *string          `json:"vacancy"`
}

type Job struct {
	ID              pgtype.UUID      `json:"id"`
	DedupeKey       string           `json:"dedupeKey"`
	SourceKey       string           `json:"sourceKey"`
	ExternalId      *string          `json:"externalId"`
	Title           string           `json:"title"`
	Company         string           `json:"company"`
	Location        *string          `json:"location"`
	Remote          bool             `json:"remote"`
	SalaryRaw       *string          `json:"salaryRaw"`
	Url             string           `json:"url"`
	Description     string           `json:"description"`
	Raw             []byte           `json:"raw"`
	PostedAt        pgtype.Timestamp `json:"postedAt"`
	IngestedAt      pgtype.Timestamp `json:"ingestedAt"`
	Embedding       *pgvector.Vector `json:"embedding"`
	Status          string           `json:"status"`
	DetailScrapedAt pgtype.Timestamp `json:"detailScrapedAt"`
}

type JobSource struct {
	ID      pgtype.UUID `json:"id"`
	Key     string      `json:"key"`
	Kind    string      `json:"kind"`
	Enabled bool        `json:"enabled"`
	Config  []byte      `json:"config"`
	Healthy bool        `json:"healthy"`
}

type KeywordDiff struct {
	ID               pgtype.UUID      `json:"id"`
	JobId            pgtype.UUID      `json:"jobId"`
	Matched          []byte           `json:"matched"`
	MissingRequired  []byte           `json:"missingRequired"`
	MissingPreferred []byte           `json:"missingPreferred"`
	CoveragePct      *float64         `json:"coveragePct"`
	Model            string           `json:"model"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
}

type MatchResult struct {
	ID            pgtype.UUID      `json:"id"`
	JobId         pgtype.UUID      `json:"jobId"`
	Similarity    float64          `json:"similarity"`
	Score         *int32           `json:"score"`
	MatchedSkills []byte           `json:"matchedSkills"`
	MissingSkills []byte           `json:"missingSkills"`
	Summary       *string          `json:"summary"`
	RedFlags      []byte           `json:"redFlags"`
	Model         string           `json:"model"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
}

type NormalizedTerm struct {
	ID        pgtype.UUID      `json:"id"`
	Source    string           `json:"source"`
	SourceId  pgtype.UUID      `json:"sourceId"`
	Original  string           `json:"original"`
	Canonical string           `json:"canonical"`
	Stemmed   string           `json:"stemmed"`
	Category  *string          `json:"category"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type Profile struct {
	ID             pgtype.UUID      `json:"id"`
	Name           string           `json:"name"`
	Document       []byte           `json:"document"`
	ExtraNotes     *string          `json:"extraNotes"`
	Embedding      *pgvector.Vector `json:"embedding"`
	EmbedModel     *string          `json:"embedModel"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	RendercvConfig []byte           `json:"rendercvConfig"`
	RendercvYaml   *string          `json:"rendercvYaml"`
}

type SavedSearch struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Query     []byte           `json:"query"`
	Cron      string           `json:"cron"`
	Enabled   bool             `json:"enabled"`
	LastRunAt pgtype.Timestamp `json:"lastRunAt"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type SourceRun struct {
	ID         pgtype.UUID      `json:"id"`
	SourceId   pgtype.UUID      `json:"sourceId"`
	SearchId   *string          `json:"searchId"`
	StartedAt  pgtype.Timestamp `json:"startedAt"`
	FinishedAt pgtype.Timestamp `json:"finishedAt"`
	Ok         *bool            `json:"ok"`
	Found      int32            `json:"found"`
	New        int32            `json:"new"`
	Error      *string          `json:"error"`
}

type Subscription struct {
	ID        pgtype.UUID      `json:"id"`
	SourceKey string           `json:"sourceKey"`
	Name      *string          `json:"name"`
	Url       string           `json:"url"`
	Enabled   bool             `json:"enabled"`
	LastRunAt pgtype.Timestamp `json:"lastRunAt"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type SynonymOverride struct {
	ID        pgtype.UUID      `json:"id"`
	Alias     string           `json:"alias"`
	Canonical string           `json:"canonical"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}
