// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO "Profile" ("name", "document", "extraNotes")
VALUES ($1, $2, $3)
RETURNING id, name, document, "extraNotes", embedding, "embedModel", "updatedAt", "createdAt"
`

type CreateProfileParams struct {
	Name       string  `json:"name"`
	Document   []byte  `json:"document"`
	ExtraNotes *string `json:"extraNotes"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.Name, arg.Document, arg.ExtraNotes)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Document,
		&i.ExtraNotes,
		&i.Embedding,
		&i.EmbedModel,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM "Profile" WHERE "id" = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfile, id)
	return err
}

const getDefaultProfile = `-- name: GetDefaultProfile :one
SELECT id, name, document, "extraNotes", embedding, "embedModel", "updatedAt", "createdAt" FROM "Profile" ORDER BY "updatedAt" DESC LIMIT 1
`

func (q *Queries) GetDefaultProfile(ctx context.Context) (Profile, error) {
	row := q.db.QueryRow(ctx, getDefaultProfile)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Document,
		&i.ExtraNotes,
		&i.Embedding,
		&i.EmbedModel,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, name, document, "extraNotes", embedding, "embedModel", "updatedAt", "createdAt" FROM "Profile" WHERE "id" = $1
`

func (q *Queries) GetProfile(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Document,
		&i.ExtraNotes,
		&i.Embedding,
		&i.EmbedModel,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, name, document, "extraNotes", embedding, "embedModel", "updatedAt", "createdAt" FROM "Profile" ORDER BY "updatedAt" DESC
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Document,
			&i.ExtraNotes,
			&i.Embedding,
			&i.EmbedModel,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profileHasEmbedding = `-- name: ProfileHasEmbedding :one
SELECT ("embedding" IS NOT NULL) AS has FROM "Profile" WHERE "id" = $1
`

func (q *Queries) ProfileHasEmbedding(ctx context.Context, id pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, profileHasEmbedding, id)
	var has interface{}
	err := row.Scan(&has)
	return has, err
}

const profileSimilarity = `-- name: ProfileSimilarity :one
SELECT (1 - ("embedding" <=> $2))::float8 AS similarity FROM "Profile" WHERE "id" = $1
`

type ProfileSimilarityParams struct {
	ID        pgtype.UUID      `json:"id"`
	Embedding *pgvector.Vector `json:"embedding"`
}

func (q *Queries) ProfileSimilarity(ctx context.Context, arg ProfileSimilarityParams) (float64, error) {
	row := q.db.QueryRow(ctx, profileSimilarity, arg.ID, arg.Embedding)
	var similarity float64
	err := row.Scan(&similarity)
	return similarity, err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE "Profile" SET
  "name" = COALESCE($1, "name"),
  "document" = COALESCE($2, "document"),
  "updatedAt" = now()
WHERE "id" = $3
`

type UpdateProfileParams struct {
	Name     *string     `json:"name"`
	Document []byte      `json:"document"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile, arg.Name, arg.Document, arg.ID)
	return err
}

const updateProfileEmbedding = `-- name: UpdateProfileEmbedding :exec
UPDATE "Profile" SET "embedding" = $2, "embedModel" = $3 WHERE "id" = $1
`

type UpdateProfileEmbeddingParams struct {
	ID         pgtype.UUID      `json:"id"`
	Embedding  *pgvector.Vector `json:"embedding"`
	EmbedModel *string          `json:"embedModel"`
}

func (q *Queries) UpdateProfileEmbedding(ctx context.Context, arg UpdateProfileEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateProfileEmbedding, arg.ID, arg.Embedding, arg.EmbedModel)
	return err
}

const updateProfileExtraNotes = `-- name: UpdateProfileExtraNotes :exec
UPDATE "Profile" SET "extraNotes" = $2, "updatedAt" = now() WHERE "id" = $1
`

type UpdateProfileExtraNotesParams struct {
	ID         pgtype.UUID `json:"id"`
	ExtraNotes *string     `json:"extraNotes"`
}

func (q *Queries) UpdateProfileExtraNotes(ctx context.Context, arg UpdateProfileExtraNotesParams) error {
	_, err := q.db.Exec(ctx, updateProfileExtraNotes, arg.ID, arg.ExtraNotes)
	return err
}
