// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resumeshapesetting.sql

package sqlcgen

import (
	"context"
)

const getResumeShapeSetting = `-- name: GetResumeShapeSetting :one
SELECT id, "summaryLines", "skillsEnabled", "skillsMaxGroups", "experienceBulletsMin", "experienceBulletsMax", "targetPages", "projectsEnabled", "projectsMin", "projectsMax", "projectBulletsMax", "updatedAt", "certificationsEnabled", "certificationsMin", "certificationsMax", "fontSize", "experienceEnabled", "summaryEnabled", "educationEnabled" FROM "ResumeShapeSetting" WHERE "id" = 'default'
`

func (q *Queries) GetResumeShapeSetting(ctx context.Context) (ResumeShapeSetting, error) {
	row := q.db.QueryRow(ctx, getResumeShapeSetting)
	var i ResumeShapeSetting
	err := row.Scan(
		&i.ID,
		&i.SummaryLines,
		&i.SkillsEnabled,
		&i.SkillsMaxGroups,
		&i.ExperienceBulletsMin,
		&i.ExperienceBulletsMax,
		&i.TargetPages,
		&i.ProjectsEnabled,
		&i.ProjectsMin,
		&i.ProjectsMax,
		&i.ProjectBulletsMax,
		&i.UpdatedAt,
		&i.CertificationsEnabled,
		&i.CertificationsMin,
		&i.CertificationsMax,
		&i.FontSize,
		&i.ExperienceEnabled,
		&i.SummaryEnabled,
		&i.EducationEnabled,
	)
	return i, err
}

const updateResumeShapeSetting = `-- name: UpdateResumeShapeSetting :one
UPDATE "ResumeShapeSetting"
SET "summaryLines" = $1,
    "skillsEnabled" = $2,
    "skillsMaxGroups" = $3,
    "experienceBulletsMin" = $4,
    "experienceBulletsMax" = $5,
    "targetPages" = $6,
    "projectsEnabled" = $7,
    "projectsMin" = $8,
    "projectsMax" = $9,
    "projectBulletsMax" = $10,
    "certificationsEnabled" = $11,
    "certificationsMin" = $12,
    "certificationsMax" = $13,
    "fontSize" = $14,
    "experienceEnabled" = $15,
    "summaryEnabled" = $16,
    "educationEnabled" = $17,
    "updatedAt" = now()
WHERE "id" = 'default'
RETURNING id, "summaryLines", "skillsEnabled", "skillsMaxGroups", "experienceBulletsMin", "experienceBulletsMax", "targetPages", "projectsEnabled", "projectsMin", "projectsMax", "projectBulletsMax", "updatedAt", "certificationsEnabled", "certificationsMin", "certificationsMax", "fontSize", "experienceEnabled", "summaryEnabled", "educationEnabled"
`

type UpdateResumeShapeSettingParams struct {
	SummaryLines          int32 `json:"summaryLines"`
	SkillsEnabled         bool  `json:"skillsEnabled"`
	SkillsMaxGroups       int32 `json:"skillsMaxGroups"`
	ExperienceBulletsMin  int32 `json:"experienceBulletsMin"`
	ExperienceBulletsMax  int32 `json:"experienceBulletsMax"`
	TargetPages           int32 `json:"targetPages"`
	ProjectsEnabled       bool  `json:"projectsEnabled"`
	ProjectsMin           int32 `json:"projectsMin"`
	ProjectsMax           int32 `json:"projectsMax"`
	ProjectBulletsMax     int32 `json:"projectBulletsMax"`
	CertificationsEnabled bool  `json:"certificationsEnabled"`
	CertificationsMin     int32 `json:"certificationsMin"`
	CertificationsMax     int32 `json:"certificationsMax"`
	FontSize              int32 `json:"fontSize"`
	ExperienceEnabled     bool  `json:"experienceEnabled"`
	SummaryEnabled        bool  `json:"summaryEnabled"`
	EducationEnabled      bool  `json:"educationEnabled"`
}

func (q *Queries) UpdateResumeShapeSetting(ctx context.Context, arg UpdateResumeShapeSettingParams) (ResumeShapeSetting, error) {
	row := q.db.QueryRow(ctx, updateResumeShapeSetting,
		arg.SummaryLines,
		arg.SkillsEnabled,
		arg.SkillsMaxGroups,
		arg.ExperienceBulletsMin,
		arg.ExperienceBulletsMax,
		arg.TargetPages,
		arg.ProjectsEnabled,
		arg.ProjectsMin,
		arg.ProjectsMax,
		arg.ProjectBulletsMax,
		arg.CertificationsEnabled,
		arg.CertificationsMin,
		arg.CertificationsMax,
		arg.FontSize,
		arg.ExperienceEnabled,
		arg.SummaryEnabled,
		arg.EducationEnabled,
	)
	var i ResumeShapeSetting
	err := row.Scan(
		&i.ID,
		&i.SummaryLines,
		&i.SkillsEnabled,
		&i.SkillsMaxGroups,
		&i.ExperienceBulletsMin,
		&i.ExperienceBulletsMax,
		&i.TargetPages,
		&i.ProjectsEnabled,
		&i.ProjectsMin,
		&i.ProjectsMax,
		&i.ProjectBulletsMax,
		&i.UpdatedAt,
		&i.CertificationsEnabled,
		&i.CertificationsMin,
		&i.CertificationsMax,
		&i.FontSize,
		&i.ExperienceEnabled,
		&i.SummaryEnabled,
		&i.EducationEnabled,
	)
	return i, err
}
