// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: salary.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSalaryCacheByBucket = `-- name: GetSalaryCacheByBucket :many
SELECT id, bucket, "salaryMin", "salaryMax", currency, source, "sampleSize", "updatedAt" FROM "SalaryCache" WHERE bucket = $1
`

func (q *Queries) GetSalaryCacheByBucket(ctx context.Context, bucket string) ([]SalaryCache, error) {
	rows, err := q.db.Query(ctx, getSalaryCacheByBucket, bucket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalaryCache
	for rows.Next() {
		var i SalaryCache
		if err := rows.Scan(
			&i.ID,
			&i.Bucket,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.Currency,
			&i.Source,
			&i.SampleSize,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobSalary = `-- name: UpdateJobSalary :exec
UPDATE "Job" SET
  "salaryMin" = $2,
  "salaryMax" = $3,
  "salaryCurrency" = $4,
  "salaryConfidence" = $5,
  "salarySource" = $6
WHERE "id" = $1
`

type UpdateJobSalaryParams struct {
	ID               pgtype.UUID `json:"id"`
	SalaryMin        *int32      `json:"salaryMin"`
	SalaryMax        *int32      `json:"salaryMax"`
	SalaryCurrency   *string     `json:"salaryCurrency"`
	SalaryConfidence *float64    `json:"salaryConfidence"`
	SalarySource     *string     `json:"salarySource"`
}

func (q *Queries) UpdateJobSalary(ctx context.Context, arg UpdateJobSalaryParams) error {
	_, err := q.db.Exec(ctx, updateJobSalary,
		arg.ID,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.SalaryCurrency,
		arg.SalaryConfidence,
		arg.SalarySource,
	)
	return err
}

const upsertSalaryCache = `-- name: UpsertSalaryCache :exec
INSERT INTO "SalaryCache" (bucket, "salaryMin", "salaryMax", currency, source, "sampleSize")
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (bucket, currency, source) DO UPDATE SET
  "salaryMin" = EXCLUDED."salaryMin",
  "salaryMax" = EXCLUDED."salaryMax",
  "sampleSize" = "SalaryCache"."sampleSize" + 1,
  "updatedAt" = now()
`

type UpsertSalaryCacheParams struct {
	Bucket     string `json:"bucket"`
	SalaryMin  *int32 `json:"salaryMin"`
	SalaryMax  *int32 `json:"salaryMax"`
	Currency   string `json:"currency"`
	Source     string `json:"source"`
	SampleSize int32  `json:"sampleSize"`
}

func (q *Queries) UpsertSalaryCache(ctx context.Context, arg UpsertSalaryCacheParams) error {
	_, err := q.db.Exec(ctx, upsertSalaryCache,
		arg.Bucket,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.Currency,
		arg.Source,
		arg.SampleSize,
	)
	return err
}
