// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: savedsearch.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimSavedSearchRun = `-- name: ClaimSavedSearchRun :one
UPDATE "SavedSearch" SET "lastRunAt" = now()
WHERE "id" = $1
  AND "lastRunAt" IS NOT DISTINCT FROM $2::timestamp
RETURNING "id"
`

type ClaimSavedSearchRunParams struct {
	ID                pgtype.UUID      `json:"id"`
	ExpectedLastRunAt pgtype.Timestamp `json:"expected_last_run_at"`
}

// Compare-and-swap on "lastRunAt", used by the scheduler to claim a due
// search before enqueueing anything for it. Two schedulers racing on the same
// due search both pass the same expected value; row-level locking serializes
// the UPDATEs, so the second one matches no row and returns pgx.ErrNoRows
// instead of double-scraping every source.
//
// "IS NOT DISTINCT FROM" rather than "=" because a never-run search has a
// NULL "lastRunAt", and "NULL = NULL" is NULL, not true.
func (q *Queries) ClaimSavedSearchRun(ctx context.Context, arg ClaimSavedSearchRunParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimSavedSearchRun, arg.ID, arg.ExpectedLastRunAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createSavedSearch = `-- name: CreateSavedSearch :one
INSERT INTO "SavedSearch" ("name", "query", "cron", "enabled")
VALUES ($1, $2, $3, $4)
RETURNING id, name, query, cron, enabled, "lastRunAt", "createdAt"
`

type CreateSavedSearchParams struct {
	Name    string `json:"name"`
	Query   []byte `json:"query"`
	Cron    string `json:"cron"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) CreateSavedSearch(ctx context.Context, arg CreateSavedSearchParams) (SavedSearch, error) {
	row := q.db.QueryRow(ctx, createSavedSearch,
		arg.Name,
		arg.Query,
		arg.Cron,
		arg.Enabled,
	)
	var i SavedSearch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Query,
		&i.Cron,
		&i.Enabled,
		&i.LastRunAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSavedSearch = `-- name: DeleteSavedSearch :exec
DELETE FROM "SavedSearch" WHERE "id" = $1
`

func (q *Queries) DeleteSavedSearch(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSavedSearch, id)
	return err
}

const getSavedSearch = `-- name: GetSavedSearch :one
SELECT id, name, query, cron, enabled, "lastRunAt", "createdAt" FROM "SavedSearch" WHERE "id" = $1
`

func (q *Queries) GetSavedSearch(ctx context.Context, id pgtype.UUID) (SavedSearch, error) {
	row := q.db.QueryRow(ctx, getSavedSearch, id)
	var i SavedSearch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Query,
		&i.Cron,
		&i.Enabled,
		&i.LastRunAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledSavedSearches = `-- name: ListEnabledSavedSearches :many
SELECT id, name, query, cron, enabled, "lastRunAt", "createdAt" FROM "SavedSearch" WHERE "enabled" = true
`

func (q *Queries) ListEnabledSavedSearches(ctx context.Context) ([]SavedSearch, error) {
	rows, err := q.db.Query(ctx, listEnabledSavedSearches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedSearch
	for rows.Next() {
		var i SavedSearch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Query,
			&i.Cron,
			&i.Enabled,
			&i.LastRunAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedSearches = `-- name: ListSavedSearches :many
SELECT id, name, query, cron, enabled, "lastRunAt", "createdAt" FROM "SavedSearch" ORDER BY "createdAt" ASC
`

func (q *Queries) ListSavedSearches(ctx context.Context) ([]SavedSearch, error) {
	rows, err := q.db.Query(ctx, listSavedSearches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedSearch
	for rows.Next() {
		var i SavedSearch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Query,
			&i.Cron,
			&i.Enabled,
			&i.LastRunAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSavedSearchLastRun = `-- name: TouchSavedSearchLastRun :exec
UPDATE "SavedSearch" SET "lastRunAt" = now() WHERE "id" = $1
`

func (q *Queries) TouchSavedSearchLastRun(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSavedSearchLastRun, id)
	return err
}

const updateSavedSearch = `-- name: UpdateSavedSearch :one
UPDATE "SavedSearch" SET
  "name" = COALESCE($1, "name"),
  "query" = COALESCE($2, "query"),
  "cron" = COALESCE($3, "cron"),
  "enabled" = COALESCE($4, "enabled")
WHERE "id" = $5
RETURNING id, name, query, cron, enabled, "lastRunAt", "createdAt"
`

type UpdateSavedSearchParams struct {
	Name    *string     `json:"name"`
	Query   []byte      `json:"query"`
	Cron    *string     `json:"cron"`
	Enabled *bool       `json:"enabled"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSavedSearch(ctx context.Context, arg UpdateSavedSearchParams) (SavedSearch, error) {
	row := q.db.QueryRow(ctx, updateSavedSearch,
		arg.Name,
		arg.Query,
		arg.Cron,
		arg.Enabled,
		arg.ID,
	)
	var i SavedSearch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Query,
		&i.Cron,
		&i.Enabled,
		&i.LastRunAt,
		&i.CreatedAt,
	)
	return i, err
}
