// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: starstory.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStarStory = `-- name: CreateStarStory :one
INSERT INTO "StarStory" (
  "profileId", "title", "situation", "task", "action", "result", "skills", "categories"
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, "profileId", title, situation, task, action, result, skills, categories, "createdAt"
`

type CreateStarStoryParams struct {
	ProfileId  pgtype.UUID `json:"profileId"`
	Title      string      `json:"title"`
	Situation  string      `json:"situation"`
	Task       string      `json:"task"`
	Action     string      `json:"action"`
	Result     string      `json:"result"`
	Skills     []byte      `json:"skills"`
	Categories []byte      `json:"categories"`
}

func (q *Queries) CreateStarStory(ctx context.Context, arg CreateStarStoryParams) (StarStory, error) {
	row := q.db.QueryRow(ctx, createStarStory,
		arg.ProfileId,
		arg.Title,
		arg.Situation,
		arg.Task,
		arg.Action,
		arg.Result,
		arg.Skills,
		arg.Categories,
	)
	var i StarStory
	err := row.Scan(
		&i.ID,
		&i.ProfileId,
		&i.Title,
		&i.Situation,
		&i.Task,
		&i.Action,
		&i.Result,
		&i.Skills,
		&i.Categories,
		&i.CreatedAt,
	)
	return i, err
}

const listStarStoriesByProfile = `-- name: ListStarStoriesByProfile :many
SELECT id, "profileId", title, situation, task, action, result, skills, categories, "createdAt" FROM "StarStory" WHERE "profileId" = $1 ORDER BY "createdAt" ASC
`

func (q *Queries) ListStarStoriesByProfile(ctx context.Context, profileid pgtype.UUID) ([]StarStory, error) {
	rows, err := q.db.Query(ctx, listStarStoriesByProfile, profileid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StarStory
	for rows.Next() {
		var i StarStory
		if err := rows.Scan(
			&i.ID,
			&i.ProfileId,
			&i.Title,
			&i.Situation,
			&i.Task,
			&i.Action,
			&i.Result,
			&i.Skills,
			&i.Categories,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
