// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimSubscriptionRun = `-- name: ClaimSubscriptionRun :one
UPDATE "Subscription" SET "lastRunAt" = now()
WHERE "id" = $1
  AND "lastRunAt" IS NOT DISTINCT FROM $2::timestamp
RETURNING "id"
`

type ClaimSubscriptionRunParams struct {
	ID                pgtype.UUID      `json:"id"`
	ExpectedLastRunAt pgtype.Timestamp `json:"expected_last_run_at"`
}

// Compare-and-swap on "lastRunAt", the subscription twin of
// ClaimSavedSearchRun: the scheduler claims a due subscription before
// enqueueing its ingest task, so concurrent schedulers can't both scrape it.
func (q *Queries) ClaimSubscriptionRun(ctx context.Context, arg ClaimSubscriptionRunParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimSubscriptionRun, arg.ID, arg.ExpectedLastRunAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO "Subscription" ("sourceKey", "name", "url", "enabled", "cron")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, "sourceKey", name, url, enabled, "lastRunAt", "createdAt", cron
`

type CreateSubscriptionParams struct {
	SourceKey string  `json:"sourceKey"`
	Name      *string `json:"name"`
	Url       string  `json:"url"`
	Enabled   bool    `json:"enabled"`
	Cron      string  `json:"cron"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.SourceKey,
		arg.Name,
		arg.Url,
		arg.Enabled,
		arg.Cron,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.Cron,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM "Subscription" WHERE "id" = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscription, id)
	return err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, "sourceKey", name, url, enabled, "lastRunAt", "createdAt", cron FROM "Subscription" WHERE "id" = $1
`

func (q *Queries) GetSubscription(ctx context.Context, id pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.Cron,
	)
	return i, err
}

const listEnabledSubscriptions = `-- name: ListEnabledSubscriptions :many
SELECT id, "sourceKey", name, url, enabled, "lastRunAt", "createdAt", cron FROM "Subscription" WHERE "enabled" ORDER BY "createdAt" ASC
`

func (q *Queries) ListEnabledSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listEnabledSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.SourceKey,
			&i.Name,
			&i.Url,
			&i.Enabled,
			&i.LastRunAt,
			&i.CreatedAt,
			&i.Cron,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, "sourceKey", name, url, enabled, "lastRunAt", "createdAt", cron FROM "Subscription" ORDER BY "createdAt" ASC
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.SourceKey,
			&i.Name,
			&i.Url,
			&i.Enabled,
			&i.LastRunAt,
			&i.CreatedAt,
			&i.Cron,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsBySource = `-- name: ListSubscriptionsBySource :many
SELECT id, "sourceKey", name, url, enabled, "lastRunAt", "createdAt", cron FROM "Subscription" WHERE "sourceKey" = $1 ORDER BY "createdAt" ASC
`

func (q *Queries) ListSubscriptionsBySource(ctx context.Context, sourcekey string) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsBySource, sourcekey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.SourceKey,
			&i.Name,
			&i.Url,
			&i.Enabled,
			&i.LastRunAt,
			&i.CreatedAt,
			&i.Cron,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSubscriptionLastRun = `-- name: TouchSubscriptionLastRun :exec
UPDATE "Subscription" SET "lastRunAt" = now() WHERE "id" = $1
`

func (q *Queries) TouchSubscriptionLastRun(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSubscriptionLastRun, id)
	return err
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE "Subscription" SET
  "name" = COALESCE($1, "name"),
  "url" = COALESCE($2, "url"),
  "enabled" = COALESCE($3, "enabled"),
  "cron" = COALESCE($4, "cron")
WHERE "id" = $5
RETURNING id, "sourceKey", name, url, enabled, "lastRunAt", "createdAt", cron
`

type UpdateSubscriptionParams struct {
	Name    *string     `json:"name"`
	Url     *string     `json:"url"`
	Enabled *bool       `json:"enabled"`
	Cron    *string     `json:"cron"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.Name,
		arg.Url,
		arg.Enabled,
		arg.Cron,
		arg.ID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.Cron,
	)
	return i, err
}
