// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summarymodelsetting.sql

package sqlcgen

import (
	"context"
)

const getSummaryModelSetting = `-- name: GetSummaryModelSetting :one
SELECT id, "optionId", "updatedAt" FROM "SummaryModelSetting" WHERE "id" = 'default'
`

func (q *Queries) GetSummaryModelSetting(ctx context.Context) (SummaryModelSetting, error) {
	row := q.db.QueryRow(ctx, getSummaryModelSetting)
	var i SummaryModelSetting
	err := row.Scan(&i.ID, &i.OptionId, &i.UpdatedAt)
	return i, err
}

const updateSummaryModelSetting = `-- name: UpdateSummaryModelSetting :one
UPDATE "SummaryModelSetting"
SET "optionId" = $1,
    "updatedAt" = now()
WHERE "id" = 'default'
RETURNING id, "optionId", "updatedAt"
`

func (q *Queries) UpdateSummaryModelSetting(ctx context.Context, optionid string) (SummaryModelSetting, error) {
	row := q.db.QueryRow(ctx, updateSummaryModelSetting, optionid)
	var i SummaryModelSetting
	err := row.Scan(&i.ID, &i.OptionId, &i.UpdatedAt)
	return i, err
}
