// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tailoring.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abandonDraft = `-- name: AbandonDraft :exec
UPDATE tailored_drafts SET state = 'abandoned', updated_at = now() WHERE id = $1
`

// Used when a re-run supersedes the prior active draft (data-model.md
// state transitions: review -> abandoned).
func (q *Queries) AbandonDraft(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, abandonDraft, id)
	return err
}

const createDraft = `-- name: CreateDraft :one
INSERT INTO tailored_drafts (
    profile_id, job_id, vacancy_company, vacancy_title, vacancy_text,
    baseline, baseline_content_hash, state, parent_draft_id, model, activity_id
) VALUES (
    $1, $6, $7, $8, $9,
    $2, $3, $4, $10, $5, $11
)
RETURNING id, profile_id, job_id, vacancy_company, vacancy_title, vacancy_text, baseline, baseline_content_hash, state, parent_draft_id, model, activity_id, export_document_id, export_status, export_feedback, created_at, updated_at
`

type CreateDraftParams struct {
	ProfileID           pgtype.UUID `json:"profile_id"`
	Baseline            []byte      `json:"baseline"`
	BaselineContentHash string      `json:"baseline_content_hash"`
	State               string      `json:"state"`
	Model               string      `json:"model"`
	JobID               pgtype.UUID `json:"job_id"`
	VacancyCompany      *string     `json:"vacancy_company"`
	VacancyTitle        *string     `json:"vacancy_title"`
	VacancyText         *string     `json:"vacancy_text"`
	ParentDraftID       pgtype.UUID `json:"parent_draft_id"`
	ActivityID          pgtype.UUID `json:"activity_id"`
}

func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) (TailoredDraft, error) {
	row := q.db.QueryRow(ctx, createDraft,
		arg.ProfileID,
		arg.Baseline,
		arg.BaselineContentHash,
		arg.State,
		arg.Model,
		arg.JobID,
		arg.VacancyCompany,
		arg.VacancyTitle,
		arg.VacancyText,
		arg.ParentDraftID,
		arg.ActivityID,
	)
	var i TailoredDraft
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.JobID,
		&i.VacancyCompany,
		&i.VacancyTitle,
		&i.VacancyText,
		&i.Baseline,
		&i.BaselineContentHash,
		&i.State,
		&i.ParentDraftID,
		&i.Model,
		&i.ActivityID,
		&i.ExportDocumentID,
		&i.ExportStatus,
		&i.ExportFeedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProposals = `-- name: CreateProposals :many
INSERT INTO edit_proposals (
    draft_id, field_type, field_key, before_value, after_value,
    traceability, status, dropped_reason
)
SELECT
    $1::uuid, ft, fk, bv, av, tr, st, NULLIF(dr, '')
FROM (
    SELECT
        unnest($2::text[]) AS ft,
        unnest($3::text[]) AS fk,
        unnest($4::text[]) AS bv,
        unnest($5::text[]) AS av,
        unnest($6::jsonb[]) AS tr,
        unnest($7::text[]) AS st,
        unnest($8::text[]) AS dr
) AS x
RETURNING id, draft_id, field_type, field_key, before_value, after_value, traceability, status, dropped_reason, accepted_at, rejected_at, created_at
`

type CreateProposalsParams struct {
	DraftID        pgtype.UUID `json:"draft_id"`
	FieldTypes     []string    `json:"field_types"`
	FieldKeys      []string    `json:"field_keys"`
	BeforeValues   []string    `json:"before_values"`
	AfterValues    []string    `json:"after_values"`
	Traceabilities [][]byte    `json:"traceabilities"`
	Statuses       []string    `json:"statuses"`
	DroppedReasons []string    `json:"dropped_reasons"`
}

// Batch insert for one draft's proposals. Arrays are position-aligned and
// zipped via parallel unnest() calls in a subquery select list rather than
// the multi-argument unnest(a, b, ...) table form, which sqlc's analyzer
// cannot resolve (same pattern as job.sql's BulkInsertJobs); PostgreSQL
// evaluates them in lockstep either way. dropped_reason is passed as ""
// for non-dropped rows and normalized to NULL here.
func (q *Queries) CreateProposals(ctx context.Context, arg CreateProposalsParams) ([]EditProposal, error) {
	rows, err := q.db.Query(ctx, createProposals,
		arg.DraftID,
		arg.FieldTypes,
		arg.FieldKeys,
		arg.BeforeValues,
		arg.AfterValues,
		arg.Traceabilities,
		arg.Statuses,
		arg.DroppedReasons,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EditProposal
	for rows.Next() {
		var i EditProposal
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.FieldType,
			&i.FieldKey,
			&i.BeforeValue,
			&i.AfterValue,
			&i.Traceability,
			&i.Status,
			&i.DroppedReason,
			&i.AcceptedAt,
			&i.RejectedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDraft = `-- name: GetDraft :one
SELECT id, profile_id, job_id, vacancy_company, vacancy_title, vacancy_text, baseline, baseline_content_hash, state, parent_draft_id, model, activity_id, export_document_id, export_status, export_feedback, created_at, updated_at FROM tailored_drafts WHERE id = $1
`

func (q *Queries) GetDraft(ctx context.Context, id pgtype.UUID) (TailoredDraft, error) {
	row := q.db.QueryRow(ctx, getDraft, id)
	var i TailoredDraft
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.JobID,
		&i.VacancyCompany,
		&i.VacancyTitle,
		&i.VacancyText,
		&i.Baseline,
		&i.BaselineContentHash,
		&i.State,
		&i.ParentDraftID,
		&i.Model,
		&i.ActivityID,
		&i.ExportDocumentID,
		&i.ExportStatus,
		&i.ExportFeedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDraftForUpdate = `-- name: GetDraftForUpdate :one
SELECT id, profile_id, job_id, vacancy_company, vacancy_title, vacancy_text, baseline, baseline_content_hash, state, parent_draft_id, model, activity_id, export_document_id, export_status, export_feedback, created_at, updated_at FROM tailored_drafts WHERE id = $1 FOR UPDATE
`

// Row lock for the accept/reject/finalize/skill-edit mutation path: these
// read the current baseline, mutate it, and write it back, so concurrent
// requests against the same draft must serialize (research/data-model.md).
func (q *Queries) GetDraftForUpdate(ctx context.Context, id pgtype.UUID) (TailoredDraft, error) {
	row := q.db.QueryRow(ctx, getDraftForUpdate, id)
	var i TailoredDraft
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.JobID,
		&i.VacancyCompany,
		&i.VacancyTitle,
		&i.VacancyText,
		&i.Baseline,
		&i.BaselineContentHash,
		&i.State,
		&i.ParentDraftID,
		&i.Model,
		&i.ActivityID,
		&i.ExportDocumentID,
		&i.ExportStatus,
		&i.ExportFeedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDraftsByProfileJob = `-- name: ListDraftsByProfileJob :many
SELECT id, profile_id, job_id, vacancy_company, vacancy_title, vacancy_text, baseline, baseline_content_hash, state, parent_draft_id, model, activity_id, export_document_id, export_status, export_feedback, created_at, updated_at FROM tailored_drafts
WHERE profile_id = $1
  AND COALESCE(job_id, '00000000-0000-0000-0000-000000000000'::uuid)
    = COALESCE($2::uuid, '00000000-0000-0000-0000-000000000000'::uuid)
ORDER BY created_at DESC
`

type ListDraftsByProfileJobParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	JobID     pgtype.UUID `json:"job_id"`
}

// Mirrors the unique(profile_id, coalesce(job_id, '0000...')) constraint on
// tailored_drafts so the service can find the current active draft for a
// (profile, job) pair, including the ad-hoc case where job_id is NULL.
func (q *Queries) ListDraftsByProfileJob(ctx context.Context, arg ListDraftsByProfileJobParams) ([]TailoredDraft, error) {
	rows, err := q.db.Query(ctx, listDraftsByProfileJob, arg.ProfileID, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TailoredDraft
	for rows.Next() {
		var i TailoredDraft
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.JobID,
			&i.VacancyCompany,
			&i.VacancyTitle,
			&i.VacancyText,
			&i.Baseline,
			&i.BaselineContentHash,
			&i.State,
			&i.ParentDraftID,
			&i.Model,
			&i.ActivityID,
			&i.ExportDocumentID,
			&i.ExportStatus,
			&i.ExportFeedback,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingProposals = `-- name: ListPendingProposals :many
SELECT id, draft_id, field_type, field_key, before_value, after_value, traceability, status, dropped_reason, accepted_at, rejected_at, created_at FROM edit_proposals WHERE draft_id = $1 AND status = 'pending' ORDER BY created_at
`

// Backed by edit_proposals_draft_status_idx; the export path uses this to
// verify zero pending proposals remain before issuing a PDF.
func (q *Queries) ListPendingProposals(ctx context.Context, draftID pgtype.UUID) ([]EditProposal, error) {
	rows, err := q.db.Query(ctx, listPendingProposals, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EditProposal
	for rows.Next() {
		var i EditProposal
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.FieldType,
			&i.FieldKey,
			&i.BeforeValue,
			&i.AfterValue,
			&i.Traceability,
			&i.Status,
			&i.DroppedReason,
			&i.AcceptedAt,
			&i.RejectedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProposalsByDraft = `-- name: ListProposalsByDraft :many
SELECT id, draft_id, field_type, field_key, before_value, after_value, traceability, status, dropped_reason, accepted_at, rejected_at, created_at FROM edit_proposals WHERE draft_id = $1 ORDER BY created_at
`

func (q *Queries) ListProposalsByDraft(ctx context.Context, draftID pgtype.UUID) ([]EditProposal, error) {
	rows, err := q.db.Query(ctx, listProposalsByDraft, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EditProposal
	for rows.Next() {
		var i EditProposal
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.FieldType,
			&i.FieldKey,
			&i.BeforeValue,
			&i.AfterValue,
			&i.Traceability,
			&i.Status,
			&i.DroppedReason,
			&i.AcceptedAt,
			&i.RejectedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDraftExport = `-- name: SetDraftExport :exec
UPDATE tailored_drafts SET
    export_document_id = $2,
    export_status = 'fit',
    export_feedback = NULL,
    updated_at = now()
WHERE id = $1
`

type SetDraftExportParams struct {
	ID               pgtype.UUID `json:"id"`
	ExportDocumentID pgtype.UUID `json:"export_document_id"`
}

// Called on a successful single-page export: records the produced
// generated_documents row and marks the export fit; clears any stale
// blocked-export feedback from a prior attempt.
func (q *Queries) SetDraftExport(ctx context.Context, arg SetDraftExportParams) error {
	_, err := q.db.Exec(ctx, setDraftExport, arg.ID, arg.ExportDocumentID)
	return err
}

const setDraftExportStatus = `-- name: SetDraftExportStatus :exec
UPDATE tailored_drafts SET
    export_status = $2,
    export_feedback = $3,
    updated_at = now()
WHERE id = $1
`

type SetDraftExportStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	ExportStatus *string     `json:"export_status"`
	Feedback     []byte      `json:"feedback"`
}

// Used for the pending/blocked/error export states, which don't produce a
// document. feedback is only non-NULL when status = 'blocked'.
func (q *Queries) SetDraftExportStatus(ctx context.Context, arg SetDraftExportStatusParams) error {
	_, err := q.db.Exec(ctx, setDraftExportStatus, arg.ID, arg.ExportStatus, arg.Feedback)
	return err
}

const setDraftState = `-- name: SetDraftState :exec
UPDATE tailored_drafts SET state = $2, updated_at = now() WHERE id = $1
`

type SetDraftStateParams struct {
	ID    pgtype.UUID `json:"id"`
	State string      `json:"state"`
}

func (q *Queries) SetDraftState(ctx context.Context, arg SetDraftStateParams) error {
	_, err := q.db.Exec(ctx, setDraftState, arg.ID, arg.State)
	return err
}

const setProposalStatus = `-- name: SetProposalStatus :exec
UPDATE edit_proposals SET
    status = $2,
    accepted_at = $3,
    rejected_at = $4
WHERE id = $1
`

type SetProposalStatusParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	RejectedAt pgtype.Timestamptz `json:"rejected_at"`
}

// accepted_at/rejected_at are mutually exclusive: the caller passes now()
// for exactly one (matching status) and NULL for the other.
func (q *Queries) SetProposalStatus(ctx context.Context, arg SetProposalStatusParams) error {
	_, err := q.db.Exec(ctx, setProposalStatus,
		arg.ID,
		arg.Status,
		arg.AcceptedAt,
		arg.RejectedAt,
	)
	return err
}

const updateDraftBaseline = `-- name: UpdateDraftBaseline :exec
UPDATE tailored_drafts SET baseline = $2, updated_at = now() WHERE id = $1
`

type UpdateDraftBaselineParams struct {
	ID       pgtype.UUID `json:"id"`
	Baseline []byte      `json:"baseline"`
}

// Called on every proposal acceptance and every per-skill edit to an
// existing group; baseline is the full RendercvMaster snapshot re-marshaled
// by the caller.
func (q *Queries) UpdateDraftBaseline(ctx context.Context, arg UpdateDraftBaselineParams) error {
	_, err := q.db.Exec(ctx, updateDraftBaseline, arg.ID, arg.Baseline)
	return err
}
