package config

var defaults = map[string]any{
	"PORT":                           3000,
	"REDIS_URL":                      "redis://localhost:6379",
	"OLLAMA_URL":                     "http://localhost:11434",
	"LLM_MODEL":                      "qwen2.5:14b",
	"EMBED_MODEL":                    "nomic-embed-text",
	"EMBED_DIMS":                     768,
	"MATCH_SIMILARITY_THRESHOLD":     0.35,
	"KEYWORD_REPHRASE_CACHE_TTL_SEC": 900,
	"ADZUNA_COUNTRY":                 "gb",
	"DJINNI_DETAIL_DELAY_MS":         1500,
	"WORKUA_DETAIL_DELAY_MS":         2000,
	"DOCUMENTS_DIR":                  "./data/documents",
	"MINIO_BUCKET":                   "documents",
	"MINIO_USE_SSL":                  false,
	"RESUME_GROUNDING_LEVEL":         "moderate",
	"RENDERCV_BIN":                   "rendercv",
	"LINKEDIN_SCRAPE_ENABLED":        false,
	"COOLING_OFF_THRESHOLD":          3,
	"COOLING_OFF_BASE_DURATION":      "1h",
	"CHEAP_RUNG_RETEST_INTERVAL":     "24h",
	"DJINNI_RATE_OVERRIDE_RPS":       0.5,

	"AI_CONCURRENCY_CLOUD":        3,
	"AI_CONCURRENCY_LOCAL":        1,
	"INGEST_CONCURRENCY":          2,
	"INGEST_PERSIST_CHUNK_SIZE":   500,
	"ENRICH_CONCURRENCY":          1,
	"AI_TASK_TIMEOUT_MATCH":       "5m",
	"AI_TASK_TIMEOUT_GENERATE":    "15m",
	"AI_TASK_TIMEOUT_SALARY":      "5m",
	"AI_TASK_TIMEOUT_GHOST":       "5m",
	"AI_TASK_TIMEOUT_ENRICH":      "10m",
	"AI_TASK_TIMEOUT_INGEST":      "30m",
	"ACTIVITY_HEARTBEAT_INTERVAL": "30s",
	"ACTIVITY_STALE_AFTER":        "2m",
	"ACTIVITY_SWEEP_INTERVAL":     "1m",
	"ACTIVITY_QUEUED_GRACE":       "30m",
	"OLLAMA_KEEP_ALIVE":           "30m",
	"LLM_MAX_IDLE_CONNS_PER_HOST": 4,

	"DB_MAX_CONNS":           0,
	"DB_MIN_CONNS":           2,
	"DB_MAX_CONN_LIFETIME":   "1h",
	"DB_MAX_CONN_IDLE_TIME":  "30m",
	"DB_ACQUIRE_TIMEOUT":     "5s",
	"DB_SERVER_MAX_CONNS":    100,
	"DB_INTERACTIVE_RESERVE": 8,
}

var optionalKeys = []string{
	"DATABASE_URL", "OLLAMA_KEY", "LLM_MODEL_MATCH", "LLM_MODEL_GENERATION",
	"LLM_MODEL_REPHRASE", "LLM_MODEL_GHOST",
	"EMBED_URL", "CONFIG_ENCRYPTION_KEY",
	"ADZUNA_APP_ID", "ADZUNA_APP_KEY",
	"JOBLEADS_EMAIL", "JOBLEADS_PASSWORD",
	"DJINNI_EMAIL", "DJINNI_PASSWORD", "RESUME_MASTER_PATH",
	"JOOBLE_API_KEY", "FLARESOLVERR_URL", "JOBSPY_URL",
	"MINIO_ENDPOINT", "MINIO_ACCESS_KEY", "MINIO_SECRET_KEY",
	"LEVELS_FYI_CSV", "SALARY_FLOOR_USD",
	"GATEWAY_URL", "LITELLM_MASTER_KEY",
	"BROWSER_IDENTITY_VERSION",
}
