// Code generated by tygo. DO NOT EDIT.

//////////
// source: activity.go

export interface ActivityRunDto {
  id: string;
  op: string;
  state: string;
  label: string;
  step?: string;
  jobId?: string;
  sourceKey?: string;
  refId?: string;
  error?: string;
  meta: { [key: string]: any};
  createdAt: string;
  startedAt?: string;
  finishedAt?: string;
  elapsedMs?: number /* int64 */;
}
export interface ActivityListResponse {
  active: ActivityRunDto[];
  recent: ActivityRunDto[];
}
export interface FreshMatchNotificationDto {
  id: string;
  jobId: string;
  matchResultId: string;
  fresh: boolean;
  seen: boolean;
  createdAt: string;
  jobTitle?: string;
  company?: string;
  matchScore?: number /* int32 */;
}

//////////
// source: analysis.go

export interface KeywordDiffTermDto {
  term: string;
  canonical: string;
  polarity: string;
  normalized: string;
  matchType?: string;
}
export interface KeywordDiffMetadataDto {
  totalRequired: number /* int */;
  totalPreferred: number /* int */;
  matchedRequired: number /* int */;
  matchedPreferred: number /* int */;
  coveragePct: number /* float64 */;
}
export interface KeywordRephraseSuggestionDto {
  term: string;
  canonical: string;
  rephrase?: string;
  sourceBullet?: string;
  reason?: string;
}
export interface KeywordDiffDto {
  jobId: string;
  matched: KeywordDiffTermDto[];
  missingRequired: KeywordDiffTermDto[];
  missingPreferred: KeywordDiffTermDto[];
  metadata: KeywordDiffMetadataDto;
  suggestions: KeywordRephraseSuggestionDto[];
}
export interface FitGapEvidenceDto {
  sourceEntry: string;
  sourceBullet: string;
  proximity: string;
  rephrase: string;
}
export interface FitGapItemDto {
  term: string;
  polarity: string;
  adjacentEvidence: FitGapEvidenceDto[];
  noAdjacentEvidence: boolean;
}
export interface FitGapAssessmentDto {
  jobId: string;
  totalMustHaves: number /* int */;
  failedMustHaves: number /* int */;
  coveragePct: number /* float64 */;
  gaps: FitGapItemDto[];
}
export interface GhostSignalBreakdownDto {
  repostCount: number /* int */;
  daysOpen?: number /* int */;
  crossBoardCount?: number /* int */;
  alwaysHiringCount?: number /* int */;
  confidence: number /* float64 */;
  explanation: string;
  topSignals?: string[];
  notes: { [key: string]: string};
}
export interface JobSignalDto {
  id: string;
  jobId: string;
  kind: string;
  score: number /* int */;
  model: string;
  createdAt: string;
  signals: GhostSignalBreakdownDto;
}
export interface StoryMappingDto {
  storyId: string;
  storyTitle: string;
  relevanceScore: number /* float64 */;
  matchedSkills: string[];
  excerpt: string;
}
export interface InterviewQuestionDto {
  id: string;
  text: string;
  category: string;
  source: string;
  sourceExcerpt: string;
  mappedStories: StoryMappingDto[];
}
export interface CompanyNewsItemDto {
  kind: string;
  label: string;
  value: string;
  source: string;
  fetchedAt: string;
}
export interface KeywordGapSummaryDto {
  missingRequired: string[];
  missingPreferred: string[];
  coveragePct: number /* float64 */;
  gapAwarenessTips: string[];
}
export interface InterviewPrepMetadataDto {
  totalQuestions: number /* int */;
  coveredQuestions: number /* int */;
  uncoveredQuestions: number /* int */;
  staleNews: boolean;
}
export interface InterviewPrepPackDto {
  jobId: string;
  generatedAt: string;
  questions: InterviewQuestionDto[];
  companyNews: CompanyNewsItemDto[];
  keywordGap: KeywordGapSummaryDto;
  metadata: InterviewPrepMetadataDto;
}

//////////
// source: documents.go

export interface GeneratedDocumentDto {
  id: string;
  jobId?: string;
  type: string;
  version: number /* int */;
  content: any;
  pdfPath?: string;
  model: string;
  company?: string;
  title?: string;
  vacancy?: string;
  createdAt: string;
}
export interface ApplicationDto {
  id: string;
  jobId: string;
  status: ApplicationStatus;
  notes?: string;
  appliedAt?: string;
  events: ApplicationEvent[];
  updatedAt: string;
  job?: JobDto;
}
export interface ApplicationEvent {
  status: string;
  at: string;
}
export interface ApplicationOutcomeDto {
  id: string;
  applicationId: string;
  eventType: OutcomeEventType;
  occurredAt: string;
  recordedAt: string;
  note?: string;
}
export interface StatsDto {
  jobsTotal: number /* int64 */;
  jobsLast24h: number /* int64 */;
  highFit: number /* int64 */;
  pipeline: { [key: string]: number /* int64 */};
  recentRuns: SourceRunDto[];
}

//////////
// source: dto.go

export type SourceKind = string;
export const SourceKindAPI: SourceKind = "api";
export const SourceKindScrape: SourceKind = "scrape";
export const SourceKindSidecar: SourceKind = "sidecar";
export type ApplicationStatus = string;
export const StatusFound: ApplicationStatus = "found";
export const StatusShortlisted: ApplicationStatus = "shortlisted";
export const StatusDocsGenerated: ApplicationStatus = "docs_generated";
export const StatusApplied: ApplicationStatus = "applied";
export const StatusInterview: ApplicationStatus = "interview";
export const StatusOffer: ApplicationStatus = "offer";
export const StatusRejected: ApplicationStatus = "rejected";
export type OutcomeEventType = string;
export const OutcomeApplied: OutcomeEventType = "applied";
export const OutcomeViewed: OutcomeEventType = "viewed";
export const OutcomeScreen: OutcomeEventType = "screen";
export const OutcomeOffer: OutcomeEventType = "offer";
export const OutcomeRejected: OutcomeEventType = "rejected";
export type DocumentType = string;
export const DocumentTypeResume: DocumentType = "resume";
export const DocumentTypeCoverLetter: DocumentType = "cover_letter";

//////////
// source: intel.go

export interface CompanyIntelDto {
  companyName: string;
  website?: string;
  funding?: string;
  layoffs?: string;
  glassdoorRating?: number /* float64 */;
  headcount?: string;
  techStack?: string;
  fetchedAt: string;
  error?: string;
}
export interface JobContactDto {
  id: string;
  name: string;
  title?: string;
  linkedInUrl?: string;
  email?: string;
  phone?: string;
  source: string;
  confidence: number /* float64 */;
  fetchedAt: string;
}
export interface ReferralContactDto {
  id: string;
  name: string;
  email?: string;
  company?: string;
  role?: string;
  linkedInUrl?: string;
  gitHubUsername?: string;
}
export interface ReferralPathDto {
  path: ReferralContactDto[];
  score: number /* float64 */;
  length: number /* int */;
}
export interface ContactImportResultDto {
  imported: number /* int */;
  skipped: number /* int */;
  total: number /* int */;
}
export interface GithubSyncResultDto {
  contact: ReferralContactDto;
  followersScanned: number /* int */;
  followingScanned: number /* int */;
  connectionsMade: number /* int */;
}
export interface GroundingTraceDto {
  claim: string;
  signalKind: string;
  signalValue: string;
}
export interface OutreachDraftDto {
  jobId: string;
  contactId?: string;
  contactName?: string;
  tone: string;
  text: string;
  groundingTraces: GroundingTraceDto[];
  generatedAt: string;
}
export interface OutreachToneOptionDto {
  value: string;
  label: string;
  default: boolean;
}

//////////
// source: jobs.go

export interface NormalizedJob {
  sourceKey: string;
  externalId?: string;
  title: string;
  company: string;
  location?: string;
  remote: boolean;
  salaryRaw?: string;
  url: string;
  description: string;
  postedAt?: string;
  raw: any;
}
export interface SearchQuery {
  keywords: string;
  location?: string;
  remote?: boolean;
  salaryMin?: number /* float64 */;
  country?: string;
  sources?: string[];
  subscriptionUrl?: string;
}
export interface JobDto {
  id: string;
  dedupeKey: string;
  sourceKey: string;
  subscriptionId?: string;
  title: string;
  company: string;
  location?: string;
  remote: boolean;
  salaryRaw?: string;
  url: string;
  description: string;
  descriptionHtml?: string;
  postedAt?: string;
  ingestedAt: string;
  status: string;
  matchResult?: MatchResultDto;
  documents?: GeneratedDocumentDto[];
  application?: ApplicationDto;
  salaryMin?: number /* int */;
  salaryMax?: number /* int */;
  salaryCurrency?: string;
  salaryConfidence?: number /* float64 */;
  salarySource?: string;
  salaryBelowFloor: boolean;
  ghostSignal?: JobSignalDto;
}
export interface JobListResponse {
  items: JobDto[];
  total: number /* int64 */;
  page: number /* int */;
  pageSize: number /* int */;
}
export interface MatchResultDto {
  id: string;
  jobId: string;
  similarity: number /* float64 */;
  score?: number /* int */;
  matchedSkills?: string[];
  missingSkills?: string[];
  summary?: string;
  redFlags?: string[];
  model: string;
  createdAt: string;
}
export interface JobSourceDto {
  id: string;
  key: string;
  kind: SourceKind;
  enabled: boolean;
  healthy: boolean;
  config: { [key: string]: any};
}
export interface SavedSearchDto {
  id: string;
  name: string;
  query: SearchQuery;
  cron: string;
  enabled: boolean;
  lastRunAt?: string;
}
export interface SubscriptionDto {
  id: string;
  sourceKey: string;
  name?: string;
  url: string;
  enabled: boolean;
  cron: string;
  lastRunAt?: string;
}
export interface SourceRunDto {
  id: string;
  sourceKey: string;
  searchId?: string;
  startedAt: string;
  finishedAt?: string;
  ok?: boolean;
  found: number /* int */;
  new: number /* int */;
  error?: string;
  verdict?: string;
  blockedCount: number /* int */;
  blockReason?: string;
}
export interface RunVerdictDto {
  verdict: string;
  blockedCount: number /* int */;
  blockReason?: string;
}
export interface HostRetrievalStatusDto {
  host: string;
  identityVersion: string;
  currentRung: string;
  lastBlockAt?: string;
  lastBlockReason?: string;
  coolingOffUntil?: string;
  budgetUsed: number /* int */;
  budgetLimit: number /* int */;
  budgetResetsAt: string;
  crawlDelaySeconds?: number /* int */;
}
export interface EmployerBoardDto {
  id: string;
  vendor: string;
  employerIdentifier: string;
  displayName: string;
  addedVia: string;
  enabled: boolean;
  lastSuccessAt?: string;
  lastPostingCount: number /* int */;
  stale: boolean;
}
export interface BoardCandidateDto {
  id: string;
  vendor: string;
  employerIdentifier: string;
  displayName: string;
  inferredFromJobId?: string;
  state: string;
}
export interface GenerateRequestDto {
  type: DocumentType;
  profileId?: string;
}

//////////
// source: postage.go

export type PostAgeBucketState = string;
export const PostAgeStateObserved: PostAgeBucketState = "observed";
export const PostAgeStatePrior: PostAgeBucketState = "prior";
export const PostAgeStateInsufficient: PostAgeBucketState = "insufficient";
export interface PostAgeBucketDto {
  bucket: string;
  n: number /* int32 */;
  responses: number /* int32 */;
  rate?: number /* float64 */;
  state: PostAgeBucketState;
}
export interface PostAgeResponseDto {
  buckets: PostAgeBucketDto[];
  totalApps: number /* int32 */;
  globalState: PostAgeBucketState;
  priorRate: number /* float64 */;
  priorLabel: string;
  thresholdMsg?: string;
}

//////////
// source: profiles.go

export interface ResumeLocation {
  city?: string;
  countryCode?: string;
  region?: string;
}
export interface ResumeProfile {
  network?: string;
  username?: string;
  url?: string;
}
export interface ResumeBasics {
  name?: string;
  label?: string;
  email?: string;
  phone?: string;
  url?: string;
  summary?: string;
  location?: ResumeLocation;
  profiles?: ResumeProfile[];
}
export interface ResumeWork {
  name: string;
  position?: string;
  url?: string;
  startDate?: string;
  endDate?: string;
  summary?: string;
  highlights?: string[];
}
export interface ResumeEducation {
  institution: string;
  area?: string;
  studyType?: string;
  startDate?: string;
  endDate?: string;
}
export interface ResumeSkill {
  name: string;
  level?: string;
  keywords?: string[];
}
export interface ResumeProject {
  name: string;
  description?: string;
  url?: string;
  keywords?: string[];
  highlights?: string[];
}
export interface ResumeLanguage {
  language?: string;
  fluency?: string;
}
export interface ResumeCertificate {
  name?: string;
  issuer?: string;
  date?: string;
}
export interface JsonResume {
  basics?: ResumeBasics;
  work?: ResumeWork[];
  education?: ResumeEducation[];
  skills?: ResumeSkill[];
  projects?: ResumeProject[];
  languages?: ResumeLanguage[];
  certificates?: ResumeCertificate[];
}
export interface RendercvSummaryExperience {
  company: string;
  highlightCount: number /* int */;
}
export interface RendercvSummary {
  name: string;
  headline: string;
  skillGroups: string[];
  experience: RendercvSummaryExperience[];
}
export interface ProfileDto {
  id: string;
  name: string;
  hasConfig: boolean;
  rendercvConfig?: RendercvSummary;
  rendercvFull?: any;
  extraNotes?: string;
  updatedAt: string;
}
export interface ExtProfileDto {
  fullName: string;
  email: string;
  phone: string;
  location: string;
  headline: string;
  skills: string[];
  workHistory: ExtWorkEntry[];
  education: ExtEducation[];
  links: ExtLink[];
}
export interface ExtWorkEntry {
  employer: string;
  role: string;
  startDate: string;
  endDate?: string;
  current: boolean;
  description: string;
}
export interface ExtEducation {
  institution: string;
  degree: string;
  startDate: string;
  endDate: string;
}
export interface ExtLink {
  url: string;
  label: string;
}

//////////
// source: resume.go

/**
 * EntryType is one of the 9 canonical RenderCV entry types. A Section holds
 * entries of exactly one EntryType (see spec 009 data-model.md).
 */
export type EntryType = string;
export const EntryEducation: EntryType = "education";
export const EntryExperience: EntryType = "experience";
export const EntryNormal: EntryType = "normal";
export const EntryPublication: EntryType = "publication";
export const EntryOneLine: EntryType = "one_line";
export const EntryBullet: EntryType = "bullet";
export const EntryNumbered: EntryType = "numbered";
export const EntryReversedNumbered: EntryType = "reversed_numbered";
export const EntryText: EntryType = "text";
/**
 * SocialNetwork mirrors RenderCV's cv.social_networks entries.
 */
export interface SocialNetwork {
  network: string;
  username: string;
}
/**
 * CustomConnection mirrors RenderCV's cv.custom_connections entries: a
 * display label (placeholder), a link, and a fontawesome icon name — used
 * for networks not in RenderCV's built-in social_networks list (e.g.
 * Telegram in some configs).
 */
export interface CustomConnection {
  placeholder: string;
  url: string;
  icon?: string;
}
/**
 * Entry is a tagged-union-by-convention struct: which fields are meaningful
 * depends on the parent Section's EntryType. Represented as one flat struct
 * (rather than a Go interface) so it tygo-generates into a single, simple TS
 * type the dashboard can pattern-match on `entryType`.
 */
export interface Entry {
  /**
   * education
   */
  institution?: string;
  area?: string;
  degree?: string;
  /**
   * experience
   */
  company?: string;
  position?: string;
  /**
   * normal (projects)
   */
  name?: string;
  /**
   * publication
   */
  title?: string;
  authors?: string[];
  doi?: string;
  journal?: string;
  /**
   * publication, normal
   */
  url?: string;
  /**
   * one_line (skills)
   */
  label?: string;
  details?: string;
  /**
   * bullet
   */
  bullet?: string;
  /**
   * numbered
   */
  number?: string;
  /**
   * reversed_numbered — field is named "reversed_number" in RenderCV YAML;
   * its value is a talk title/description, not a number (RenderCV naming
   * quirk, preserved as-is for round-trip fidelity).
   */
  reversedNumber?: string;
  /**
   * text
   */
  text?: string;
  /**
   * education, experience, normal, publication
   */
  date?: string;
  /**
   * education, experience, normal
   */
  startDate?: string;
  endDate?: string;
  location?: string;
  /**
   * education, experience, normal, publication
   */
  summary?: string;
  /**
   * education, experience, normal
   */
  highlights?: string[];
  /**
   * Unrecognized carries any fields present in imported data that don't map
   * to a field above, so nothing is silently dropped (FR-009).
   */
  unrecognized?: { [key: string]: any};
}
/**
 * Section is a named, ordered group of same-typed Entries (FR-005, FR-006).
 */
export interface Section {
  name: string;
  entryType: EntryType;
  entries: Entry[];
}
/**
 * Resume is the top-level structured, editable view of a Profile's resume
 * content (maps to cv.* in the RendercvMaster, minus design/locale/settings,
 * which stay out of scope for this feature).
 */
export interface Resume {
  name: string;
  headline?: string;
  location?: string;
  email?: string;
  phone?: string;
  website?: string;
  photo?: string;
  socialNetworks?: SocialNetwork[];
  customConnections?: CustomConnection[];
  sections: Section[];
  /**
   * Unrecognized carries any top-level cv.* keys not modeled above.
   */
  unrecognized?: { [key: string]: any};
}
/**
 * ResumeDto wraps Resume for the GET/PUT /profiles/{id}/resume endpoints.
 */
export interface ResumeDto {
  resume: Resume;
}

//////////
// source: settings.go

export interface LlmTaskSettingDto {
  taskKey: string;
  provider: string;
  model: string;
}
export interface LlmSettingsResponseDto {
  credentialConfigured: boolean;
  openRouterCredentialConfigured: boolean;
  tasks: LlmTaskSettingDto[];
}
export interface UpdateLlmSettingsRequestDto {
  tasks: LlmTaskSettingDto[];
}
export interface AiFeatureSettingDto {
  feature: string;
  enabled: boolean;
  threshold: number /* int */;
}
export interface CerebrasModelDto {
  id: string;
  label: string;
  isDefault: boolean;
}
export interface OpenRouterModelDto {
  id: string;
  label: string;
  isDefault: boolean;
}
export interface LlmModelsResponseDto {
  cerebras: CerebrasModelDto[];
  openrouter: OpenRouterModelDto[];
}
