// Code generated by tygo. DO NOT EDIT.

//////////
// source: job.go

export const SourceKindAPI = "api";
export const SourceKindScrape = "scrape";
export const SourceKindSidecar = "sidecar";
/**
 * SourceKindManual backs hand-entered vacancies on hosts no adapter reads.
 * It is never crawled — its adapter's Search fails permanently (041 D4).
 */
export const SourceKindManual = "manual";
export type SourceKind = typeof SourceKindAPI | typeof SourceKindScrape | typeof SourceKindSidecar | typeof SourceKindManual;
export interface NormalizedJob {
  sourceKey: string;
  externalId?: string;
  title: string;
  company: string;
  location?: string;
  remote: boolean;
  salaryRaw?: string;
  url: string;
  description: string;
  postedAt?: string;
  raw: any;
  experienceLevel?: string;
  experienceMinYears?: number /* int */;
  englishLevel?: string;
  salaryEstimateRaw?: string;
  salaryEstimateMin?: number /* int */;
  salaryEstimateMax?: number /* int */;
  salaryEstimateCurrency?: string;
}
export interface SearchQuery {
  keywords: string;
  location?: string;
  remote?: boolean;
  salaryMin?: number /* float64 */;
  country?: string;
  sources?: string[];
  subscriptionUrl?: string;
}
export interface JobSourceDto {
  id: string;
  key: string;
  kind: SourceKind;
  enabled: boolean;
  healthy: boolean;
  config: { [key: string]: any};
}
