// Code generated by tygo. DO NOT EDIT.

//////////
// source: dto.go
/*
Package dto defines the wire-format structs served by the HTTP API.
These are the Go source of truth for tygo-generated dashboard TypeScript
types; field names/JSON tags must match packages/shared/src/index.ts
exactly (field-for-field) so the existing React dashboard needs zero changes.
*/

export type SourceKind = string;
export const SourceKindAPI: SourceKind = "api";
export const SourceKindScrape: SourceKind = "scrape";
export const SourceKindSidecar: SourceKind = "sidecar";
export type ApplicationStatus = string;
export const StatusFound: ApplicationStatus = "found";
export const StatusShortlisted: ApplicationStatus = "shortlisted";
export const StatusDocsGenerated: ApplicationStatus = "docs_generated";
export const StatusApplied: ApplicationStatus = "applied";
export const StatusInterview: ApplicationStatus = "interview";
export const StatusOffer: ApplicationStatus = "offer";
export const StatusRejected: ApplicationStatus = "rejected";
export type DocumentType = string;
export const DocumentTypeResume: DocumentType = "resume";
export const DocumentTypeCoverLetter: DocumentType = "cover_letter";
/**
 * NormalizedJob is the canonical job shape every source adapter must produce.
 */
export interface NormalizedJob {
  sourceKey: string;
  externalId?: string;
  title: string;
  company: string;
  location?: string;
  remote: boolean;
  salaryRaw?: string;
  url: string;
  description: string;
  postedAt?: string; // ISO date
  raw: any;
}
/**
 * SearchQuery is the query shape a saved search stores and adapters receive.
 */
export interface SearchQuery {
  keywords: string;
  location?: string;
  remote?: boolean;
  salaryMin?: number /* float64 */;
  country?: string;
  sources?: string[];
  site?: string; // 'linkedin' | 'indeed' | 'glassdoor'
  /**
   * SubscriptionURL, when set, tells an adapter to scrape this saved-filter
   * URL (e.g. a djinni subs page) instead of running a keyword search.
   */
  subscriptionUrl?: string;
}
export interface ResumeLocation {
  city?: string;
  countryCode?: string;
  region?: string;
}
export interface ResumeProfile {
  network?: string;
  username?: string;
  url?: string;
}
export interface ResumeBasics {
  name?: string;
  label?: string;
  email?: string;
  phone?: string;
  url?: string;
  summary?: string;
  location?: ResumeLocation;
  profiles?: ResumeProfile[];
}
export interface ResumeWork {
  name: string;
  position?: string;
  url?: string;
  startDate?: string;
  endDate?: string;
  summary?: string;
  highlights?: string[];
}
export interface ResumeEducation {
  institution: string;
  area?: string;
  studyType?: string;
  startDate?: string;
  endDate?: string;
}
export interface ResumeSkill {
  name: string;
  level?: string;
  keywords?: string[];
}
export interface ResumeProject {
  name: string;
  description?: string;
  url?: string;
  keywords?: string[];
  highlights?: string[];
}
export interface ResumeLanguage {
  language?: string;
  fluency?: string;
}
export interface ResumeCertificate {
  name?: string;
  issuer?: string;
  date?: string;
}
export interface JsonResume {
  basics?: ResumeBasics;
  work?: ResumeWork[];
  education?: ResumeEducation[];
  skills?: ResumeSkill[];
  projects?: ResumeProject[];
  languages?: ResumeLanguage[];
  certificates?: ResumeCertificate[];
}
export interface MatchResultDto {
  id: string;
  jobId: string;
  similarity: number /* float64 */;
  score?: number /* int */;
  matchedSkills?: string[];
  missingSkills?: string[];
  summary?: string;
  redFlags?: string[];
  model: string;
  createdAt: string;
}
export interface JobDto {
  id: string;
  dedupeKey: string;
  sourceKey: string;
  title: string;
  company: string;
  location?: string;
  remote: boolean;
  salaryRaw?: string;
  url: string;
  description: string;
  descriptionHtml?: string;
  postedAt?: string;
  ingestedAt: string;
  status: string; // ApplicationStatus | 'hidden'
  matchResult?: MatchResultDto;
  documents?: GeneratedDocumentDto[];
  application?: ApplicationDto;
}
export interface JobListResponse {
  items: JobDto[];
  total: number /* int64 */;
  page: number /* int */;
  pageSize: number /* int */;
}
export interface GeneratedDocumentDto {
  id: string;
  jobId?: string;
  type: string;
  version: number /* int */;
  content: any;
  pdfPath?: string;
  model: string;
  company?: string;
  title?: string;
  vacancy?: string;
  createdAt: string;
}
export interface RendercvSummaryExperience {
  company: string;
  highlightCount: number /* int */;
}
export interface RendercvSummary {
  name: string;
  headline: string;
  skillGroups: string[];
  experience: RendercvSummaryExperience[];
}
export interface ProfileDto {
  id: string;
  name: string;
  hasConfig: boolean;
  rendercvConfig?: RendercvSummary;
  extraNotes?: string;
  updatedAt: string;
}
export interface JobSourceDto {
  id: string;
  key: string;
  kind: SourceKind;
  enabled: boolean;
  healthy: boolean;
  config: { [key: string]: any};
}
export interface SavedSearchDto {
  id: string;
  name: string;
  query: SearchQuery;
  cron: string;
  enabled: boolean;
  lastRunAt?: string;
}
/**
 * SubscriptionDto is a URL-based subscription attached to a job source: a
 * saved-filter URL on the site itself (e.g. a djinni subs page or a dou
 * category listing). Fetching the URL is deferred; this is CRUD + enable only.
 */
export interface SubscriptionDto {
  id: string;
  sourceKey: string;
  name?: string;
  url: string;
  enabled: boolean;
  lastRunAt?: string;
}
export interface SourceRunDto {
  id: string;
  sourceKey: string;
  searchId?: string;
  startedAt: string;
  finishedAt?: string;
  ok?: boolean;
  found: number /* int */;
  new: number /* int */;
  error?: string;
}
export interface ApplicationEvent {
  status: string;
  at: string;
}
export interface ApplicationDto {
  id: string;
  jobId: string;
  status: ApplicationStatus;
  notes?: string;
  appliedAt?: string;
  events: ApplicationEvent[];
  updatedAt: string;
  job?: JobDto;
}
export interface StatsDto {
  jobsTotal: number /* int64 */;
  jobsLast24h: number /* int64 */;
  highFit: number /* int64 */;
  pipeline: { [key: string]: number /* int64 */};
  recentRuns: SourceRunDto[];
}
export interface GenerateRequestDto {
  type: DocumentType;
  profileId?: string;
}
/**
 * ActivityRunDto is one row of under-the-hood async task activity (ingest,
 * match, generate, enrich), live progress and recent history alike.
 */
export interface ActivityRunDto {
  id: string;
  op: string;
  state: string;
  label: string;
  step?: string;
  jobId?: string;
  sourceKey?: string;
  refId?: string;
  error?: string;
  meta: { [key: string]: any};
  createdAt: string;
  startedAt?: string;
  finishedAt?: string;
  elapsedMs?: number /* int64 */;
}
export interface ActivityListResponse {
  active: ActivityRunDto[];
  recent: ActivityRunDto[];
}
