// Code generated by tygo. DO NOT EDIT.

//////////
// source: detail.go

/**
 * WorkMode is how a job is worked, normalised away from any one site's wording.
 */
export const WorkModeRemote = "remote";
export const WorkModeOffice = "office";
export const WorkModeHybrid = "hybrid";
export const WorkModeUnknown = "unknown";
export type WorkMode = typeof WorkModeRemote | typeof WorkModeOffice | typeof WorkModeHybrid | typeof WorkModeUnknown;
/**
 * LocationScope reserves the sentinel boards use for "no country restriction"
 * so it is never mistaken for a place name.
 */
export type LocationScope = string;
export const LocationWorldwide: LocationScope = "worldwide";
export const LocationCountries: LocationScope = "countries";
export const LocationUnknown: LocationScope = "unknown";
/**
 * LanguageLevel is CEFR. Boards that print their own wording — "Native",
 * "Upper Intermediate" — are mapped onto it by their adapter.
 */
export type LanguageLevel = string;
export const LevelA1: LanguageLevel = "A1";
export const LevelA2: LanguageLevel = "A2";
export const LevelB1: LanguageLevel = "B1";
export const LevelB2: LanguageLevel = "B2";
export const LevelC1: LanguageLevel = "C1";
export const LevelC2: LanguageLevel = "C2";
export const LevelUnknown: LanguageLevel = "";
/**
 * SalaryTier is a band published instead of a range: some boards rank a job
 * against their own market data rather than showing numbers.
 */
export type SalaryTier = string;
export const TierBelowAverage: SalaryTier = "below_average";
export const TierAverage: SalaryTier = "average";
export const TierAboveAverage: SalaryTier = "above_average";
export const TierTopRange: SalaryTier = "top_range";
export const TierUnknown: SalaryTier = "";
/**
 * LanguageReq is one language requirement: "English B2 - Upper Intermediate"
 * becomes {English, B2}.
 */
export interface LanguageReq {
  language: string;
  level: LanguageLevel;
}
/**
 * Company is who is hiring.
 */
export interface Company {
  name: string;
  url?: string;
  site?: string;
  logoUrl?: string;
  /**
   * Type is how the company is organised — product, outstaff, agency.
   */
  type?: string;
  /**
   * Domain is the board's label for the field it works in ("DefTech");
   * Industry is the machine-readable spelling ("miltech"). They differ often
   * enough to be worth keeping apart.
   */
  domain?: string;
  industry?: string;
}
/**
 * Salary is what the posting says about pay. A board may publish an exact
 * range, a band relative to its own market data, or nothing at all.
 */
export interface Salary {
  min?: number /* int */;
  max?: number /* int */;
  currency?: string;
  /**
   * Public reports whether the employer itself published the range, as
   * opposed to the board estimating one.
   */
  public: boolean;
  /**
   * Raw is the employer's own salary text, where it published one.
   */
  raw?: string;
  /**
   * Tier is the board's band where it shows one instead of numbers.
   */
  tier?: SalaryTier;
  tierLabel?: string;
  /**
   * Estimate is the board's own suggested range for similar jobs.
   */
  estimate?: string;
}
/**
 * Location is where the work happens and who may do it.
 */
export interface Location {
  /**
   * Mode is the first mode the posting lists; Modes is every mode it
   * accepts. A job open to office, remote and hybrid at once is common.
   */
  mode: WorkMode;
  modes?: WorkMode[];
  scope: LocationScope;
  /**
   * Countries are where candidates may be based. Entries may be regions
   * rather than countries: "Countries of Europe" is one value boards use.
   */
  countries?: string[];
  /**
   * Offices are where the employer sits, stated separately from where
   * candidates may live.
   */
  offices?: string[];
}
/**
 * SkillReq is one named skill with the experience the posting asks for it —
 * "Azure, 3 years" — which can be shorter than the overall requirement.
 */
export interface SkillReq {
  name: string;
  years?: number /* float64 */;
}
/**
 * Requirements is what the posting asks of a candidate.
 */
export interface Requirements {
  /**
   * ExperienceYears is fractional where the posting is: a board stating 18
   * months means 1.5 years.
   */
  experienceYears?: number /* float64 */;
  /**
   * MinimumExperienceYears is the floor the employer will still consider —
   * "Considering with 4 years" under a 5-year requirement. Where the posting
   * names no lower bound it equals the requirement.
   */
  minimumExperienceYears?: number /* float64 */;
  /**
   * Skills are the named technologies and the experience asked for each.
   */
  skills?: SkillReq[];
  languages?: LanguageReq[];
  hasTestTask: boolean;
}
/**
 * Timeline is every date on the posting, as Unix seconds. Zero means the
 * posting does not state it.
 */
export interface Timeline {
  /**
   * PostedAt is when the posting last went live; PublishedAt is when it
   * first did. They differ on a posting that has been renewed.
   */
  postedAt?: number /* int64 */;
  publishedAt?: number /* int64 */;
  updatedAt?: number /* int64 */;
  validThru?: number /* int64 */;
  /**
   * ScrapedAt is when this record was read, which dates everything above it:
   * view counts and "last responded" are only true as of this moment.
   */
  scrapedAt?: number /* int64 */;
}
/**
 * Activity is how much competition the posting has drawn and how reliably the
 * employer answers. Absent on a posting too fresh to have any.
 */
export interface Activity {
  views?: number /* int */;
  applications?: number /* int */;
  /**
   * ResponseRate is the board's own verdict on the recruiter — "Low".
   */
  responseRate?: string;
  /**
   * LastRespondedAt is Unix seconds; zero when never or not stated.
   */
  lastRespondedAt?: number /* int64 */;
}
/**
 * Content is the posting's own text.
 */
export interface Content {
  description?: string;
  descriptionHtml?: string;
  metaDescription?: string;
  ogImage?: string;
}
/**
 * JobDetail is one job's own page, which carries more than a search card does.
 * Normalized projects it onto NormalizedJob for callers wanting the common
 * shape.
 */
export interface JobDetail {
  sourceKey: string;
  externalId?: string;
  url: string;
  title: string;
  category?: string;
  /**
   * Employment is the schema.org term: FULL_TIME, PART_TIME, CONTRACTOR.
   */
  employment?: string;
  /**
   * DirectApply reports whether the application is made on the board itself
   * rather than on the employer's site.
   */
  directApply: boolean;
  recruiterId?: number /* int */;
  company: Company;
  salary: Salary;
  location: Location;
  requirements: Requirements;
  timeline: Timeline;
  activity: Activity;
  content: Content;
  /**
   * Badges are labels the board shows that no other field already carries.
   */
  badges?: string[];
  /**
   * OtherFacts are rows the parser recognised as facts but has no field for,
   * which is where a newly added row shows up before it earns one.
   */
  otherFacts?: string[];
}

//////////
// source: job.go

export const SourceKindAPI = "api";
export const SourceKindScrape = "scrape";
export const SourceKindSidecar = "sidecar";
/**
 * SourceKindManual backs hand-entered vacancies on hosts no adapter reads.
 * It is never crawled — its adapter's Search fails permanently (041 D4).
 */
export const SourceKindManual = "manual";
export type SourceKind = typeof SourceKindAPI | typeof SourceKindScrape | typeof SourceKindSidecar | typeof SourceKindManual;
export interface NormalizedJob {
  sourceKey: string;
  externalId?: string;
  title: string;
  company: string;
  location?: string;
  remote: boolean;
  salaryRaw?: string;
  url: string;
  description: string;
  postedAt?: string;
  raw: any;
  experienceLevel?: string;
  experienceMinYears?: number /* int */;
  englishLevel?: string;
  salaryEstimateRaw?: string;
  salaryEstimateMin?: number /* int */;
  salaryEstimateMax?: number /* int */;
  salaryEstimateCurrency?: string;
}
export interface SearchQuery {
  keywords: string;
  location?: string;
  remote?: boolean;
  salaryMin?: number /* float64 */;
  country?: string;
  sources?: string[];
  subscriptionUrl?: string;
}
export interface JobSourceDto {
  id: string;
  key: string;
  kind: SourceKind;
  enabled: boolean;
  healthy: boolean;
  config: { [key: string]: any};
}
