// Code generated by tygo. DO NOT EDIT.

//////////
// source: dto.go
/*
Package dto defines the wire-format structs served by the HTTP API.
These are the Go source of truth for tygo-generated dashboard TypeScript
types; field names/JSON tags must match packages/shared/src/index.ts
exactly (field-for-field) so the existing React dashboard needs zero changes.
*/

export type SourceKind = string;
export const SourceKindAPI: SourceKind = "api";
export const SourceKindScrape: SourceKind = "scrape";
export const SourceKindSidecar: SourceKind = "sidecar";
export type ApplicationStatus = string;
export const StatusFound: ApplicationStatus = "found";
export const StatusShortlisted: ApplicationStatus = "shortlisted";
export const StatusDocsGenerated: ApplicationStatus = "docs_generated";
export const StatusApplied: ApplicationStatus = "applied";
export const StatusInterview: ApplicationStatus = "interview";
export const StatusOffer: ApplicationStatus = "offer";
export const StatusRejected: ApplicationStatus = "rejected";
/**
 * OutcomeEventType is the append-only outcome event log's enum (spec 010,
 * migration 00012_application_outcome.sql). A "response" is any event whose
 * type is not OutcomeApplied — silence (only `applied` recorded) is a
 * non-response, never an exclusion.
 */
export type OutcomeEventType = string;
export const OutcomeApplied: OutcomeEventType = "applied";
export const OutcomeViewed: OutcomeEventType = "viewed";
export const OutcomeScreen: OutcomeEventType = "screen";
export const OutcomeOffer: OutcomeEventType = "offer";
export const OutcomeRejected: OutcomeEventType = "rejected";
export type DocumentType = string;
export const DocumentTypeResume: DocumentType = "resume";
export const DocumentTypeCoverLetter: DocumentType = "cover_letter";
/**
 * NormalizedJob is the canonical job shape every source adapter must produce.
 */
export interface NormalizedJob {
  sourceKey: string;
  externalId?: string;
  title: string;
  company: string;
  location?: string;
  remote: boolean;
  salaryRaw?: string;
  url: string;
  description: string;
  postedAt?: string; // ISO date
  raw: any;
}
/**
 * SearchQuery is the query shape a saved search stores and adapters receive.
 */
export interface SearchQuery {
  keywords: string;
  location?: string;
  remote?: boolean;
  salaryMin?: number /* float64 */;
  country?: string;
  sources?: string[];
  site?: string; // 'linkedin' | 'indeed' | 'glassdoor'
  /**
   * SubscriptionURL, when set, tells an adapter to scrape this saved-filter
   * URL (e.g. a djinni subs page) instead of running a keyword search.
   */
  subscriptionUrl?: string;
}
export interface ResumeLocation {
  city?: string;
  countryCode?: string;
  region?: string;
}
export interface ResumeProfile {
  network?: string;
  username?: string;
  url?: string;
}
export interface ResumeBasics {
  name?: string;
  label?: string;
  email?: string;
  phone?: string;
  url?: string;
  summary?: string;
  location?: ResumeLocation;
  profiles?: ResumeProfile[];
}
export interface ResumeWork {
  name: string;
  position?: string;
  url?: string;
  startDate?: string;
  endDate?: string;
  summary?: string;
  highlights?: string[];
}
export interface ResumeEducation {
  institution: string;
  area?: string;
  studyType?: string;
  startDate?: string;
  endDate?: string;
}
export interface ResumeSkill {
  name: string;
  level?: string;
  keywords?: string[];
}
export interface ResumeProject {
  name: string;
  description?: string;
  url?: string;
  keywords?: string[];
  highlights?: string[];
}
export interface ResumeLanguage {
  language?: string;
  fluency?: string;
}
export interface ResumeCertificate {
  name?: string;
  issuer?: string;
  date?: string;
}
export interface JsonResume {
  basics?: ResumeBasics;
  work?: ResumeWork[];
  education?: ResumeEducation[];
  skills?: ResumeSkill[];
  projects?: ResumeProject[];
  languages?: ResumeLanguage[];
  certificates?: ResumeCertificate[];
}
export interface MatchResultDto {
  id: string;
  jobId: string;
  similarity: number /* float64 */;
  score?: number /* int */;
  matchedSkills?: string[];
  missingSkills?: string[];
  summary?: string;
  redFlags?: string[];
  model: string;
  createdAt: string;
}
export interface JobDto {
  id: string;
  dedupeKey: string;
  sourceKey: string;
  title: string;
  company: string;
  location?: string;
  remote: boolean;
  salaryRaw?: string;
  url: string;
  description: string;
  descriptionHtml?: string;
  postedAt?: string;
  ingestedAt: string;
  status: string; // ApplicationStatus | 'hidden'
  matchResult?: MatchResultDto;
  documents?: GeneratedDocumentDto[];
  application?: ApplicationDto;
  /**
   * Salary inference (spec 006). All five are nil together when no source
   * could produce a band (FR-009) — SalaryRaw is preserved and displayed
   * alongside regardless (FR-024).
   */
  salaryMin?: number /* int */;
  salaryMax?: number /* int */;
  salaryCurrency?: string;
  salaryConfidence?: number /* float64 */;
  salarySource?: string;
  /**
   * SalaryBelowFloor is computed (not stored) against the configured
   * SALARY_FLOOR_USD; true only when the band's currency is USD and its
   * max lies entirely below the floor (FR-016, FR-020 fail-open for other
   * currencies).
   */
  salaryBelowFloor: boolean;
}
export interface JobListResponse {
  items: JobDto[];
  total: number /* int64 */;
  page: number /* int */;
  pageSize: number /* int */;
}
export interface GeneratedDocumentDto {
  id: string;
  jobId?: string;
  type: string;
  version: number /* int */;
  content: any;
  pdfPath?: string;
  model: string;
  company?: string;
  title?: string;
  vacancy?: string;
  createdAt: string;
}
export interface RendercvSummaryExperience {
  company: string;
  highlightCount: number /* int */;
}
export interface RendercvSummary {
  name: string;
  headline: string;
  skillGroups: string[];
  experience: RendercvSummaryExperience[];
}
export interface ProfileDto {
  id: string;
  name: string;
  hasConfig: boolean;
  rendercvConfig?: RendercvSummary;
  rendercvFull?: any;
  extraNotes?: string;
  updatedAt: string;
}
export interface JobSourceDto {
  id: string;
  key: string;
  kind: SourceKind;
  enabled: boolean;
  healthy: boolean;
  config: { [key: string]: any};
}
export interface SavedSearchDto {
  id: string;
  name: string;
  query: SearchQuery;
  cron: string;
  enabled: boolean;
  lastRunAt?: string;
}
/**
 * SubscriptionDto is a URL-based subscription attached to a job source: a
 * saved-filter URL on the site itself (e.g. a djinni subs page or a dou
 * category listing). Fetching the URL is deferred; this is CRUD + enable only.
 */
export interface SubscriptionDto {
  id: string;
  sourceKey: string;
  name?: string;
  url: string;
  enabled: boolean;
  lastRunAt?: string;
}
export interface SourceRunDto {
  id: string;
  sourceKey: string;
  searchId?: string;
  startedAt: string;
  finishedAt?: string;
  ok?: boolean;
  found: number /* int */;
  new: number /* int */;
  error?: string;
}
export interface ApplicationEvent {
  status: string;
  at: string;
}
/**
 * ApplicationOutcomeDto is one row of the append-only outcome event log.
 * OccurredAt is when the real-world event happened (may be back-dated);
 * RecordedAt is when the row was written and is never back-dated.
 */
export interface ApplicationOutcomeDto {
  id: string;
  applicationId: string;
  eventType: OutcomeEventType;
  occurredAt: string;
  recordedAt: string;
  note?: string;
}
export interface ApplicationDto {
  id: string;
  jobId: string;
  status: ApplicationStatus;
  notes?: string;
  appliedAt?: string;
  events: ApplicationEvent[];
  updatedAt: string;
  job?: JobDto;
}
export interface StatsDto {
  jobsTotal: number /* int64 */;
  jobsLast24h: number /* int64 */;
  highFit: number /* int64 */;
  pipeline: { [key: string]: number /* int64 */};
  recentRuns: SourceRunDto[];
}
export interface GenerateRequestDto {
  type: DocumentType;
  profileId?: string;
}
/**
 * KeywordDiffTermDto is one term in a keyword-diff bucket (008-4). The JSON
 * shape mirrors the persisted KeywordDiff jsonb (spec 008-1 §3) so the wire
 * format and the cache stay identical.
 */
export interface KeywordDiffTermDto {
  term: string;
  canonical: string;
  polarity: string; // "required" | "preferred"
  normalized: string;
  matchType?: string; // "exact" | "normalized"
}
/**
 * KeywordDiffMetadataDto carries the coverage counters the diff panel renders.
 */
export interface KeywordDiffMetadataDto {
  totalRequired: number /* int */;
  totalPreferred: number /* int */;
  matchedRequired: number /* int */;
  matchedPreferred: number /* int */;
  coveragePct: number /* float64 */;
}
/**
 * KeywordRephraseSuggestionDto is an advisory, truthful rephrase for a missing
 * required term (008-5). Rephrase is null when no honest rephrase is available.
 */
export interface KeywordRephraseSuggestionDto {
  term: string;
  canonical: string;
  rephrase?: string;
  sourceBullet?: string;
  reason?: string;
}
/**
 * KeywordDiffDto is the response served by GET /api/jobs/{id}/keyword-diff:
 * the three diff buckets, coverage metadata, and any advisory rephrase
 * suggestions for the missing-required terms.
 */
export interface KeywordDiffDto {
  jobId: string;
  matched: KeywordDiffTermDto[];
  missingRequired: KeywordDiffTermDto[];
  missingPreferred: KeywordDiffTermDto[];
  metadata: KeywordDiffMetadataDto;
  suggestions: KeywordRephraseSuggestionDto[];
}
/**
 * ActivityRunDto is one row of under-the-hood async task activity (ingest,
 * match, generate, enrich), live progress and recent history alike.
 */
export interface ActivityRunDto {
  id: string;
  op: string;
  state: string;
  label: string;
  step?: string;
  jobId?: string;
  sourceKey?: string;
  refId?: string;
  error?: string;
  meta: { [key: string]: any};
  createdAt: string;
  startedAt?: string;
  finishedAt?: string;
  elapsedMs?: number /* int64 */;
}
export interface ActivityListResponse {
  active: ActivityRunDto[];
  recent: ActivityRunDto[];
}
/**
 * PostAgeBucketState is the three-state output contract for the post-age
 * vs response-rate signal (spec 010 §Cold-Start Honesty).
 */
export type PostAgeBucketState = string;
export const PostAgeStateObserved: PostAgeBucketState = "observed";
export const PostAgeStatePrior: PostAgeBucketState = "prior";
export const PostAgeStateInsufficient: PostAgeBucketState = "insufficient";
/**
 * PostAgeBucketDto is one bucket in the post-age vs response-rate signal.
 * Rate is null unless State == PostAgeStateObserved. N is always present
 * so the caller can render sample size alongside any rate.
 */
export interface PostAgeBucketDto {
  bucket: string;
  n: number /* int32 */;
  responses: number /* int32 */;
  rate?: number /* float64 */;
  state: PostAgeBucketState;
}
/**
 * PostAgeResponseDto is the full signal response served by
 * GET /api/postage-response-rate.
 */
export interface PostAgeResponseDto {
  buckets: PostAgeBucketDto[];
  totalApps: number /* int32 */;
  globalState: PostAgeBucketState;
  priorRate: number /* float64 */;
  priorLabel: string;
  thresholdMsg?: string;
}
/**
 * FreshMatchNotificationDto is one row of the fresh-match notification table,
 * served by GET /api/notifications.
 */
export interface FreshMatchNotificationDto {
  id: string;
  jobId: string;
  matchResultId: string;
  fresh: boolean;
  seen: boolean;
  createdAt: string;
  /**
   * JobTitle and Company are populated by the list endpoint via a JOIN.
   */
  jobTitle?: string;
  company?: string;
  matchScore?: number /* int32 */;
}
/**
 * CompanyIntelDto is the flattened company-intel signal set served by
 * GET /api/companies/{jobId}/intel and POST /api/companies/{jobId}/intel/refresh
 * (spec 004). Each of the five CompanySignal rows for the job's company is
 * flattened into one named field; a nil field means that signal has never
 * been captured (or its source failed and no previous value exists yet).
 */
export interface CompanyIntelDto {
  companyName: string;
  website?: string;
  funding?: string;
  layoffs?: string;
  glassdoorRating?: number /* float64 */;
  headcount?: string;
  techStack?: string;
  fetchedAt: string;
  /**
   * Error is set on a Refresh response when every source failed (FR-007):
   * previous values (if any) remain in the other fields, and the
   * dashboard shows a top-level error banner.
   */
  error?: string;
}
/**
 * JobContactDto is one resolved recruiter/hiring-manager candidate served
 * by GET /api/jobs/{id}/contacts and POST /api/jobs/{id}/contacts/refresh
 * (spec 007). Nil fields mean that channel was never resolved — never
 * fabricated (FR-006, FR-008). Email/phone/linkedInUrl are sensitive
 * (FR-018): the API surfaces them only on this endpoint, and callers must
 * not log them in full.
 */
export interface JobContactDto {
  id: string;
  name: string;
  title?: string;
  linkedInUrl?: string;
  email?: string;
  phone?: string;
  /**
   * Source is one of "posting" / "company-page" / "linkedin".
   */
  source: string;
  confidence: number /* float64 */;
  fetchedAt: string;
}
