#!/usr/bin/env bash
#
# Generate Pydantic models in apps/ai/src/jobfinder_ai/contracts from the
# JSON Schema in apps/api/internal/events/schema (itself generated from the
# Go event structs by `just contracts-generate`).
#
# Regenerates the whole contracts/ package from scratch so stale files never
# linger. Run via `just contracts-generate`.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AI_DIR="$REPO_ROOT/apps/ai"
SCHEMA_DIR="$REPO_ROOT/apps/api/internal/events/schema"
OUT_DIR="$AI_DIR/src/jobfinder_ai/contracts"

HEADER='# ------------------------------------------------------------------
# GENERATED FILE - DO NOT EDIT.
#
# Generated by scripts/contracts-generate-ai.sh from the JSON Schema in
# apps/api/internal/events/schema, which is itself generated from the Go
# event structs in apps/api/internal/events (`just contracts-generate`).
# ------------------------------------------------------------------
'

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

(
  cd "$AI_DIR"
  uv run datamodel-codegen \
    --input "$SCHEMA_DIR" \
    --input-file-type jsonschema \
    --output "$OUT_DIR" \
    --output-model-type pydantic_v2.BaseModel \
    --target-python-version 3.13 \
    --use-schema-description \
    --disable-timestamp \
    --formatters black --formatters isort
)

# Drop the redundant "_schema" suffix datamodel-codegen adds to filenames
# (e.g. match_work_schema.py -> match_work.py) and prepend the do-not-edit
# header to every generated module.
for f in "$OUT_DIR"/*_schema.py; do
  base="$(basename "$f" "_schema.py")"
  mv "$f" "$OUT_DIR/$base.py"
done

for f in "$OUT_DIR"/*.py; do
  [[ "$(basename "$f")" == "__init__.py" ]] && continue
  tmp="$(mktemp)"
  printf '%s' "$HEADER" > "$tmp"
  cat "$f" >> "$tmp"
  mv "$tmp" "$f"
done

# Regenerate __init__.py re-exporting each schema's top-level model for
# convenient imports, e.g. `from jobfinder_ai.contracts import MatchWork`.
# Only the class matching the schema title is exported here: some schemas
# (e.g. result.schema.json) inline nested objects as extra classes that
# duplicate other top-level schemas (Failure, Usage) and would collide.
pascal_case() {
  IFS='_' read -ra parts <<< "$1"
  for p in "${parts[@]}"; do
    printf '%s%s' "${p:0:1}" "${p:1}" | awk '{print toupper(substr($0,1,1)) substr($0,2)}' | tr -d '\n'
  done
}

{
  printf '%s' "$HEADER"
  echo
  declare -a all_classes=()
  for f in "$OUT_DIR"/*.py; do
    [[ "$(basename "$f")" == "__init__.py" ]] && continue
    module="$(basename "$f" .py)"
    cls="$(pascal_case "$module")"
    echo "from jobfinder_ai.contracts.${module} import ${cls}"
    all_classes+=("$cls")
  done
  echo
  echo '__all__ = ['
  for cls in "${all_classes[@]}"; do
    echo "    \"${cls}\","
  done
  echo ']'
} > "$OUT_DIR/__init__.py"

(cd "$AI_DIR" && uv run ruff format "$OUT_DIR" >/dev/null && uv run ruff check --fix "$OUT_DIR" >/dev/null)

echo "generated Pydantic contracts in ${OUT_DIR#$REPO_ROOT/}"
