import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Principles',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'principles' }],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },
    {
      type: 'category',
      label: 'Backend',
      items: [{ type: 'autogenerated', dirName: 'backend' }],
    },
    {
      type: 'category',
      label: 'Data',
      items: [{ type: 'autogenerated', dirName: 'data' }],
    },
    {
      type: 'category',
      label: 'Job Sources & Ingestion',
      items: [{ type: 'autogenerated', dirName: 'ingestion' }],
    },
    {
      type: 'category',
      label: 'AI & LLM',
      items: [{ type: 'autogenerated', dirName: 'ai' }],
    },
    {
      type: 'category',
      label: 'Async & Workers',
      items: [{ type: 'autogenerated', dirName: 'async' }],
    },
    {
      type: 'category',
      label: 'Frontend',
      items: [{ type: 'autogenerated', dirName: 'frontend' }],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [{ type: 'autogenerated', dirName: 'operations' }],
    },
  ],
};

export default sidebars;
