// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const getJobByDedupeKey = `-- name: GetJobByDedupeKey :one
SELECT "id" FROM "Job" WHERE "dedupeKey" = $1
`

func (q *Queries) GetJobByDedupeKey(ctx context.Context, dedupekey string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getJobByDedupeKey, dedupekey)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status FROM "Job" WHERE "id" = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.SourceKey,
		&i.ExternalId,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.SalaryRaw,
		&i.Url,
		&i.Description,
		&i.Raw,
		&i.PostedAt,
		&i.IngestedAt,
		&i.Embedding,
		&i.Status,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO "Job" (
  "dedupeKey", "sourceKey", "externalId", "title", "company", "location",
  "remote", "salaryRaw", "url", "description", "raw", "postedAt"
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status
`

type InsertJobParams struct {
	DedupeKey   string           `json:"dedupeKey"`
	SourceKey   string           `json:"sourceKey"`
	ExternalId  *string          `json:"externalId"`
	Title       string           `json:"title"`
	Company     string           `json:"company"`
	Location    *string          `json:"location"`
	Remote      bool             `json:"remote"`
	SalaryRaw   *string          `json:"salaryRaw"`
	Url         string           `json:"url"`
	Description string           `json:"description"`
	Raw         []byte           `json:"raw"`
	PostedAt    pgtype.Timestamp `json:"postedAt"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.DedupeKey,
		arg.SourceKey,
		arg.ExternalId,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Remote,
		arg.SalaryRaw,
		arg.Url,
		arg.Description,
		arg.Raw,
		arg.PostedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.SourceKey,
		&i.ExternalId,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.SalaryRaw,
		&i.Url,
		&i.Description,
		&i.Raw,
		&i.PostedAt,
		&i.IngestedAt,
		&i.Embedding,
		&i.Status,
	)
	return i, err
}

const updateJobEmbedding = `-- name: UpdateJobEmbedding :exec
UPDATE "Job" SET "embedding" = $2 WHERE "id" = $1
`

type UpdateJobEmbeddingParams struct {
	ID        pgtype.UUID      `json:"id"`
	Embedding *pgvector.Vector `json:"embedding"`
}

func (q *Queries) UpdateJobEmbedding(ctx context.Context, arg UpdateJobEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateJobEmbedding, arg.ID, arg.Embedding)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE "Job" SET "status" = $2 WHERE "id" = $1
RETURNING id, "dedupeKey", "sourceKey", "externalId", title, company, location, remote, "salaryRaw", url, description, raw, "postedAt", "ingestedAt", embedding, status
`

type UpdateJobStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.DedupeKey,
		&i.SourceKey,
		&i.ExternalId,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.SalaryRaw,
		&i.Url,
		&i.Description,
		&i.Raw,
		&i.PostedAt,
		&i.IngestedAt,
		&i.Embedding,
		&i.Status,
	)
	return i, err
}
