// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobsource.sql

package sqlcgen

import (
	"context"
)

const getJobSourceByKey = `-- name: GetJobSourceByKey :one
SELECT id, key, kind, enabled, config, healthy FROM "JobSource" WHERE "key" = $1
`

func (q *Queries) GetJobSourceByKey(ctx context.Context, key string) (JobSource, error) {
	row := q.db.QueryRow(ctx, getJobSourceByKey, key)
	var i JobSource
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Kind,
		&i.Enabled,
		&i.Config,
		&i.Healthy,
	)
	return i, err
}

const listEnabledJobSources = `-- name: ListEnabledJobSources :many
SELECT id, key, kind, enabled, config, healthy FROM "JobSource" WHERE "enabled" = true
`

func (q *Queries) ListEnabledJobSources(ctx context.Context) ([]JobSource, error) {
	rows, err := q.db.Query(ctx, listEnabledJobSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobSource
	for rows.Next() {
		var i JobSource
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Kind,
			&i.Enabled,
			&i.Config,
			&i.Healthy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobSources = `-- name: ListJobSources :many
SELECT id, key, kind, enabled, config, healthy FROM "JobSource" ORDER BY "key"
`

func (q *Queries) ListJobSources(ctx context.Context) ([]JobSource, error) {
	rows, err := q.db.Query(ctx, listJobSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobSource
	for rows.Next() {
		var i JobSource
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Kind,
			&i.Enabled,
			&i.Config,
			&i.Healthy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setJobSourceConfig = `-- name: SetJobSourceConfig :exec
UPDATE "JobSource" SET "config" = $2 WHERE "key" = $1
`

type SetJobSourceConfigParams struct {
	Key    string `json:"key"`
	Config []byte `json:"config"`
}

func (q *Queries) SetJobSourceConfig(ctx context.Context, arg SetJobSourceConfigParams) error {
	_, err := q.db.Exec(ctx, setJobSourceConfig, arg.Key, arg.Config)
	return err
}

const setJobSourceEnabled = `-- name: SetJobSourceEnabled :exec
UPDATE "JobSource" SET "enabled" = $2 WHERE "key" = $1
`

type SetJobSourceEnabledParams struct {
	Key     string `json:"key"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) SetJobSourceEnabled(ctx context.Context, arg SetJobSourceEnabledParams) error {
	_, err := q.db.Exec(ctx, setJobSourceEnabled, arg.Key, arg.Enabled)
	return err
}

const setJobSourceHealthy = `-- name: SetJobSourceHealthy :exec
UPDATE "JobSource" SET "healthy" = $2 WHERE "key" = $1
`

type SetJobSourceHealthyParams struct {
	Key     string `json:"key"`
	Healthy bool   `json:"healthy"`
}

func (q *Queries) SetJobSourceHealthy(ctx context.Context, arg SetJobSourceHealthyParams) error {
	_, err := q.db.Exec(ctx, setJobSourceHealthy, arg.Key, arg.Healthy)
	return err
}

const upsertJobSource = `-- name: UpsertJobSource :exec
INSERT INTO "JobSource" ("key", "kind", "config")
VALUES ($1, $2, $3)
ON CONFLICT ("key") DO UPDATE SET "kind" = EXCLUDED."kind"
`

type UpsertJobSourceParams struct {
	Key    string `json:"key"`
	Kind   string `json:"kind"`
	Config []byte `json:"config"`
}

func (q *Queries) UpsertJobSource(ctx context.Context, arg UpsertJobSourceParams) error {
	_, err := q.db.Exec(ctx, upsertJobSource, arg.Key, arg.Kind, arg.Config)
	return err
}
