// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matchresult.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMatchResultByJobID = `-- name: GetMatchResultByJobID :one
SELECT id, "jobId", similarity, score, "matchedSkills", "missingSkills", summary, "redFlags", model, "createdAt" FROM "MatchResult" WHERE "jobId" = $1
`

func (q *Queries) GetMatchResultByJobID(ctx context.Context, jobid pgtype.UUID) (MatchResult, error) {
	row := q.db.QueryRow(ctx, getMatchResultByJobID, jobid)
	var i MatchResult
	err := row.Scan(
		&i.ID,
		&i.JobId,
		&i.Similarity,
		&i.Score,
		&i.MatchedSkills,
		&i.MissingSkills,
		&i.Summary,
		&i.RedFlags,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const upsertMatchResult = `-- name: UpsertMatchResult :one
INSERT INTO "MatchResult" (
  "jobId", "similarity", "score", "matchedSkills", "missingSkills", "summary", "redFlags", "model"
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT ("jobId") DO UPDATE SET
  "similarity" = EXCLUDED."similarity",
  "score" = EXCLUDED."score",
  "matchedSkills" = EXCLUDED."matchedSkills",
  "missingSkills" = EXCLUDED."missingSkills",
  "summary" = EXCLUDED."summary",
  "redFlags" = EXCLUDED."redFlags",
  "model" = EXCLUDED."model"
RETURNING id, "jobId", similarity, score, "matchedSkills", "missingSkills", summary, "redFlags", model, "createdAt"
`

type UpsertMatchResultParams struct {
	JobId         pgtype.UUID `json:"jobId"`
	Similarity    float64     `json:"similarity"`
	Score         *int32      `json:"score"`
	MatchedSkills []byte      `json:"matchedSkills"`
	MissingSkills []byte      `json:"missingSkills"`
	Summary       *string     `json:"summary"`
	RedFlags      []byte      `json:"redFlags"`
	Model         string      `json:"model"`
}

func (q *Queries) UpsertMatchResult(ctx context.Context, arg UpsertMatchResultParams) (MatchResult, error) {
	row := q.db.QueryRow(ctx, upsertMatchResult,
		arg.JobId,
		arg.Similarity,
		arg.Score,
		arg.MatchedSkills,
		arg.MissingSkills,
		arg.Summary,
		arg.RedFlags,
		arg.Model,
	)
	var i MatchResult
	err := row.Scan(
		&i.ID,
		&i.JobId,
		&i.Similarity,
		&i.Score,
		&i.MatchedSkills,
		&i.MissingSkills,
		&i.Summary,
		&i.RedFlags,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}
