// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sourcerun.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishSourceRunError = `-- name: FinishSourceRunError :exec
UPDATE "SourceRun" SET "finishedAt" = now(), "ok" = false, "error" = $2
WHERE "id" = $1
`

type FinishSourceRunErrorParams struct {
	ID    pgtype.UUID `json:"id"`
	Error *string     `json:"error"`
}

func (q *Queries) FinishSourceRunError(ctx context.Context, arg FinishSourceRunErrorParams) error {
	_, err := q.db.Exec(ctx, finishSourceRunError, arg.ID, arg.Error)
	return err
}

const finishSourceRunOk = `-- name: FinishSourceRunOk :exec
UPDATE "SourceRun" SET "finishedAt" = now(), "ok" = true, "found" = $2, "new" = $3
WHERE "id" = $1
`

type FinishSourceRunOkParams struct {
	ID    pgtype.UUID `json:"id"`
	Found int32       `json:"found"`
	New   int32       `json:"new"`
}

func (q *Queries) FinishSourceRunOk(ctx context.Context, arg FinishSourceRunOkParams) error {
	_, err := q.db.Exec(ctx, finishSourceRunOk, arg.ID, arg.Found, arg.New)
	return err
}

const insertSourceRun = `-- name: InsertSourceRun :one
INSERT INTO "SourceRun" ("sourceId", "searchId")
VALUES ($1, $2)
RETURNING id, "sourceId", "searchId", "startedAt", "finishedAt", ok, found, new, error
`

type InsertSourceRunParams struct {
	SourceId pgtype.UUID `json:"sourceId"`
	SearchId *string     `json:"searchId"`
}

func (q *Queries) InsertSourceRun(ctx context.Context, arg InsertSourceRunParams) (SourceRun, error) {
	row := q.db.QueryRow(ctx, insertSourceRun, arg.SourceId, arg.SearchId)
	var i SourceRun
	err := row.Scan(
		&i.ID,
		&i.SourceId,
		&i.SearchId,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Ok,
		&i.Found,
		&i.New,
		&i.Error,
	)
	return i, err
}

const recentRunsJoined = `-- name: RecentRunsJoined :many
SELECT
  sr."id" AS id,
  js."key" AS source_key,
  sr."searchId" AS search_id,
  sr."startedAt" AS started_at,
  sr."finishedAt" AS finished_at,
  sr."ok" AS ok,
  sr."found" AS found,
  sr."new" AS new,
  sr."error" AS error
FROM "SourceRun" sr
JOIN "JobSource" js ON js."id" = sr."sourceId"
ORDER BY sr."startedAt" DESC
LIMIT $1
`

type RecentRunsJoinedRow struct {
	ID         pgtype.UUID      `json:"id"`
	SourceKey  string           `json:"source_key"`
	SearchID   *string          `json:"search_id"`
	StartedAt  pgtype.Timestamp `json:"started_at"`
	FinishedAt pgtype.Timestamp `json:"finished_at"`
	Ok         *bool            `json:"ok"`
	Found      int32            `json:"found"`
	New        int32            `json:"new"`
	Error      *string          `json:"error"`
}

func (q *Queries) RecentRunsJoined(ctx context.Context, limit int32) ([]RecentRunsJoinedRow, error) {
	rows, err := q.db.Query(ctx, recentRunsJoined, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentRunsJoinedRow
	for rows.Next() {
		var i RecentRunsJoinedRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceKey,
			&i.SearchID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Ok,
			&i.Found,
			&i.New,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentSourceRunsForSource = `-- name: RecentSourceRunsForSource :many
SELECT "ok" FROM "SourceRun"
WHERE "sourceId" = $1 AND "ok" IS NOT NULL
ORDER BY "startedAt" DESC
LIMIT $2
`

type RecentSourceRunsForSourceParams struct {
	SourceId pgtype.UUID `json:"sourceId"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) RecentSourceRunsForSource(ctx context.Context, arg RecentSourceRunsForSourceParams) ([]*bool, error) {
	rows, err := q.db.Query(ctx, recentSourceRunsForSource, arg.SourceId, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*bool
	for rows.Next() {
		var ok *bool
		if err := rows.Scan(&ok); err != nil {
			return nil, err
		}
		items = append(items, ok)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
