root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./server ./cmd/server"
  bin = "./server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "data", "seed"]
  exclude_regex = ["_test\\.go$"]
  delay = 300
  stop_on_error = true
  send_interrupt = true
  kill_delay = "2s"

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
